import { type ContentPillar } from "@/types";

export interface ComparisonFeature {
  feature: string;
  optionA: string;
  optionB: string;
}

export interface ComparisonPage {
  slug: string;
  title: string;
  seoTitle: string;
  seoDescription: string;
  optionA: string;
  optionB: string;
  verdict: string;
  verdictWinner: "A" | "B" | "depends";
  pillar: ContentPillar;
  features: ComparisonFeature[];
  bestForA: string[];
  bestForB: string[];
  relatedArticle?: string;
  relatedTool?: string;
}

export const COMPARISONS: ComparisonPage[] = [
  {
    slug: "coach-vs-app",
    title: "Cycling Coach vs Training App",
    seoTitle: "Cycling Coach vs Training App — Which Do You Need?",
    seoDescription: "When does a cycling coach beat a training app? Side-by-side comparison of cost, personalisation, accountability, and results.",
    optionA: "Cycling Coach",
    optionB: "Training App",
    verdict: "A coach wins when you've plateaued, need accountability, or have complex life constraints. An app wins when you're a beginner, budget-conscious, or still making easy gains.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Personalisation", optionA: "Fully personalised weekly", optionB: "Algorithm-adjusted" },
      { feature: "Accountability", optionA: "Weekly calls + plan reviews", optionB: "Self-directed" },
      { feature: "Cost", optionA: "$150-300/month", optionB: "$15-30/month" },
      { feature: "Nutrition guidance", optionA: "Included", optionB: "Not included" },
      { feature: "Strength programming", optionA: "Included", optionB: "Rarely included" },
      { feature: "Life context adjustment", optionA: "Real-time, human", optionB: "Limited or none" },
      { feature: "Best for beginners", optionA: "Overkill", optionB: "Ideal" },
      { feature: "Best for plateaued riders", optionA: "Ideal", optionB: "Insufficient" },
    ],
    bestForA: [
      "Riders who've plateaued after 2+ years of structured training",
      "Time-crunched professionals who need every hour to count",
      "Riders with specific event goals and a date on the calendar",
      "Anyone who needs accountability to stay consistent",
    ],
    bestForB: [
      "Beginners in their first 1-2 years of structured training",
      "Budget-conscious riders making easy gains",
      "Self-motivated riders who follow plans independently",
      "Riders who prefer a virtual-world experience (Zwift)",
    ],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
    relatedTool: "/assessment",
  },
  {
    slug: "polarised-vs-pyramidal",
    title: "Polarised vs Pyramidal Training",
    seoTitle: "Polarised vs Pyramidal Training for Cyclists",
    seoDescription: "Polarised training (80/20) vs pyramidal distribution — which intensity model produces better results for amateur cyclists?",
    optionA: "Polarised (80/20)",
    optionB: "Pyramidal",
    verdict: "Polarised has stronger research support for most amateurs. Pyramidal works for riders with very high volume. Both beat the grey-zone middle that most cyclists default to.",
    verdictWinner: "A",
    pillar: "coaching",
    features: [
      { feature: "Easy training %", optionA: "~80%", optionB: "~75%" },
      { feature: "Moderate (Zone 3) %", optionA: "~0-5%", optionB: "~15-20%" },
      { feature: "High intensity %", optionA: "~15-20%", optionB: "~5-10%" },
      { feature: "Research support", optionA: "Strong (Seiler)", optionB: "Moderate" },
      { feature: "Best for time-crunched", optionA: "Yes", optionB: "Needs more volume" },
      { feature: "Recovery demand", optionA: "Manageable", optionB: "Higher due to Zone 3" },
    ],
    bestForA: [
      "Time-crunched riders (6-10 hours/week)",
      "Masters cyclists who need to manage recovery",
      "Riders who plateau doing lots of tempo work",
    ],
    bestForB: [
      "High-volume riders (15+ hours/week)",
      "Riders who naturally thrive on tempo-paced group rides",
      "Stage-race athletes building sustained aerobic capacity",
    ],
    relatedArticle: "/blog/polarised-vs-sweet-spot-training",
  },
  {
    slug: "strength-vs-more-miles",
    title: "Strength Training vs More Miles",
    seoTitle: "Strength Training vs More Riding for Cyclists",
    seoDescription: "Should cyclists lift weights or ride more? Side-by-side comparison of strength training vs extra volume for amateur and masters riders.",
    optionA: "Strength Training",
    optionB: "More Riding Volume",
    verdict: "For riders over 35 or those training under 10 hours/week, strength training produces better returns per hour than adding more riding volume. For high-volume riders under 35 with no injury history, more riding still wins.",
    verdictWinner: "depends",
    pillar: "strength",
    features: [
      { feature: "Time investment", optionA: "2-3 sessions/week (45-60min)", optionB: "3-5 extra hours/week riding" },
      { feature: "Injury prevention", optionA: "Strong evidence", optionB: "No direct benefit" },
      { feature: "FTP improvement", optionA: "8-15% (Rønnestad)", optionB: "5-10% with more volume" },
      { feature: "Masters benefit", optionA: "Critical after 40", optionB: "Diminishing returns" },
      { feature: "Cycling economy", optionA: "4-5% improvement", optionB: "Marginal" },
      { feature: "Recovery cost", optionA: "Manageable if programmed", optionB: "Fatigue accumulation risk" },
    ],
    bestForA: ["Masters riders over 40", "Time-crunched riders under 10 hours/week", "Riders with recurring injuries", "Anyone who has never done structured S&C"],
    bestForB: ["Young riders with no injury history", "Riders with 15+ hours available", "Riders already lifting consistently", "Ultra-endurance athletes building volume"],
    relatedArticle: "/blog/new-study-confirms-heavy-strength-training-beats-more-miles-after-40",
    relatedTool: "/strength-training",
  },
  {
    slug: "indoor-vs-outdoor-training",
    title: "Indoor vs Outdoor Training",
    seoTitle: "Indoor vs Outdoor Cycling Training — Which Is Better?",
    seoDescription: "Indoor training vs outdoor riding for cyclists. Time efficiency, workout quality, skill development, and how to balance both for maximum gains.",
    optionA: "Indoor Training",
    optionB: "Outdoor Riding",
    verdict: "Indoor training wins on time efficiency and workout precision. Outdoor riding wins on skill development, mental health, and race-specific fitness. The best cyclists do both — structured work inside, volume and skills outside.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Time efficiency", optionA: "60min indoor = 90min outdoor", optionB: "Includes travel, coasting, stops" },
      { feature: "Workout precision", optionA: "Exact power targets via ERG", optionB: "Terrain-dependent" },
      { feature: "Skill development", optionA: "None", optionB: "Cornering, descending, bunch riding" },
      { feature: "Mental health", optionA: "Can feel isolating", optionB: "Daylight, fresh air, social" },
      { feature: "Race specificity", optionA: "Limited", optionB: "High" },
      { feature: "Weather independence", optionA: "Complete", optionB: "Season-dependent" },
    ],
    bestForA: ["Winter months", "Midweek structured sessions", "Time-crunched riders", "Riders with young children or shift work"],
    bestForB: ["Weekends and longer rides", "Group ride and race skills", "Mental freshness", "Race-specific preparation"],
    relatedArticle: "/blog/cycling-indoor-training-tips",
  },
  {
    slug: "heart-rate-vs-power",
    title: "Heart Rate vs Power Meter Training",
    seoTitle: "Heart Rate vs Power Meter for Cycling Training",
    seoDescription: "Should you train by heart rate or power? Comparison of accuracy, cost, and practical use for amateur cyclists.",
    optionA: "Power Meter",
    optionB: "Heart Rate Monitor",
    verdict: "Power is the gold standard — it measures output directly while heart rate measures response. But heart rate still has value for pacing easy rides, monitoring fatigue, and riders on a budget.",
    verdictWinner: "A",
    pillar: "coaching",
    features: [
      { feature: "Measures", optionA: "Work output (watts)", optionB: "Physiological response (bpm)" },
      { feature: "Instant feedback", optionA: "Yes", optionB: "Lags 30-90 seconds" },
      { feature: "Affected by fatigue", optionA: "No", optionB: "Yes (cardiac drift)" },
      { feature: "Affected by heat", optionA: "No", optionB: "Yes" },
      { feature: "Cost", optionA: "£200-600", optionB: "£30-80" },
      { feature: "Pacing value", optionA: "Excellent", optionB: "Good for easy rides" },
      { feature: "Training zones", optionA: "7-zone Coggan model", optionB: "5-zone approximate" },
    ],
    bestForA: ["Serious training with interval targets", "Event pacing", "FTP tracking and progression", "Anyone who can afford it"],
    bestForB: ["Budget-conscious riders", "Monitoring Zone 2 easy days", "Detecting overtraining via resting HR", "Beginners learning intensity"],
    relatedArticle: "/blog/cycling-power-meter-guide",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "trainerroad-vs-trainingpeaks",
    title: "TrainerRoad vs TrainingPeaks",
    seoTitle: "TrainerRoad vs TrainingPeaks for Cyclists",
    seoDescription: "TrainerRoad's adaptive plans vs TrainingPeaks' coach-driven platform. Which training software is right for your cycling goals?",
    optionA: "TrainerRoad",
    optionB: "TrainingPeaks",
    verdict: "TrainerRoad is a self-coaching engine — pick a plan, follow the workouts, let the algorithm adapt. TrainingPeaks is a platform your coach builds your plan on. If you have a coach, TrainingPeaks. If you're self-coached, TrainerRoad.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Primary use", optionA: "Self-coached adaptive training", optionB: "Coach-athlete platform" },
      { feature: "Plan creation", optionA: "Algorithm-generated", optionB: "Coach-built or purchased" },
      { feature: "Adaptive training", optionA: "Yes (AI-driven)", optionB: "Manual (coach adjusts)" },
      { feature: "Indoor workouts", optionA: "Built-in with ERG mode", optionB: "Syncs to Wahoo/Garmin" },
      { feature: "Analytics depth", optionA: "Good", optionB: "Excellent (PMC, CTL, ATL)" },
      { feature: "Cost", optionA: "~$20/month", optionB: "~$10-20/month + coach fee" },
    ],
    bestForA: ["Self-coached riders who want structure", "Indoor training focus", "Riders who want AI-adjusted plans", "Budget-conscious athletes"],
    bestForB: ["Riders working with a human coach", "Advanced analytics and periodisation", "Multi-sport athletes (triathlon)", "Riders who want full calendar control"],
    relatedArticle: "/blog/trainerroad-vs-online-cycling-coach",
  },
  {
    slug: "online-coach-vs-local-club",
    title: "Online Cycling Coach vs Local Club Training",
    seoTitle: "Online Coach vs Local Club for Cycling Training",
    seoDescription: "Should you hire an online cycling coach or train with your local club? Comparison of personalisation, cost, social benefits, and results.",
    optionA: "Online Coach",
    optionB: "Local Club Training",
    verdict: "An online coach delivers personalised, accountable, structured training. Club training delivers social riding, group dynamics, and race skills. The best approach: use a coach for structure and the club for fun and skills.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Personalisation", optionA: "Fully individualised", optionB: "One-size-fits-all group rides" },
      { feature: "Social element", optionA: "Community platform", optionB: "Strong (group rides, racing)" },
      { feature: "Cost", optionA: "$150-300/month", optionB: "$5-30/month membership" },
      { feature: "Skill development", optionA: "Limited (remote)", optionB: "Bunch riding, drafting, tactics" },
      { feature: "Accountability", optionA: "Weekly calls + reviews", optionB: "Peer motivation" },
      { feature: "Flexibility", optionA: "Train when you can", optionB: "Fixed group ride schedule" },
    ],
    bestForA: ["Riders who've plateaued on club training alone", "Time-crunched professionals", "Riders targeting specific events", "Riders not near a strong club"],
    bestForB: ["Social riders who thrive in groups", "Beginners learning to ride in a bunch", "Budget-conscious riders", "Riders who need race-simulation intensity"],
    relatedArticle: "/blog/cycling-coach-near-me-why-location-doesnt-matter-2026",
  },
  {
    slug: "ftp-ramp-test-vs-20-minute",
    title: "FTP Ramp Test vs 20-Minute Test",
    seoTitle: "FTP Ramp Test vs 20-Minute Test — Which Is More Accurate?",
    seoDescription: "Ramp test or 20-minute test for FTP? Accuracy, pacing difficulty, and which test suits your riding style and training goals.",
    optionA: "Ramp Test",
    optionB: "20-Minute Test",
    verdict: "The 20-minute test is more accurate for most riders but harder to pace. The ramp test is easier to execute and more repeatable but can overestimate FTP for riders with strong anaerobic capacity.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Accuracy", optionA: "Good (±3-5%)", optionB: "Better (±2-3%)" },
      { feature: "Pacing difficulty", optionA: "None (progressive)", optionB: "High (must hold steady)" },
      { feature: "Duration", optionA: "~20 min total", optionB: "~45 min with warm-up" },
      { feature: "Repeatability", optionA: "High", optionB: "Moderate (pacing varies)" },
      { feature: "Anaerobic bias", optionA: "Can overestimate", optionB: "Less biased" },
      { feature: "Mental difficulty", optionA: "Moderate", optionB: "Very high" },
    ],
    bestForA: ["New to FTP testing", "Riders who struggle with pacing", "Frequent retesting (every 4-6 weeks)", "Indoor training platforms"],
    bestForB: ["Experienced riders who can pace well", "More accurate zone calculation", "Riders training for TTs or steady-state events", "When absolute accuracy matters"],
    relatedArticle: "/blog/how-to-improve-ftp-cycling",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "sweet-spot-vs-threshold",
    title: "Sweet Spot vs Threshold Training",
    seoTitle: "Sweet Spot vs Threshold Training for Cyclists",
    seoDescription: "Sweet spot (88-94% FTP) vs threshold (95-105% FTP) training. Which builds more fitness, which costs more recovery, and when to use each.",
    optionA: "Sweet Spot (88-94% FTP)",
    optionB: "Threshold (95-105% FTP)",
    verdict: "Sweet spot delivers more training stimulus per unit of fatigue — ideal for time-crunched riders and build phases. Threshold builds race-specific fitness for sustained efforts. Most coaches use both across the training year.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Intensity", optionA: "88-94% FTP", optionB: "95-105% FTP" },
      { feature: "Typical session", optionA: "3x15 or 2x20 min", optionB: "2x20 or 3x12 min" },
      { feature: "Recovery cost", optionA: "Moderate", optionB: "High" },
      { feature: "FTP stimulus", optionA: "Strong", optionB: "Very strong" },
      { feature: "Time-crunched friendly", optionA: "Yes", optionB: "Needs more recovery days" },
      { feature: "Race specificity", optionA: "General", optionB: "High for TT and road racing" },
    ],
    bestForA: ["Time-crunched riders under 10 hours/week", "Build phases before adding full threshold", "Masters riders managing recovery", "Riders new to structured training"],
    bestForB: ["Riders targeting time trials", "Peaking phases before racing", "Riders with good recovery who can handle the load", "Riders specifically building FTP"],
    relatedArticle: "/blog/polarised-vs-sweet-spot-training",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "zwift-plan-vs-coach",
    title: "Zwift Training Plan vs Human Coach",
    seoTitle: "Zwift Training Plan vs Human Cycling Coach",
    seoDescription: "Zwift's built-in training plans vs hiring a human cycling coach. Cost, personalisation, accountability, and results compared honestly.",
    optionA: "Zwift Training Plan",
    optionB: "Human Coach",
    verdict: "Zwift plans are excellent value for beginners and self-motivated riders. A human coach wins when you've plateaued, need accountability, or have complex life constraints. The gap narrows for disciplined riders but widens for everyone else.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Cost", optionA: "$15/month (platform)", optionB: "$150-300/month" },
      { feature: "Personalisation", optionA: "Plan selection only", optionB: "Fully individualised weekly" },
      { feature: "Accountability", optionA: "Gamification + badges", optionB: "Weekly calls + plan reviews" },
      { feature: "Nutrition guidance", optionA: "None", optionB: "Included" },
      { feature: "Adjusts to life", optionA: "No", optionB: "Yes, weekly" },
      { feature: "Social motivation", optionA: "Strong (group rides)", optionB: "Community + 1:1" },
    ],
    bestForA: ["Beginners in first 1-2 years", "Budget-conscious riders", "Riders who thrive on gamification", "Riders who follow plans independently"],
    bestForB: ["Plateaued riders (2+ years structured)", "Time-crunched professionals", "Riders with specific event goals", "Anyone who needs accountability"],
    relatedArticle: "/blog/zwift-vs-cycling-coach",
  },
  {
    slug: "road-vs-gravel-fitness",
    title: "Road Cycling vs Gravel for Fitness",
    seoTitle: "Road Cycling vs Gravel — Which Builds More Fitness?",
    seoDescription: "Road cycling vs gravel for building fitness. Power output, muscle engagement, injury risk, and training stimulus compared for amateur cyclists.",
    optionA: "Road Cycling",
    optionB: "Gravel Riding",
    verdict: "Road riding builds higher sustained power and aerobic capacity. Gravel builds broader fitness — more core engagement, bike handling, and functional strength. Both build fitness; road is more training-efficient, gravel is more fun for many riders.",
    verdictWinner: "depends",
    pillar: "community",
    features: [
      { feature: "Average power output", optionA: "Higher (less coasting)", optionB: "Lower (variable terrain)" },
      { feature: "Muscle engagement", optionA: "Primarily legs", optionB: "Legs + core + upper body" },
      { feature: "Bike handling skills", optionA: "Moderate", optionB: "Extensive" },
      { feature: "Injury risk", optionA: "Traffic-related", optionB: "Crash risk on technical terrain" },
      { feature: "Training specificity", optionA: "High for road events", optionB: "High for gravel/MTB events" },
      { feature: "Mental freshness", optionA: "Can become repetitive", optionB: "Variety reduces burnout" },
    ],
    bestForA: ["Riders training for road races or TTs", "Riders focused on FTP development", "Riders near structured training routes", "Competitive road cyclists"],
    bestForB: ["Riders seeking variety and adventure", "Riders training for gravel events", "Riders prone to burnout on the road", "Riders who want broader athletic fitness"],
    relatedArticle: "/blog/gravel-cycling-beginners-guide",
  },
  {
    slug: "self-coached-vs-coached",
    title: "Self-Coached vs Coached Cyclist",
    seoTitle: "Self-Coached vs Coached — When to Make the Switch",
    seoDescription: "Self-coaching vs hiring a cycling coach. Cost, results, time investment, and the honest signals that you've outgrown DIY training.",
    optionA: "Self-Coached",
    optionB: "Coached",
    verdict: "Self-coaching works well for the first 2-3 years of structured training, especially with good apps and free resources. Coaching becomes worth it when gains stall, life gets complex, or you need accountability. The inflection point is usually around 3.0-3.5 W/kg.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Cost", optionA: "Free to $20/month (apps)", optionB: "$150-300/month" },
      { feature: "Learning value", optionA: "High (learn by doing)", optionB: "High (learn from expert)" },
      { feature: "Time investment", optionA: "Planning + research time", optionB: "Plan delivered, you execute" },
      { feature: "Adaptability", optionA: "Slow (you diagnose yourself)", optionB: "Fast (weekly adjustment)" },
      { feature: "Accountability", optionA: "Self-discipline only", optionB: "External accountability" },
      { feature: "Ceiling", optionA: "Hits a plateau (usually 3-3.5 W/kg)", optionB: "Breaks through plateaus" },
    ],
    bestForA: ["Beginners (first 2-3 years)", "Self-motivated learners", "Budget-constrained riders", "Riders who enjoy the process of planning"],
    bestForB: ["Plateaued riders at 3+ W/kg", "Time-crunched professionals", "Riders with event deadlines", "Anyone stuck for 6+ months"],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
    relatedTool: "/assessment",
  },
  {
    slug: "weight-loss-vs-ftp-gain",
    title: "Losing Weight vs Gaining FTP",
    seoTitle: "Lose Weight or Gain FTP — Which Improves W/kg Faster?",
    seoDescription: "Should you focus on losing weight or gaining FTP to improve W/kg? The honest answer depends on your body composition and training history.",
    optionA: "Lose Weight",
    optionB: "Gain FTP",
    verdict: "If your body fat is above 15% (men) or 22% (women), weight loss is the faster path to better W/kg. If you're already lean, FTP gains are the only safe lever. Most riders benefit from doing both simultaneously using the fuel-for-the-work-required approach.",
    verdictWinner: "depends",
    pillar: "nutrition",
    features: [
      { feature: "Speed of improvement", optionA: "Fast (weeks)", optionB: "Slow (months)" },
      { feature: "Sustainability", optionA: "Risk of muscle loss", optionB: "Permanent adaptation" },
      { feature: "Performance risk", optionA: "Can lose power if done wrong", optionB: "No downside risk" },
      { feature: "Effort type", optionA: "Nutrition discipline", optionB: "Training discipline" },
      { feature: "Best when body fat >15%", optionA: "Highest ROI", optionB: "Also helps" },
      { feature: "Best when already lean", optionA: "Dangerous (RED-S risk)", optionB: "Only safe option" },
    ],
    bestForA: ["Riders with body fat above 15%", "Riders who haven't changed nutrition habits", "Post-winter body composition reset", "Riders using fuel-for-the-work-required framework"],
    bestForB: ["Lean riders (under 12% body fat)", "Riders with strong nutrition already", "Early-season base building", "Riders adding structured training for the first time"],
    relatedArticle: "/blog/cycling-power-to-weight-ratio-guide",
    relatedTool: "/tools/wkg",
  },
  {
    slug: "training-plan-vs-coach",
    title: "Cycling Training Plan vs Coach",
    seoTitle: "Cycling Training Plan vs Coach — Which Works Better?",
    seoDescription: "A pre-built training plan versus a personal coach. Which delivers better results for which rider? Cost, personalisation, accountability, and outcomes compared.",
    optionA: "Pre-Built Training Plan",
    optionB: "Personal Coach",
    verdict: "A pre-built plan works for self-motivated riders with standard life constraints and modest goals. A coach wins the moment anything goes non-standard — plateaus, illness, life stress, event-specific demands, or sustained plateau. For anyone serious about significant improvement, coaching outperforms by a wide margin.",
    verdictWinner: "B",
    pillar: "coaching",
    features: [
      { feature: "Upfront cost", optionA: "$50-200 one-time", optionB: "$150-300/month" },
      { feature: "Personalisation", optionA: "One-size for similar riders", optionB: "Fully bespoke, weekly-adjusted" },
      { feature: "Adapts to life", optionA: "No — you adapt to it", optionB: "Yes — continuously" },
      { feature: "Recovery adjustment", optionA: "Fixed rest days", optionB: "Adjusted to your HRV/fatigue" },
      { feature: "Illness/injury handling", optionA: "You figure it out", optionB: "Coach reworks the plan" },
      { feature: "Event-specific preparation", optionA: "Generic if your event isn't included", optionB: "Built for your specific event" },
      { feature: "Accountability", optionA: "Self-directed", optionB: "Weekly check-ins and reviews" },
      { feature: "Best for breakthrough performance", optionA: "Limited ceiling", optionB: "Much higher ceiling" },
    ],
    bestForA: [
      "Intermediate riders with clear event targets included in the plan library",
      "Self-motivated riders who've never followed any structure before",
      "Budget-constrained riders (under $50/month to spend)",
      "Riders testing whether structured training suits them before committing to coaching",
    ],
    bestForB: [
      "Riders who've already followed plans and want more than they delivered",
      "Plateaued riders who need someone to see what they can't see",
      "Time-crunched riders who need every hour to count",
      "Riders with complex life context (shift work, chronic illness, family demands)",
      "Event-specific preparation where the event isn't in any plan library",
    ],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
    relatedTool: "/assessment",
  },
  {
    slug: "garmin-vs-wahoo",
    title: "Garmin vs Wahoo Cycling Computers",
    seoTitle: "Garmin vs Wahoo: Which Cycling Computer Is Better?",
    seoDescription: "Garmin Edge vs Wahoo Element. Navigation, data, training features, app integration — the real differences between the two leading cycling computer ecosystems.",
    optionA: "Garmin Edge",
    optionB: "Wahoo Elemnt",
    verdict: "Garmin wins on feature depth, navigation breadth, and ecosystem (watches, lights, radar). Wahoo wins on simplicity, battery life, and app-based setup. Most riders thrive on either — pick Garmin if you want the widest feature set, Wahoo if you want the lowest friction.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Feature depth", optionA: "Extensive (perhaps overwhelming)", optionB: "Focused (perhaps limiting)" },
      { feature: "Navigation maps", optionA: "Turn-by-turn, on-device search, off-route rerouting", optionB: "Turn-by-turn, but requires pre-planned routes" },
      { feature: "Battery life", optionA: "12-24 hours depending on model", optionB: "17-30 hours depending on model" },
      { feature: "Setup friction", optionA: "Garmin Express / Connect app required", optionB: "Phone-only setup in minutes" },
      { feature: "Training features", optionA: "ClimbPro, Daily Suggested Workouts, Firstbeat metrics", optionB: "Structured workouts, planned races, simpler interface" },
      { feature: "Ecosystem breadth", optionA: "Watches, radar, lights, inReach — fully integrated", optionB: "Trainers (KICKR) + head units only" },
      { feature: "Third-party app integration", optionA: "Connect IQ store (hundreds of apps)", optionB: "No app store, tighter native integration with partners" },
      { feature: "Used with a power meter", optionA: "Full TrainingPeaks / Strava / Intervals.icu sync", optionB: "Full TrainingPeaks / Strava / Intervals.icu sync" },
    ],
    bestForA: [
      "Riders who want maximum features and depth (navigation, training, analysis)",
      "Riders already in the Garmin watch/radar/light ecosystem",
      "Explorers who need robust off-route navigation",
      "Data nerds who want ClimbPro, recovery advisor, and Firstbeat metrics",
    ],
    bestForB: [
      "Riders who want a head unit that just works without tinkering",
      "Budget-conscious riders (Wahoo is often cheaper at each tier)",
      "Riders who prefer phone-based setup over desktop apps",
      "Strava/Komoot users who primarily plan routes on the phone",
    ],
    relatedArticle: "/blog/wahoo-vs-garmin-cycling-computers",
  },
  {
    slug: "rouvy-vs-zwift-platform",
    title: "Rouvy vs Zwift — Indoor Cycling Platforms",
    seoTitle: "Rouvy vs Zwift: Which Indoor Cycling Platform Wins?",
    seoDescription: "Real-world courses versus virtual islands. Rouvy and Zwift compared on training, racing, routes, social features, and value.",
    optionA: "Rouvy",
    optionB: "Zwift",
    verdict: "Pick Rouvy if you want to simulate real events (Tour stages, Ironman courses, Alpine climbs) and prefer AR video over cartoon worlds. Pick Zwift if you want social riding, races, group rides, and the best-in-class structured workout library. Most cyclists gravitate to Zwift for community, Rouvy for course-specific preparation.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Visual style", optionA: "Augmented-reality video of real roads", optionB: "Cartoon-stylised virtual worlds (Watopia, France, NYC)" },
      { feature: "Route library", optionA: "1000+ real-world courses including Tour stages, Ironman courses", optionB: "100+ virtual routes across 10+ worlds" },
      { feature: "Structured workouts", optionA: "Basic library, less intuitive to author", optionB: "Extensive workout library, TrainerRoad-style authoring" },
      { feature: "Racing", optionA: "Race events exist but smaller community", optionB: "Huge racing scene — hundreds of races daily across categories" },
      { feature: "Group rides", optionA: "Limited", optionB: "Massive — thousands of daily group rides" },
      { feature: "Event-specific training", optionA: "Best in class — ride the real course you're targeting", optionB: "Generic — Watopia routes don't match real events" },
      { feature: "Monthly cost", optionA: "$12-15", optionB: "$20" },
      { feature: "Device compatibility", optionA: "iOS, Android, Windows, Mac, Apple TV", optionB: "iOS, Android, Windows, Mac, Apple TV" },
    ],
    bestForA: [
      "Riders targeting a specific real event (Étape du Tour, Ironman, Unbound)",
      "Riders who prefer real-world visuals over virtual worlds",
      "Cyclists training for climbs and want to see the actual gradient profile",
      "Budget-focused riders willing to trade community for lower cost",
    ],
    bestForB: [
      "Riders who need social motivation and group rides to stay consistent",
      "Racers who want to compete multiple times a week",
      "Structured-training users who want a deep workout library built in",
      "Cyclists who prioritise community and consistency over course specificity",
    ],
    relatedArticle: "/blog/rouvy-vs-zwift",
  },
];

export function getComparisonBySlug(slug: string): ComparisonPage | null {
  return COMPARISONS.find((c) => c.slug === slug) ?? null;
}

export function getAllComparisonSlugs(): string[] {
  return COMPARISONS.map((c) => c.slug);
}
