import { type ContentPillar } from "@/types";

export interface ComparisonFeature {
  feature: string;
  optionA: string;
  optionB: string;
}

export interface ComparisonFAQ {
  q: string;
  a: string;
}

export interface ComparisonPage {
  slug: string;
  title: string;
  seoTitle: string;
  seoDescription: string;
  optionA: string;
  optionB: string;
  verdict: string;
  verdictWinner: "A" | "B" | "depends";
  pillar: ContentPillar;
  features: ComparisonFeature[];
  bestForA: string[];
  bestForB: string[];
  relatedArticle?: string;
  relatedTool?: string;
  /**
   * Optional opening paragraph(s) shown before the comparison body — used
   * when context the reader needs (e.g. a competitor shutting down)
   * deserves more space than the verdict block can carry.
   */
  intro?: string[];
  /**
   * Long-form prose paragraphs rendered between the decision blocks and
   * the FAQ. Each string is one paragraph; basic Markdown-style links
   * in the form `[text](href)` are converted to anchors at render time.
   */
  body?: string[];
  /**
   * Disclosure paragraph rendered in a callout — partnership notes,
   * conflicts of interest, or anything the reader should know about
   * the writer's relationship to the products being compared.
   */
  disclosure?: string;
  /** Optional FAQ block. When present, also added to FAQPage schema. */
  faqs?: ComparisonFAQ[];
}

export const COMPARISONS: ComparisonPage[] = [
  {
    slug: "coach-vs-app",
    title: "Cycling Coach vs Training App",
    seoTitle: "Cycling Coach vs Training App — Which Do You Need?",
    seoDescription: "When does a cycling coach beat a training app? Side-by-side comparison of cost, personalisation, accountability, and results.",
    optionA: "Cycling Coach",
    optionB: "Training App",
    verdict: "A coach wins when you've plateaued, need accountability, or have complex life constraints. An app wins when you're a beginner, budget-conscious, or still making easy gains.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Personalisation", optionA: "Fully personalised weekly", optionB: "Algorithm-adjusted" },
      { feature: "Accountability", optionA: "Weekly calls + plan reviews", optionB: "Self-directed" },
      { feature: "Cost", optionA: "$150-300/month", optionB: "$15-30/month" },
      { feature: "Nutrition guidance", optionA: "Included", optionB: "Not included" },
      { feature: "Strength programming", optionA: "Included", optionB: "Rarely included" },
      { feature: "Life context adjustment", optionA: "Real-time, human", optionB: "Limited or none" },
      { feature: "Best for beginners", optionA: "Overkill", optionB: "Ideal" },
      { feature: "Best for plateaued riders", optionA: "Ideal", optionB: "Insufficient" },
    ],
    bestForA: [
      "Riders who've plateaued after 2+ years of structured training",
      "Time-crunched professionals who need every hour to count",
      "Riders with specific event goals and a date on the calendar",
      "Anyone who needs accountability to stay consistent",
    ],
    bestForB: [
      "Beginners in their first 1-2 years of structured training",
      "Budget-conscious riders making easy gains",
      "Self-motivated riders who follow plans independently",
      "Riders who prefer a virtual-world experience (Zwift)",
    ],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
    relatedTool: "/assessment",
  },
  {
    slug: "polarised-vs-pyramidal",
    title: "Polarised vs Pyramidal Training",
    seoTitle: "Polarised vs Pyramidal Training for Cyclists",
    seoDescription: "Polarised training (80/20) vs pyramidal distribution — which intensity model produces better results for amateur cyclists?",
    optionA: "Polarised (80/20)",
    optionB: "Pyramidal",
    verdict: "Polarised has stronger research support for most amateurs. Pyramidal works for riders with very high volume. Both beat the grey-zone middle that most cyclists default to.",
    verdictWinner: "A",
    pillar: "coaching",
    features: [
      { feature: "Easy training %", optionA: "~80%", optionB: "~75%" },
      { feature: "Moderate (Zone 3) %", optionA: "~0-5%", optionB: "~15-20%" },
      { feature: "High intensity %", optionA: "~15-20%", optionB: "~5-10%" },
      { feature: "Research support", optionA: "Strong (Seiler)", optionB: "Moderate" },
      { feature: "Best for time-crunched", optionA: "Yes", optionB: "Needs more volume" },
      { feature: "Recovery demand", optionA: "Manageable", optionB: "Higher due to Zone 3" },
    ],
    bestForA: [
      "Time-crunched riders (6-10 hours/week)",
      "Masters cyclists who need to manage recovery",
      "Riders who plateau doing lots of tempo work",
    ],
    bestForB: [
      "High-volume riders (15+ hours/week)",
      "Riders who naturally thrive on tempo-paced group rides",
      "Stage-race athletes building sustained aerobic capacity",
    ],
    relatedArticle: "/blog/polarised-vs-sweet-spot-training",
  },
  {
    slug: "strength-vs-more-miles",
    title: "Strength Training vs More Miles",
    seoTitle: "Strength Training vs More Riding for Cyclists",
    seoDescription: "Should cyclists lift weights or ride more? Side-by-side comparison of strength training vs extra volume for amateur and masters riders.",
    optionA: "Strength Training",
    optionB: "More Riding Volume",
    verdict: "For riders over 35 or those training under 10 hours/week, strength training produces better returns per hour than adding more riding volume. For high-volume riders under 35 with no injury history, more riding still wins.",
    verdictWinner: "depends",
    pillar: "strength",
    features: [
      { feature: "Time investment", optionA: "2-3 sessions/week (45-60min)", optionB: "3-5 extra hours/week riding" },
      { feature: "Injury prevention", optionA: "Strong evidence", optionB: "No direct benefit" },
      { feature: "FTP improvement", optionA: "8-15% (Rønnestad)", optionB: "5-10% with more volume" },
      { feature: "Masters benefit", optionA: "Critical after 40", optionB: "Diminishing returns" },
      { feature: "Cycling economy", optionA: "4-5% improvement", optionB: "Marginal" },
      { feature: "Recovery cost", optionA: "Manageable if programmed", optionB: "Fatigue accumulation risk" },
    ],
    bestForA: ["Masters riders over 40", "Time-crunched riders under 10 hours/week", "Riders with recurring injuries", "Anyone who has never done structured S&C"],
    bestForB: ["Young riders with no injury history", "Riders with 15+ hours available", "Riders already lifting consistently", "Ultra-endurance athletes building volume"],
    relatedArticle: "/blog/new-study-confirms-heavy-strength-training-beats-more-miles-after-40",
    relatedTool: "/strength-training",
  },
  {
    slug: "indoor-vs-outdoor-training",
    title: "Indoor vs Outdoor Training",
    seoTitle: "Indoor vs Outdoor Cycling Training — Which Is Better?",
    seoDescription: "Indoor training vs outdoor riding for cyclists. Time efficiency, workout quality, skill development, and how to balance both for maximum gains.",
    optionA: "Indoor Training",
    optionB: "Outdoor Riding",
    verdict: "Indoor training wins on time efficiency and workout precision. Outdoor riding wins on skill development, mental health, and race-specific fitness. The best cyclists do both — structured work inside, volume and skills outside.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Time efficiency", optionA: "60min indoor = 90min outdoor", optionB: "Includes travel, coasting, stops" },
      { feature: "Workout precision", optionA: "Exact power targets via ERG", optionB: "Terrain-dependent" },
      { feature: "Skill development", optionA: "None", optionB: "Cornering, descending, bunch riding" },
      { feature: "Mental health", optionA: "Can feel isolating", optionB: "Daylight, fresh air, social" },
      { feature: "Race specificity", optionA: "Limited", optionB: "High" },
      { feature: "Weather independence", optionA: "Complete", optionB: "Season-dependent" },
    ],
    bestForA: ["Winter months", "Midweek structured sessions", "Time-crunched riders", "Riders with young children or shift work"],
    bestForB: ["Weekends and longer rides", "Group ride and race skills", "Mental freshness", "Race-specific preparation"],
    relatedArticle: "/blog/cycling-indoor-training-tips",
  },
  {
    slug: "heart-rate-vs-power",
    title: "Heart Rate vs Power Meter Training",
    seoTitle: "Heart Rate vs Power Meter for Cycling Training",
    seoDescription: "Should you train by heart rate or power? Comparison of accuracy, cost, and practical use for amateur cyclists.",
    optionA: "Power Meter",
    optionB: "Heart Rate Monitor",
    verdict: "Power is the gold standard — it measures output directly while heart rate measures response. But heart rate still has value for pacing easy rides, monitoring fatigue, and riders on a budget.",
    verdictWinner: "A",
    pillar: "coaching",
    features: [
      { feature: "Measures", optionA: "Work output (watts)", optionB: "Physiological response (bpm)" },
      { feature: "Instant feedback", optionA: "Yes", optionB: "Lags 30-90 seconds" },
      { feature: "Affected by fatigue", optionA: "No", optionB: "Yes (cardiac drift)" },
      { feature: "Affected by heat", optionA: "No", optionB: "Yes" },
      { feature: "Cost", optionA: "$200-600", optionB: "$30-80" },
      { feature: "Pacing value", optionA: "Excellent", optionB: "Good for easy rides" },
      { feature: "Training zones", optionA: "7-zone Coggan model", optionB: "5-zone approximate" },
    ],
    bestForA: ["Serious training with interval targets", "Event pacing", "FTP tracking and progression", "Anyone who can afford it"],
    bestForB: ["Budget-conscious riders", "Monitoring Zone 2 easy days", "Detecting overtraining via resting HR", "Beginners learning intensity"],
    relatedArticle: "/blog/cycling-power-meter-guide",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "trainerroad-vs-trainingpeaks",
    title: "TrainerRoad vs TrainingPeaks",
    seoTitle: "TrainerRoad vs TrainingPeaks for Cyclists",
    seoDescription: "TrainerRoad's adaptive plans vs TrainingPeaks' coach-driven platform. Which training software is right for your cycling goals?",
    optionA: "TrainerRoad",
    optionB: "TrainingPeaks",
    verdict: "TrainerRoad is a self-coaching engine — pick a plan, follow the workouts, let the algorithm adapt. TrainingPeaks is a platform your coach builds your plan on. If you have a coach, TrainingPeaks. If you're self-coached, TrainerRoad.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Primary use", optionA: "Self-coached adaptive training", optionB: "Coach-athlete platform" },
      { feature: "Plan creation", optionA: "Algorithm-generated", optionB: "Coach-built or purchased" },
      { feature: "Adaptive training", optionA: "Yes (AI-driven)", optionB: "Manual (coach adjusts)" },
      { feature: "Indoor workouts", optionA: "Built-in with ERG mode", optionB: "Syncs to Wahoo/Garmin" },
      { feature: "Analytics depth", optionA: "Good", optionB: "Excellent (PMC, CTL, ATL)" },
      { feature: "Cost", optionA: "~$20/month", optionB: "~$10-20/month + coach fee" },
    ],
    bestForA: ["Self-coached riders who want structure", "Indoor training focus", "Riders who want AI-adjusted plans", "Budget-conscious athletes"],
    bestForB: ["Riders working with a human coach", "Advanced analytics and periodisation", "Multi-sport athletes (triathlon)", "Riders who want full calendar control"],
    relatedArticle: "/blog/trainerroad-vs-online-cycling-coach",
  },
  {
    slug: "online-coach-vs-local-club",
    title: "Online Cycling Coach vs Local Club Training",
    seoTitle: "Online Coach vs Local Club for Cycling Training",
    seoDescription: "Should you hire an online cycling coach or train with your local club? Comparison of personalisation, cost, social benefits, and results.",
    optionA: "Online Coach",
    optionB: "Local Club Training",
    verdict: "An online coach delivers personalised, accountable, structured training. Club training delivers social riding, group dynamics, and race skills. The best approach: use a coach for structure and the club for fun and skills.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Personalisation", optionA: "Fully individualised", optionB: "One-size-fits-all group rides" },
      { feature: "Social element", optionA: "Community platform", optionB: "Strong (group rides, racing)" },
      { feature: "Cost", optionA: "$150-300/month", optionB: "$5-30/month membership" },
      { feature: "Skill development", optionA: "Limited (remote)", optionB: "Bunch riding, drafting, tactics" },
      { feature: "Accountability", optionA: "Weekly calls + reviews", optionB: "Peer motivation" },
      { feature: "Flexibility", optionA: "Train when you can", optionB: "Fixed group ride schedule" },
    ],
    bestForA: ["Riders who've plateaued on club training alone", "Time-crunched professionals", "Riders targeting specific events", "Riders not near a strong club"],
    bestForB: ["Social riders who thrive in groups", "Beginners learning to ride in a bunch", "Budget-conscious riders", "Riders who need race-simulation intensity"],
    relatedArticle: "/blog/cycling-coach-near-me-why-location-doesnt-matter-2026",
  },
  {
    slug: "ftp-ramp-test-vs-20-minute",
    title: "FTP Ramp Test vs 20-Minute Test",
    seoTitle: "FTP Ramp Test vs 20-Minute Test — Which Is More Accurate?",
    seoDescription: "Ramp test or 20-minute test for FTP? Accuracy, pacing difficulty, and which test suits your riding style and training goals.",
    optionA: "Ramp Test",
    optionB: "20-Minute Test",
    verdict: "The 20-minute test is more accurate for most riders but harder to pace. The ramp test is easier to execute and more repeatable but can overestimate FTP for riders with strong anaerobic capacity.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Accuracy", optionA: "Good (±3-5%)", optionB: "Better (±2-3%)" },
      { feature: "Pacing difficulty", optionA: "None (progressive)", optionB: "High (must hold steady)" },
      { feature: "Duration", optionA: "~20 min total", optionB: "~45 min with warm-up" },
      { feature: "Repeatability", optionA: "High", optionB: "Moderate (pacing varies)" },
      { feature: "Anaerobic bias", optionA: "Can overestimate", optionB: "Less biased" },
      { feature: "Mental difficulty", optionA: "Moderate", optionB: "Very high" },
    ],
    bestForA: ["New to FTP testing", "Riders who struggle with pacing", "Frequent retesting (every 4-6 weeks)", "Indoor training platforms"],
    bestForB: ["Experienced riders who can pace well", "More accurate zone calculation", "Riders training for TTs or steady-state events", "When absolute accuracy matters"],
    relatedArticle: "/blog/how-to-improve-ftp-cycling",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "sweet-spot-vs-threshold",
    title: "Sweet Spot vs Threshold Training",
    seoTitle: "Sweet Spot vs Threshold Training for Cyclists",
    seoDescription: "Sweet spot (88-94% FTP) vs threshold (95-105% FTP) training. Which builds more fitness, which costs more recovery, and when to use each.",
    optionA: "Sweet Spot (88-94% FTP)",
    optionB: "Threshold (95-105% FTP)",
    verdict: "Sweet spot delivers more training stimulus per unit of fatigue — ideal for time-crunched riders and build phases. Threshold builds race-specific fitness for sustained efforts. Most coaches use both across the training year.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Intensity", optionA: "88-94% FTP", optionB: "95-105% FTP" },
      { feature: "Typical session", optionA: "3x15 or 2x20 min", optionB: "2x20 or 3x12 min" },
      { feature: "Recovery cost", optionA: "Moderate", optionB: "High" },
      { feature: "FTP stimulus", optionA: "Strong", optionB: "Very strong" },
      { feature: "Time-crunched friendly", optionA: "Yes", optionB: "Needs more recovery days" },
      { feature: "Race specificity", optionA: "General", optionB: "High for TT and road racing" },
    ],
    bestForA: ["Time-crunched riders under 10 hours/week", "Build phases before adding full threshold", "Masters riders managing recovery", "Riders new to structured training"],
    bestForB: ["Riders targeting time trials", "Peaking phases before racing", "Riders with good recovery who can handle the load", "Riders specifically building FTP"],
    relatedArticle: "/blog/polarised-vs-sweet-spot-training",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "zwift-plan-vs-coach",
    title: "Zwift Training Plan vs Human Coach",
    seoTitle: "Zwift Training Plan vs Human Cycling Coach",
    seoDescription: "Zwift's built-in training plans vs hiring a human cycling coach. Cost, personalisation, accountability, and results compared honestly.",
    optionA: "Zwift Training Plan",
    optionB: "Human Coach",
    verdict: "Zwift plans are excellent value for beginners and self-motivated riders. A human coach wins when you've plateaued, need accountability, or have complex life constraints. The gap narrows for disciplined riders but widens for everyone else.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Cost", optionA: "$15/month (platform)", optionB: "$150-300/month" },
      { feature: "Personalisation", optionA: "Plan selection only", optionB: "Fully individualised weekly" },
      { feature: "Accountability", optionA: "Gamification + badges", optionB: "Weekly calls + plan reviews" },
      { feature: "Nutrition guidance", optionA: "None", optionB: "Included" },
      { feature: "Adjusts to life", optionA: "No", optionB: "Yes, weekly" },
      { feature: "Social motivation", optionA: "Strong (group rides)", optionB: "Community + 1:1" },
    ],
    bestForA: ["Beginners in first 1-2 years", "Budget-conscious riders", "Riders who thrive on gamification", "Riders who follow plans independently"],
    bestForB: ["Plateaued riders (2+ years structured)", "Time-crunched professionals", "Riders with specific event goals", "Anyone who needs accountability"],
    relatedArticle: "/blog/zwift-vs-cycling-coach",
  },
  {
    slug: "road-vs-gravel-fitness",
    title: "Road Cycling vs Gravel for Fitness",
    seoTitle: "Road Cycling vs Gravel — Which Builds More Fitness?",
    seoDescription: "Road cycling vs gravel for building fitness. Power output, muscle engagement, injury risk, and training stimulus compared for amateur cyclists.",
    optionA: "Road Cycling",
    optionB: "Gravel Riding",
    verdict: "Road riding builds higher sustained power and aerobic capacity. Gravel builds broader fitness — more core engagement, bike handling, and functional strength. Both build fitness; road is more training-efficient, gravel is more fun for many riders.",
    verdictWinner: "depends",
    pillar: "community",
    features: [
      { feature: "Average power output", optionA: "Higher (less coasting)", optionB: "Lower (variable terrain)" },
      { feature: "Muscle engagement", optionA: "Primarily legs", optionB: "Legs + core + upper body" },
      { feature: "Bike handling skills", optionA: "Moderate", optionB: "Extensive" },
      { feature: "Injury risk", optionA: "Traffic-related", optionB: "Crash risk on technical terrain" },
      { feature: "Training specificity", optionA: "High for road events", optionB: "High for gravel/MTB events" },
      { feature: "Mental freshness", optionA: "Can become repetitive", optionB: "Variety reduces burnout" },
    ],
    bestForA: ["Riders training for road races or TTs", "Riders focused on FTP development", "Riders near structured training routes", "Competitive road cyclists"],
    bestForB: ["Riders seeking variety and adventure", "Riders training for gravel events", "Riders prone to burnout on the road", "Riders who want broader athletic fitness"],
    relatedArticle: "/blog/gravel-cycling-beginners-guide",
  },
  {
    slug: "self-coached-vs-coached",
    title: "Self-Coached vs Coached Cyclist",
    seoTitle: "Self-Coached vs Coached — When to Make the Switch",
    seoDescription: "Self-coaching vs hiring a cycling coach. Cost, results, time investment, and the honest signals that you've outgrown DIY training.",
    optionA: "Self-Coached",
    optionB: "Coached",
    verdict: "Self-coaching works well for the first 2-3 years of structured training, especially with good apps and free resources. Coaching becomes worth it when gains stall, life gets complex, or you need accountability. The inflection point is usually around 3.0-3.5 W/kg.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Cost", optionA: "Free to $20/month (apps)", optionB: "$150-300/month" },
      { feature: "Learning value", optionA: "High (learn by doing)", optionB: "High (learn from expert)" },
      { feature: "Time investment", optionA: "Planning + research time", optionB: "Plan delivered, you execute" },
      { feature: "Adaptability", optionA: "Slow (you diagnose yourself)", optionB: "Fast (weekly adjustment)" },
      { feature: "Accountability", optionA: "Self-discipline only", optionB: "External accountability" },
      { feature: "Ceiling", optionA: "Hits a plateau (usually 3-3.5 W/kg)", optionB: "Breaks through plateaus" },
    ],
    bestForA: ["Beginners (first 2-3 years)", "Self-motivated learners", "Budget-constrained riders", "Riders who enjoy the process of planning"],
    bestForB: ["Plateaued riders at 3+ W/kg", "Time-crunched professionals", "Riders with event deadlines", "Anyone stuck for 6+ months"],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
    relatedTool: "/assessment",
  },
  {
    slug: "weight-loss-vs-ftp-gain",
    title: "Losing Weight vs Gaining FTP",
    seoTitle: "Lose Weight or Gain FTP — Which Improves W/kg Faster?",
    seoDescription: "Should you focus on losing weight or gaining FTP to improve W/kg? The honest answer depends on your body composition and training history.",
    optionA: "Lose Weight",
    optionB: "Gain FTP",
    verdict: "If your body fat is above 15% (men) or 22% (women), weight loss is the faster path to better W/kg. If you're already lean, FTP gains are the only safe lever. Most riders benefit from doing both simultaneously using the fuel-for-the-work-required approach.",
    verdictWinner: "depends",
    pillar: "nutrition",
    features: [
      { feature: "Speed of improvement", optionA: "Fast (weeks)", optionB: "Slow (months)" },
      { feature: "Sustainability", optionA: "Risk of muscle loss", optionB: "Permanent adaptation" },
      { feature: "Performance risk", optionA: "Can lose power if done wrong", optionB: "No downside risk" },
      { feature: "Effort type", optionA: "Nutrition discipline", optionB: "Training discipline" },
      { feature: "Best when body fat >15%", optionA: "Highest ROI", optionB: "Also helps" },
      { feature: "Best when already lean", optionA: "Dangerous (RED-S risk)", optionB: "Only safe option" },
    ],
    bestForA: ["Riders with body fat above 15%", "Riders who haven't changed nutrition habits", "Post-winter body composition reset", "Riders using fuel-for-the-work-required framework"],
    bestForB: ["Lean riders (under 12% body fat)", "Riders with strong nutrition already", "Early-season base building", "Riders adding structured training for the first time"],
    relatedArticle: "/blog/cycling-power-to-weight-ratio-guide",
    relatedTool: "/tools/wkg",
  },
  {
    slug: "training-plan-vs-coach",
    title: "Cycling Training Plan vs Coach",
    seoTitle: "Cycling Training Plan vs Coach — Which Works Better?",
    seoDescription: "A pre-built training plan versus a personal coach. Which delivers better results for which rider? Cost, personalisation, accountability, and outcomes compared.",
    optionA: "Pre-Built Training Plan",
    optionB: "Personal Coach",
    verdict: "A pre-built plan works for self-motivated riders with standard life constraints and modest goals. A coach wins the moment anything goes non-standard — plateaus, illness, life stress, event-specific demands, or sustained plateau. For anyone serious about significant improvement, coaching outperforms by a wide margin.",
    verdictWinner: "B",
    pillar: "coaching",
    features: [
      { feature: "Upfront cost", optionA: "$50-200 one-time", optionB: "$150-300/month" },
      { feature: "Personalisation", optionA: "One-size for similar riders", optionB: "Fully bespoke, weekly-adjusted" },
      { feature: "Adapts to life", optionA: "No — you adapt to it", optionB: "Yes — continuously" },
      { feature: "Recovery adjustment", optionA: "Fixed rest days", optionB: "Adjusted to your HRV/fatigue" },
      { feature: "Illness/injury handling", optionA: "You figure it out", optionB: "Coach reworks the plan" },
      { feature: "Event-specific preparation", optionA: "Generic if your event isn't included", optionB: "Built for your specific event" },
      { feature: "Accountability", optionA: "Self-directed", optionB: "Weekly check-ins and reviews" },
      { feature: "Best for breakthrough performance", optionA: "Limited ceiling", optionB: "Much higher ceiling" },
    ],
    bestForA: [
      "Intermediate riders with clear event targets included in the plan library",
      "Self-motivated riders who've never followed any structure before",
      "Budget-constrained riders (under $50/month to spend)",
      "Riders testing whether structured training suits them before committing to coaching",
    ],
    bestForB: [
      "Riders who've already followed plans and want more than they delivered",
      "Plateaued riders who need someone to see what they can't see",
      "Time-crunched riders who need every hour to count",
      "Riders with complex life context (shift work, chronic illness, family demands)",
      "Event-specific preparation where the event isn't in any plan library",
    ],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
    relatedTool: "/assessment",
  },
  {
    slug: "garmin-vs-wahoo",
    title: "Garmin vs Wahoo Cycling Computers",
    seoTitle: "Garmin vs Wahoo: Which Cycling Computer Is Better?",
    seoDescription: "Garmin Edge vs Wahoo Element. Navigation, data, training features, app integration — the real differences between the two leading cycling computer ecosystems.",
    optionA: "Garmin Edge",
    optionB: "Wahoo Elemnt",
    verdict: "Garmin wins on feature depth, navigation breadth, and ecosystem (watches, lights, radar). Wahoo wins on simplicity, battery life, and app-based setup. Most riders thrive on either — pick Garmin if you want the widest feature set, Wahoo if you want the lowest friction.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Feature depth", optionA: "Extensive (perhaps overwhelming)", optionB: "Focused (perhaps limiting)" },
      { feature: "Navigation maps", optionA: "Turn-by-turn, on-device search, off-route rerouting", optionB: "Turn-by-turn, but requires pre-planned routes" },
      { feature: "Battery life", optionA: "12-24 hours depending on model", optionB: "17-30 hours depending on model" },
      { feature: "Setup friction", optionA: "Garmin Express / Connect app required", optionB: "Phone-only setup in minutes" },
      { feature: "Training features", optionA: "ClimbPro, Daily Suggested Workouts, Firstbeat metrics", optionB: "Structured workouts, planned races, simpler interface" },
      { feature: "Ecosystem breadth", optionA: "Watches, radar, lights, inReach — fully integrated", optionB: "Trainers (KICKR) + head units only" },
      { feature: "Third-party app integration", optionA: "Connect IQ store (hundreds of apps)", optionB: "No app store, tighter native integration with partners" },
      { feature: "Used with a power meter", optionA: "Full TrainingPeaks / Strava / Intervals.icu sync", optionB: "Full TrainingPeaks / Strava / Intervals.icu sync" },
    ],
    bestForA: [
      "Riders who want maximum features and depth (navigation, training, analysis)",
      "Riders already in the Garmin watch/radar/light ecosystem",
      "Explorers who need robust off-route navigation",
      "Data nerds who want ClimbPro, recovery advisor, and Firstbeat metrics",
    ],
    bestForB: [
      "Riders who want a head unit that just works without tinkering",
      "Budget-conscious riders (Wahoo is often cheaper at each tier)",
      "Riders who prefer phone-based setup over desktop apps",
      "Strava/Komoot users who primarily plan routes on the phone",
    ],
    relatedArticle: "/blog/wahoo-vs-garmin-cycling-computers",
  },
  {
    slug: "rouvy-vs-zwift-platform",
    title: "Rouvy vs Zwift — Indoor Cycling Platforms",
    seoTitle: "Rouvy vs Zwift: Which Indoor Cycling Platform Wins?",
    seoDescription: "Real-world courses versus virtual islands. Rouvy and Zwift compared on training, racing, routes, social features, and value.",
    optionA: "Rouvy",
    optionB: "Zwift",
    verdict: "Pick Rouvy if you want to simulate real events (Tour stages, Ironman courses, Alpine climbs) and prefer AR video over cartoon worlds. Pick Zwift if you want social riding, races, group rides, and the best-in-class structured workout library. Most cyclists gravitate to Zwift for community, Rouvy for course-specific preparation.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Visual style", optionA: "Augmented-reality video of real roads", optionB: "Cartoon-stylised virtual worlds (Watopia, France, NYC)" },
      { feature: "Route library", optionA: "1000+ real-world courses including Tour stages, Ironman courses", optionB: "100+ virtual routes across 10+ worlds" },
      { feature: "Structured workouts", optionA: "Basic library, less intuitive to author", optionB: "Extensive workout library, TrainerRoad-style authoring" },
      { feature: "Racing", optionA: "Race events exist but smaller community", optionB: "Huge racing scene — hundreds of races daily across categories" },
      { feature: "Group rides", optionA: "Limited", optionB: "Massive — thousands of daily group rides" },
      { feature: "Event-specific training", optionA: "Best in class — ride the real course you're targeting", optionB: "Generic — Watopia routes don't match real events" },
      { feature: "Monthly cost", optionA: "$12-15", optionB: "$20" },
      { feature: "Device compatibility", optionA: "iOS, Android, Windows, Mac, Apple TV", optionB: "iOS, Android, Windows, Mac, Apple TV" },
    ],
    bestForA: [
      "Riders targeting a specific real event (Étape du Tour, Ironman, Unbound)",
      "Riders who prefer real-world visuals over virtual worlds",
      "Cyclists training for climbs and want to see the actual gradient profile",
      "Budget-focused riders willing to trade community for lower cost",
    ],
    bestForB: [
      "Riders who need social motivation and group rides to stay consistent",
      "Racers who want to compete multiple times a week",
      "Structured-training users who want a deep workout library built in",
      "Cyclists who prioritise community and consistency over course specificity",
    ],
    relatedArticle: "/blog/rouvy-vs-zwift",
  },
  {
    slug: "power-meter-vs-smart-trainer",
    title: "Power Meter vs Smart Trainer — Which Should You Buy First?",
    seoTitle: "Power Meter vs Smart Trainer: Which Should Cyclists Buy First?",
    seoDescription: "Limited budget for one training investment? The case for each, with clear recommendations by rider type, climate, and training environment.",
    optionA: "Power Meter",
    optionB: "Smart Trainer",
    verdict: "Buy the power meter first if you ride outdoors more than 50% of the year — data follows you everywhere. Buy the smart trainer first if winter is long, outdoor riding is patchy, and you need structured sessions on demand. Many serious cyclists end up with both within 2-3 seasons.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Works outdoors", optionA: "Yes — every ride, any bike it's fitted to", optionB: "No — indoor only" },
      { feature: "Works indoors", optionA: "Yes — on rollers or a dumb trainer", optionB: "Yes — primary use case" },
      { feature: "Cost (entry tier)", optionA: "$350-500 single-sided", optionB: "$500-800 direct-drive smart trainer" },
      { feature: "Cost (mid-tier)", optionA: "$700-1100 dual-sided pedals or spider", optionB: "$900-1400 premium smart trainer" },
      { feature: "Setup effort", optionA: "Install once, forget it", optionB: "Calibrate, maintain, pair every session" },
      { feature: "Structured workouts", optionA: "Requires head unit and self-pacing", optionB: "Erg mode handles pacing automatically" },
      { feature: "Data accuracy", optionA: "Excellent outdoors and indoors", optionB: "Excellent when calibrated" },
      { feature: "Portability", optionA: "Travels with the bike", optionB: "Stays at home" },
      { feature: "Best for year-round outdoor training", optionA: "Clear winner", optionB: "Complementary only" },
    ],
    bestForA: [
      "Cyclists who ride outdoors for most of the year",
      "Riders with multiple bikes who want consistent data everywhere",
      "Triathletes and gravel riders whose events are outdoors",
      "Anyone who finds pacing by feel unreliable",
    ],
    bestForB: [
      "Cyclists in long winters or patchy riding climates (UK, Ireland, Scandinavia)",
      "Time-crunched riders who need structured sessions on demand",
      "Beginners who benefit from erg mode taking pacing out of the equation",
      "Riders who prioritise Zwift / TrainerRoad / Rouvy as their main training tool",
    ],
    relatedArticle: "/blog/power-meter-vs-smart-trainer",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "trainingpeaks-vs-vekta",
    title: "TrainingPeaks vs Vekta — Cycling Training Platforms Compared",
    seoTitle: "TrainingPeaks vs Vekta — Which Cycling Training Platform?",
    seoDescription: "TrainingPeaks vs Vekta — the industry-standard coaching platform every serious coach uses, compared with Vekta. Analysis depth, ecosystem, WKO5, plan marketplace and verdict.",
    optionA: "TrainingPeaks",
    optionB: "Vekta",
    verdict: "TrainingPeaks. It's the platform every serious coach in cycling uses — the gold standard for a reason. Universal device sync, the deepest analysis tools (PMC, fitness/fatigue, WKO5 integration), thousands of prebuilt plans, and over two decades of athlete data continuity. Vekta is a newer, smaller platform with some genuinely clever plan-building features, but it can't match TrainingPeaks' coach ecosystem, analysis depth, or third-party integrations. If you're working with a coach in 2026 — or planning to — TrainingPeaks is the right choice.",
    verdictWinner: "A",
    pillar: "coaching",
    features: [
      { feature: "Industry adoption (coaches)", optionA: "The default — used by the vast majority of pro and serious amateur coaches worldwide", optionB: "Newer entrant, smaller coach base, growing in pockets of UK/AU" },
      { feature: "Years on the market", optionA: "20+ years of athlete data continuity", optionB: "Younger platform, shorter track record" },
      { feature: "Plan marketplace", optionA: "Thousands of prebuilt structured plans from world-class coaches", optionB: "Smaller library, plans usually delivered direct by coach" },
      { feature: "Analysis depth", optionA: "Class-leading — PMC, performance modelling, fitness/fatigue, ATL/CTL/TSB", optionB: "Solid analytics, less granular than TrainingPeaks" },
      { feature: "WKO5 integration", optionA: "Yes — full WKO5 sync, the choice of high-performance coaches", optionB: "No native WKO5 pipeline" },
      { feature: "Device + platform sync", optionA: "Universal — Garmin, Wahoo, Zwift, TrainerRoad, Strava, MyFitnessPal, Final Surge, every major head unit", optionB: "Major brands supported, smaller ecosystem of third-party integrations" },
      { feature: "Mobile app", optionA: "Mature, polished, works offline, premium calendar features", optionB: "Functional, improving, smaller team behind it" },
      { feature: "Athlete pricing", optionA: "Free tier with workouts and basic charts; Premium $19.95/mo for full PMC and structured workout import", optionB: "Typically bundled with coaching, standalone pricing available" },
      { feature: "Coach pricing", optionA: "Tiered Coach plans scale from solo coaches to large teams", optionB: "Per-coach license, often included with platform" },
      { feature: "Plan auto-adjustment", optionA: "Coach-driven; AI-assisted suggestions in newer features", optionB: "Auto-adjusts upcoming sessions based on completed work" },
      { feature: "Best for working with a coach", optionA: "Yes — almost every coach you'd want to hire is already on it", optionB: "Only if your specific coach has chosen Vekta" },
    ],
    bestForA: [
      "Anyone working with a coach in 2026 — your coach almost certainly uses TrainingPeaks",
      "Self-coached athletes who want the biggest plan marketplace in cycling",
      "Cyclists who use multiple devices and want everything talking to one platform",
      "Riders who want WKO5 in their corner — the same software pro performance teams rely on",
      "Athletes building a long-term training history (PMC, durability, year-on-year comparisons)",
      "Teams, clubs and squads where one shared platform makes life easier for everyone",
    ],
    bestForB: [
      "Athletes whose specific coach has built their workflow on Vekta",
      "Riders inside the Roadman Not Done Yet community using the included Vekta plans",
      "Cyclists who like Vekta's auto-adjusting plan structure and don't need WKO-level analysis",
      "Coaches running smaller, plan-led programmes who prefer Vekta's interface",
    ],
    relatedArticle: "/compare/trainerroad-vs-trainingpeaks",
    relatedTool: "/tools/ftp-zones",
    intro: [
      "If you landed here looking for Today's Plan — here's the bad news: it's shut down. Today's Plan has been retired and is no longer available as a product. So if you were weighing TrainingPeaks against Today's Plan, the comparison that actually matters now is TrainingPeaks vs Vekta — the two cycling-coaching platforms most riders end up choosing between in 2026.",
      "Here's the good news: this one's a lot more clear-cut than it used to be. Let me break it down.",
    ],
    body: [
      "**TrainingPeaks is the gold standard. Genuinely.** Most of the coaches we talk to on the podcast — the ones working with World Tour riders, the ones running successful amateur coaching businesses, the ones with the published research behind them — all use TrainingPeaks. That's not marketing copy, that's just where the industry is. Two decades of platform development, the deepest analytics in the sport, and the WKO5 pipeline that high-performance teams quietly rely on.",
      "The Performance Management Chart (PMC), CTL/ATL/TSB, the fitness/fatigue model — these aren't niche features. They're the language coaches use when they sit down to plan your season. Open TrainingPeaks and a coach can read your last six months in about thirty seconds. That matters when you're paying for their time.",
      "The plan marketplace is the other unfair advantage. Thousands of structured plans built by coaches you'd happily hire — Joe Friel's plans, Tim Cusick's WKO-built blocks, Carmichael Training Systems, the pro coaches who've published books you've already read. If you're self-coaching and you want a plan written by someone who actually knows what they're doing, TrainingPeaks is where they put it.",
      "**Vekta is a clever, newer platform.** And we'll be straight with you: Roadman Cycling's paid Not Done Yet community uses Vekta to deliver training plans to members. We rate it. The plan auto-adjustment is genuinely useful — sessions ahead in the calendar shift based on what you actually completed, which is a nice touch. The interface is clean. The team behind it ships updates regularly.",
      "But Vekta is a smaller platform with a smaller coach base. The third-party integration list is shorter. There's no WKO5 pipeline. The plan marketplace is much smaller. The years-of-data continuity isn't there yet. None of that makes Vekta a bad platform — it makes it a newer one. For a community-delivered plan inside a fixed coaching system, Vekta does the job. For an athlete building a multi-year training history with the platform every serious coach in the sport already uses? TrainingPeaks, every time.",
      "**The honest answer for most cyclists:** if you're hiring a coach in 2026, ask them what platform they use, and you'll almost always get TrainingPeaks back. Sign up there. If your coach happens to use Vekta, sign up there. If you're self-coached and want the deepest tools and the biggest plan library, TrainingPeaks is the one to commit to.",
    ],
    disclosure:
      "Disclosure: TrainingPeaks is a Roadman Cycling partner — we work with them because they're the platform we genuinely recommend, not the other way around. Roadman's paid Not Done Yet community uses Vekta to deliver training plans to members, so you should know we have a working relationship with both companies. The verdict above still favours TrainingPeaks because that's the honest read of the platforms — the partnership followed the position, not the other way around.",
    faqs: [
      {
        q: "Is Today's Plan still available?",
        a: "No. Today's Plan has shut down and is no longer available as a cycling training platform. If you were comparing it against TrainingPeaks, the practical comparison now is TrainingPeaks vs Vekta — those are the two platforms most coached cyclists choose between in 2026.",
      },
      {
        q: "Which platform do most cycling coaches actually use?",
        a: "TrainingPeaks. It's the industry default — the platform the vast majority of professional and serious amateur coaches have built their workflow on. If you hire a coach in 2026 without specifying a platform, there's a very high chance they'll deliver your plan through TrainingPeaks.",
      },
      {
        q: "Do I need TrainingPeaks Premium, or is the free tier enough?",
        a: "If you're working with a coach, the free tier is often enough — your coach pushes structured workouts to your calendar and you complete them. If you want to see your own Performance Management Chart, fitness/fatigue trends, and the full analysis suite, Premium ($19.95/mo) unlocks the tools that make the platform genuinely powerful for self-directed athletes.",
      },
      {
        q: "What is WKO5 and why does it matter?",
        a: "WKO5 is TrainingPeaks' high-performance analysis software — the desktop tool serious coaches use for power-duration modelling, durability analysis, and individualised zones beyond standard FTP. It's the same software many WorldTour and high-performance teams use under the hood. The fact that TrainingPeaks owns it and integrates with it directly is a meaningful advantage if you ever work with a coach who runs WKO.",
      },
      {
        q: "Is Vekta a bad platform?",
        a: "Not at all — Vekta is a well-built, well-maintained platform with some genuinely useful features, particularly the auto-adjusting plan structure. It's just newer and smaller than TrainingPeaks, with a smaller coach base and fewer third-party integrations. It's the right tool inside a community that's chosen it (like Roadman's Not Done Yet plans). For an athlete building their own long-term setup independent of a specific community, TrainingPeaks is the broader, deeper choice.",
      },
      {
        q: "Can I use both?",
        a: "Yes — and many serious athletes do. You might run TrainingPeaks as your home platform for analysis and history while following a Vekta-delivered plan from a coach or community. They both connect to Garmin, Wahoo and Zwift, so your rides land in both places. The only friction is structured-workout delivery, which has to come from one platform or the other.",
      },
      {
        q: "Roadman uses Vekta — why is the verdict still TrainingPeaks?",
        a: "Because the verdict is about the platforms, not the partnership. Roadman uses Vekta to deliver plans inside the Not Done Yet community because it suits that specific delivery model. That doesn't change the broader truth: TrainingPeaks is the industry-standard platform with the deepest analysis tools, the biggest coach base, and the longest data history. We'd recommend TrainingPeaks even if we weren't a partner — the partnership is downstream of the recommendation.",
      },
    ],
  },
  {
    slug: "base-vs-build-training",
    title: "Base Training vs Build Training — When to Switch",
    seoTitle: "Base Training vs Build Training — When to Switch",
    seoDescription: "Base first, then build — but how much base is enough? The signals, timing, and consequences of switching phases too early or too late.",
    optionA: "Base Phase",
    optionB: "Build Phase",
    verdict: "Most amateurs leave base too early. A proper base phase delivers adaptations you cannot rush — mitochondrial density, fat oxidation, aerobic enzyme concentration — and a short base leaves build work sitting on sand. Switch to build when you can hold Zone 2 effortlessly for 90+ minutes and your 30-day aerobic decoupling stays below 5%.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Intensity distribution", optionA: "80-90% Zone 2, minimal intensity", optionB: "60-70% Zone 2, 20-30% threshold + VO2max" },
      { feature: "Primary adaptation", optionA: "Aerobic system, mitochondria, capillary density", optionB: "Lactate clearance, FTP, VO2max ceiling" },
      { feature: "Typical duration", optionA: "6-12 weeks (longer for less-trained riders)", optionB: "6-8 weeks" },
      { feature: "Weekly hours (amateur)", optionA: "8-15 hours (volume is the point)", optionB: "6-12 hours" },
      { feature: "Fatigue accumulation", optionA: "Low — recovers quickly between sessions", optionB: "High — needs structured recovery" },
      { feature: "Strength training", optionA: "Heavy, 2x weekly — compatible with easy aerobic", optionB: "Maintenance only, usually 1x weekly" },
      { feature: "Readiness signal", optionA: "Always appropriate as starting point", optionB: "Aerobic decoupling <5%, effortless Zone 2 for 90+ min" },
    ],
    bestForA: [
      "Cyclists in the off-season (October-February for most riders)",
      "Riders returning from a break or injury",
      "Anyone whose easy rides don't feel easy",
      "Masters cyclists for whom base work delivers disproportionate gains",
    ],
    bestForB: [
      "Cyclists 8-12 weeks out from an A-race or target event",
      "Riders whose base has been solid for 2+ months",
      "Returning structured athletes who already have an aerobic foundation",
      "Riders whose goal event requires high-intensity performance",
    ],
    relatedArticle: "/blog/cycling-base-training-guide",
    relatedTool: "/tools/ftp-zones",
  },
  {
    slug: "short-vs-long-intervals",
    title: "Short vs Long Intervals — When Each Works",
    seoTitle: "Short vs Long Intervals for Cyclists — Which Builds More Power?",
    seoDescription: "30/30s versus 4x8s versus 2x20s — when each interval length delivers the most adaptation, and how to choose based on your goal event.",
    optionA: "Short Intervals (<2 min)",
    optionB: "Long Intervals (>8 min)",
    verdict: "Short intervals accumulate high-intensity time fast at higher absolute power, ideal for VO2max lift and late-season sharpening. Long intervals build muscular endurance and threshold capacity, ideal for sustained-effort events. Most cyclists benefit from both across a season — but not both in the same block.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Typical duration", optionA: "15-120 seconds", optionB: "8-30 minutes" },
      { feature: "Target intensity", optionA: "105-130% FTP (VO2max or anaerobic)", optionB: "88-105% FTP (sweet spot to threshold)" },
      { feature: "Primary adaptation", optionA: "VO2max, anaerobic capacity, W'", optionB: "Lactate clearance, TTE, FTP ceiling" },
      { feature: "Subjective difficulty", optionA: "Very hard but short — mentally manageable", optionB: "Hard and sustained — mentally demanding" },
      { feature: "Pacing discipline required", optionA: "Low — reach and hold for 30-60 seconds", optionB: "High — small errors compound over 20+ min" },
      { feature: "Time accumulated at target", optionA: "5-15 minutes per session", optionB: "30-60 minutes per session" },
      { feature: "Recovery cost", optionA: "Moderate — 48 hrs typical", optionB: "High — 48-72 hrs typical" },
      { feature: "Specificity to climbing", optionA: "Moderate (VO2max climbing)", optionB: "High (sustained climbing)" },
      { feature: "Specificity to racing", optionA: "High (attacks, surges)", optionB: "Moderate (pacing, breakaway)" },
    ],
    bestForA: [
      "Cyclists training for road races, crits, or hilly events with attacks",
      "Riders whose events include repeated high-intensity efforts",
      "Athletes building VO2max late in a build phase",
      "Time-crunched riders who get more stimulus per minute",
    ],
    bestForB: [
      "Cyclists training for time trials, gran fondos, triathlons, long climbs",
      "Riders building a strong threshold base in build phase",
      "Athletes who find short-interval pacing chaotic",
      "Riders targeting sustained-effort events (Étape, Ride London)",
    ],
    relatedArticle: "/blog/cycling-interval-training-beginners",
  },
  {
    slug: "cycling-vs-triathlon-coach",
    title: "Cycling Coach vs Triathlon Coach — Which Do Age-Groupers Need?",
    seoTitle: "Cycling Coach vs Triathlon Coach — Which for Age-Groupers?",
    seoDescription: "Most triathlon coaches spread attention across three sports. Most cycling coaches ignore triathlon. Which coaching model actually works for 70.3 and Ironman age-groupers?",
    optionA: "Triathlon Coach",
    optionB: "Cycling Coach (Triathlon-Specialist)",
    verdict: "If swim and run are your weakest disciplines and bike is already strong, pick a triathlon coach who spreads attention. If bike is the leak (true for 70%+ of age-group 70.3 / Ironman fields), pick a cycling coach who periodises the bike around your run without compromising it — that's a smaller but rapidly-growing category of coach.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Bike programming depth", optionA: "Moderate — 40% of weekly focus", optionB: "Deep — bike is the primary lever" },
      { feature: "Swim + run programming", optionA: "Full coverage", optionB: "Limited — typically plan review only" },
      { feature: "Bike-run periodisation", optionA: "Balanced — both respected", optionB: "Bike builds without breaking the run" },
      { feature: "Brick workouts", optionA: "Standard part of programming", optionB: "Integrated but not overweighted" },
      { feature: "Race-day bike strategy", optionA: "Generalist advice", optionB: "Power-file level pacing plan" },
      { feature: "Fuelling on the bike", optionA: "Usually generic advice", optionB: "Individualised — carbs/hr, sodium/hr, gut training" },
      { feature: "Typical cost", optionA: "$250-500/mo full triathlon", optionB: "$150-250/mo bike-focused" },
      { feature: "Best for weak swimmer or runner", optionA: "Clear winner", optionB: "Less relevant" },
      { feature: "Best for bike-leg performance", optionA: "Competent but not specialised", optionB: "Clear winner" },
    ],
    bestForA: [
      "Age-groupers whose swim or run is the clear limiter",
      "First-time triathletes needing coaching across all three disciplines",
      "Athletes training for drafting formats (ITU-style) where bike is less decisive",
      "Anyone who wants one coach handling everything",
    ],
    bestForB: [
      "70.3 and Ironman age-groupers whose bike leg is the largest time opportunity",
      "Strong-run triathletes who need bike development without compromising run",
      "Bike-leg PR chasers targeting specific split times",
      "Experienced triathletes who handle swim/run independently",
    ],
    relatedArticle: "/blog/cycling-coach-vs-triathlon-coach",
  },
  {
    slug: "fueled-vs-fasted-sessions",
    title: "Fueled vs Fasted Sessions — When Each Is Optimal",
    seoTitle: "Fueled vs Fasted Cycling Sessions — When Each Wins",
    seoDescription: "Fasted rides are not universally better or worse. The specific session types where fasted work delivers adaptation — and the types where it wrecks performance.",
    optionA: "Fasted Session",
    optionB: "Fueled Session",
    verdict: "Use fasted work for easy Zone 2 rides under 90 minutes, targeting fat-oxidation adaptations. Fuel every session over 90 minutes, every threshold/VO2max session, and every session over 3 hours. Chronic fasted training slides into RED-S; strategic fasted training produces measurable adaptations.",
    verdictWinner: "depends",
    pillar: "nutrition",
    features: [
      { feature: "Ideal session type", optionA: "Zone 2 under 90 min, morning before breakfast", optionB: "Threshold, VO2max, anything over 90 min" },
      { feature: "Primary adaptation", optionA: "Fat oxidation capacity, mitochondrial biogenesis", optionB: "Session quality, training stimulus, recovery" },
      { feature: "Risk", optionA: "Low-to-moderate if session is appropriately easy", optionB: "Low" },
      { feature: "Frequency", optionA: "Maximum 1-2 sessions per week", optionB: "Every other session and all key ones" },
      { feature: "Weekly carbs", optionA: "Periodised — lower on fasted days", optionB: "Higher — match to workload" },
      { feature: "Hormonal risk", optionA: "Real if fasted training becomes chronic", optionB: "Minimal" },
      { feature: "Performance in session", optionA: "Lower — expect 5-10% reduced power", optionB: "Normal to improved" },
      { feature: "Appetite regulation", optionA: "Varies — some riders over-eat after", optionB: "Stable" },
      { feature: "Race-day use", optionA: "Never — races always fully fueled", optionB: "Always" },
    ],
    bestForA: [
      "Lean, well-fuelled cyclists adding targeted fat-oxidation adaptation",
      "Riders doing 1-2 easy Zone 2 sessions a week",
      "Athletes with a healthy relationship with food and no RED-S history",
      "Advanced cyclists already hitting daily carb + protein targets",
    ],
    bestForB: [
      "Any session over 90 minutes",
      "All threshold, VO2max, or race-pace work",
      "Masters cyclists (over-40 recovery windows matter more)",
      "Anyone with under-eating history, RED-S symptoms, or body-image pressure",
    ],
    relatedArticle: "/blog/fasted-vs-fueled-cycling",
    relatedTool: "/tools/fuelling",
  },
  {
    slug: "volume-vs-intensity",
    title: "Volume vs Intensity — Which Drives More Improvement?",
    seoTitle: "Cycling Volume vs Intensity — Which Matters More?",
    seoDescription: "More hours or harder hours? The research, the physiology, and the honest answer for time-constrained amateur cyclists.",
    optionA: "Volume (More Hours)",
    optionB: "Intensity (Harder Hours)",
    verdict: "Volume wins up to about 10-12 hours per week — if you can add easy hours, do. Above 12 hours per week, the marginal gains from more volume flatten and intensity becomes the larger lever. Most amateurs are time-constrained at 6-8 hours/week, so the right question is 'how do I use my limited hours?' — which is where the polarised 80/20 distribution keeps winning.",
    verdictWinner: "depends",
    pillar: "coaching",
    features: [
      { feature: "Effect at <8 hrs/week", optionA: "Diminishing — less room to add", optionB: "Dominant lever — quality matters most" },
      { feature: "Effect at 8-12 hrs/week", optionA: "Strong — each added hour gives significant return", optionB: "Important but secondary" },
      { feature: "Effect at >12 hrs/week", optionA: "Flattening returns", optionB: "Now the dominant lever" },
      { feature: "Primary adaptation", optionA: "Aerobic base, mitochondria, durability", optionB: "Lactate clearance, VO2max, power ceiling" },
      { feature: "Injury and fatigue risk", optionA: "Low at easy pace — high if volume done at grey-zone intensity", optionB: "Higher — needs structured recovery" },
      { feature: "Life compatibility", optionA: "Requires many free hours", optionB: "Compatible with short windows" },
      { feature: "Best for masters cyclists", optionA: "High — aerobic base protects ageing systems", optionB: "Important but needs longer recovery between sessions" },
      { feature: "Best for time-crunched riders (<6 hrs/wk)", optionA: "Limited — not enough hours to drive volume adaptation", optionB: "Clear winner — make the hours count" },
    ],
    bestForA: [
      "Cyclists with 10+ hours per week available and a multi-year horizon",
      "Riders whose events are long (gran fondo, 70.3, Ironman)",
      "Anyone whose easy rides are actually easy",
      "Masters cyclists in their base phase",
    ],
    bestForB: [
      "Time-crunched riders with 4-8 hours per week",
      "Athletes 8-12 weeks out from an intensity-dominant event",
      "Riders whose volume is already ~10 hrs/week and gains have plateaued",
      "Cyclists whose goal is short-duration power (crits, road races)",
    ],
    relatedArticle: "/blog/time-crunched-cyclist-8-hours-week",
  },
  {
    slug: "morning-vs-evening-training",
    title: "Morning vs Evening Cycling Training",
    seoTitle: "Morning vs Evening Cycling: Which Is Better?",
    seoDescription: "Train morning or evening? Circadian rhythms, sleep impact, and scheduling compared for cyclists.",
    optionA: "Morning Training", optionB: "Evening Training",
    verdict: "Neither is physiologically superior — consistency matters more. Morning protects from schedule conflicts. Evening aligns with peak power. Choose whichever you'll do 5 days a week.",
    verdictWinner: "depends", pillar: "coaching",
    features: [
      { feature: "Session consistency", optionA: "Higher — fewer conflicts", optionB: "Lower — work/family can override" },
      { feature: "Peak power output", optionA: "~5% lower than afternoon peak", optionB: "Aligns with circadian peak (4-6pm)" },
      { feature: "Sleep impact", optionA: "No negative impact", optionB: "Hard sessions near bed can disrupt sleep" },
      { feature: "Fasted training option", optionA: "Natural — overnight fast", optionB: "Requires deliberate fasting" },
      { feature: "Social riding", optionA: "Limited group options", optionB: "More group rides available" },
    ],
    bestForA: ["Riders struggling with evening consistency", "Parents with evening commitments", "Riders wanting fasted sessions"],
    bestForB: ["Riders targeting peak-power sessions", "Social riders wanting groups", "Night owls"],
    relatedArticle: "/blog/cycling-sleep-optimisation",
  },
  {
    slug: "group-rides-vs-solo-training",
    title: "Group Rides vs Solo Training",
    seoTitle: "Group Rides vs Solo Training for Cyclists",
    seoDescription: "Group rides or structured solo? When each approach drives more cycling performance.",
    optionA: "Group Rides", optionB: "Solo Training",
    verdict: "Group rides build race skills and motivation. Solo builds structured fitness. Optimal: 1-2 group rides per week, remaining sessions solo with structure.",
    verdictWinner: "depends", pillar: "coaching",
    features: [
      { feature: "Intensity control", optionA: "Poor — group dictates", optionB: "Perfect — you set every watt" },
      { feature: "Race-skill development", optionA: "Excellent — drafting, surges", optionB: "None" },
      { feature: "Motivation", optionA: "High — social accountability", optionB: "Self-directed" },
      { feature: "Plan adherence", optionA: "Low — group pace rarely matches plan", optionB: "High" },
    ],
    bestForA: ["Riders needing social motivation", "Racers building pack skills", "Riders in a rut"],
    bestForB: ["Riders following a specific plan", "TT preparation", "Base-building phases"],
    relatedArticle: "/blog/how-to-structure-cycling-training-plan",
  },
  {
    slug: "carbs-vs-fat-adaptation",
    title: "High Carb vs Fat Adaptation for Cycling",
    seoTitle: "High Carb vs Fat Adapted Cycling: Which Wins?",
    seoDescription: "High-carb fuelling vs fat adaptation. The evidence on cycling performance compared.",
    optionA: "High-Carb Fuelling", optionB: "Fat Adaptation (LCHF)",
    verdict: "For any effort above moderate intensity, high-carb wins. Fat adaptation improves ultra-endurance at low intensity but impairs threshold. Evidence-based: train fat oxidation at zone 2, fuel hard sessions with carbs.",
    verdictWinner: "A", pillar: "nutrition",
    features: [
      { feature: "Threshold performance", optionA: "Superior", optionB: "Impaired above moderate intensity" },
      { feature: "Ultra-endurance (6+ hrs)", optionA: "Requires aggressive fuelling", optionB: "Lower dependency but lower power" },
      { feature: "Research support", optionA: "Strong and consistent", optionB: "No performance advantage in trials" },
      { feature: "GI tolerance", optionA: "Requires gut training above 60g/hr", optionB: "Lower GI risk" },
      { feature: "Sustainability", optionA: "Easy socially", optionB: "Restrictive long-term" },
    ],
    bestForA: ["Racers above threshold", "Sportive riders", "Time triallists"],
    bestForB: ["Ultra-endurance at low intensity only", "Metabolic health experiments"],
    relatedArticle: "/blog/fasted-vs-fueled-cycling",
    relatedTool: "/tools/fuelling",
  },
  {
    slug: "single-sided-vs-dual-sided-power",
    title: "Single-Sided vs Dual-Sided Power Meter",
    seoTitle: "Single vs Dual Power Meter: Worth the Extra?",
    seoDescription: "Is dual-sided power worth the premium? Accuracy and value compared for amateur cyclists.",
    optionA: "Single-Sided Power", optionB: "Dual-Sided Power",
    verdict: "For training, single-sided is accurate enough. For known imbalances or bike fitting, dual-sided justifies the premium. Most amateurs should start single-sided.",
    verdictWinner: "depends", pillar: "community",
    features: [
      { feature: "Accuracy", optionA: "Doubles one leg — ±2-5%", optionB: "Both legs — ±1%" },
      { feature: "Left-right balance", optionA: "No — assumes 50/50", optionB: "Yes" },
      { feature: "Consistency", optionA: "Highly consistent", optionB: "Consistent and accurate" },
      { feature: "Cost", optionA: "$200-400", optionB: "$500-900" },
    ],
    bestForA: ["Budget-conscious riders", "Balanced pedal strokes", "First power meter"],
    bestForB: ["Known left-right imbalances", "Bike fit clients", "Post-injury riders"],
    relatedArticle: "/blog/cycling-power-meter-guide",
  },
  {
    slug: "road-bike-vs-gravel-bike",
    title: "Road Bike vs Gravel Bike — One-Bike Decision",
    seoTitle: "Road Bike vs Gravel Bike: Which to Buy?",
    seoDescription: "One bike? Road vs gravel compared for fitness, versatility, events, and conditions.",
    optionA: "Road Bike", optionB: "Gravel Bike",
    verdict: "80%+ tarmac and racing: road bike. One bike for everything: gravel is more versatile. For most recreational cyclists, gravel is the better single-bike option.",
    verdictWinner: "depends", pillar: "community",
    features: [
      { feature: "Speed on tarmac", optionA: "Faster — lighter, aero", optionB: "Slower — heavier, wider tyres" },
      { feature: "Versatility", optionA: "Tarmac only", optionB: "Tarmac, gravel, fire roads, trails" },
      { feature: "Comfort", optionA: "Less", optionB: "More — wider tyres, relaxed geometry" },
      { feature: "Tyre clearance", optionA: "25-32mm", optionB: "40-50mm" },
      { feature: "Event options", optionA: "Road races, sportives, crits", optionB: "Gravel, bikepacking, plus road" },
    ],
    bestForA: ["Competitive road racers", "Time triallists", "Tarmac-only riders"],
    bestForB: ["One-bike riders", "Commuter-weekenders", "Adventure riders"],
    relatedArticle: "/compare/road-vs-gravel-fitness",
  },
  {
    slug: "carbon-vs-aluminium-frame",
    title: "Carbon vs Aluminium Bike Frame",
    seoTitle: "Carbon vs Aluminium Bike: Is Carbon Worth It?",
    seoDescription: "Carbon vs aluminium frames. Weight, comfort, durability, and diminishing returns compared.",
    optionA: "Carbon Frame", optionB: "Aluminium Frame",
    verdict: "Carbon is lighter and more comfortable. But a good aluminium frame with quality wheels outperforms cheap carbon. Money saved on aluminium is often better spent on coaching or a power meter.",
    verdictWinner: "depends", pillar: "community",
    features: [
      { feature: "Weight", optionA: "6.5-8kg complete", optionB: "8-10kg complete" },
      { feature: "Ride comfort", optionA: "Better — vibration damping", optionB: "Harsher" },
      { feature: "Crash durability", optionA: "Lower — can fracture", optionB: "Higher — dents, doesn't shatter" },
      { feature: "Cost", optionA: "$2,000-12,000+", optionB: "$800-3,000" },
      { feature: "Value", optionA: "Diminishing returns above ~$4,000", optionB: "Excellent" },
    ],
    bestForA: ["Competitive racers", "Long-sportive riders", "Riders with full budget"],
    bestForB: ["Budget riders", "Commuters", "Crash-prone riders"],
  },
  {
    slug: "clipless-vs-flat-pedals",
    title: "Clipless vs Flat Pedals for Cycling",
    seoTitle: "Clipless vs Flat Pedals: Do You Need to Clip In?",
    seoDescription: "Clipless vs flats for road cycling. Efficiency, safety, and cost compared.",
    optionA: "Clipless Pedals", optionB: "Flat Pedals",
    verdict: "Clipless offers a small efficiency advantage and better power transfer. Flats are safer for beginners and better for commuting. Most road cyclists benefit from clipless once comfortable.",
    verdictWinner: "A", pillar: "community",
    features: [
      { feature: "Power transfer", optionA: "Better — stiff sole + fixed", optionB: "Good with stiff shoes" },
      { feature: "Beginner safety", optionA: "Learning curve — tip-over risk", optionB: "No learning curve" },
      { feature: "Walking", optionA: "Poor — cleats slippery", optionB: "Normal — any shoe" },
      { feature: "Cost", optionA: "$150-400 (pedals + shoes)", optionB: "$30-80 pedals only" },
    ],
    bestForA: ["Road racers", "Sportive riders doing 50+ miles", "Comfortable with clip mechanics"],
    bestForB: ["New cyclists", "Commuters", "Urban stop-start riders"],
  },
  {
    slug: "8-week-vs-16-week-plan",
    title: "8-Week vs 16-Week Training Plan",
    seoTitle: "8 vs 16-Week Cycling Plan: Which to Choose?",
    seoDescription: "Short or long plan? How plan length affects fitness gains and event readiness.",
    optionA: "8-Week Plan", optionB: "16-Week Plan",
    verdict: "16 weeks allows proper base-build-peak periodisation. 8 weeks is a compressed build phase. Choose 16 if you have time; 8 if the event is close.",
    verdictWinner: "B", pillar: "coaching",
    features: [
      { feature: "Base phase", optionA: "Minimal or skipped", optionB: "4-6 weeks aerobic foundation" },
      { feature: "Total FTP gain", optionA: "5-10%", optionB: "10-20%" },
      { feature: "Durability improvement", optionA: "Minimal", optionB: "Significant" },
      { feature: "Overtraining risk", optionA: "Higher — compressed load", optionB: "Lower — gradual ramp" },
    ],
    bestForA: ["Under 10 weeks to event", "Strong existing base", "Mid-season tune-ups"],
    bestForB: ["First-time events", "Building from low fitness", "A-priority events"],
    relatedArticle: "/blog/how-to-structure-cycling-training-plan",
  },
  {
    slug: "coaching-monthly-vs-annual",
    title: "Monthly vs Annual Coaching Commitment",
    seoTitle: "Monthly vs Annual Cycling Coaching Commitment",
    seoDescription: "Monthly rolling or annual? Cost, continuity, and value compared for coaching.",
    optionA: "Monthly Rolling", optionB: "Annual Commitment",
    verdict: "Monthly gives flexibility to test coaching. Annual gives continuity for periodisation and usually a discount. Testing: monthly. Found the right coach: annual.",
    verdictWinner: "depends", pillar: "coaching",
    features: [
      { feature: "Flexibility", optionA: "Full — cancel anytime", optionB: "Limited — committed" },
      { feature: "Periodisation quality", optionA: "Limited", optionB: "Superior — full-season plan" },
      { feature: "Cost", optionA: "Higher monthly rate", optionB: "10-20% discount usually" },
      { feature: "Coach relationship", optionA: "Developing", optionB: "Deep — mutual investment" },
    ],
    bestForA: ["First-time clients", "Unpredictable schedules", "Trialling coaches"],
    bestForB: ["Full racing season", "Right coach found", "Year-round development"],
    relatedArticle: "/blog/is-a-cycling-coach-worth-it",
  },
  {
    slug: "turbo-trainer-vs-rollers",
    title: "Turbo Trainer vs Rollers",
    seoTitle: "Turbo Trainer vs Rollers: Which Indoor Setup?",
    seoDescription: "Smart trainer or rollers? Power, skill, space, and effectiveness compared.",
    optionA: "Smart Turbo Trainer", optionB: "Rollers",
    verdict: "Smart trainers win for structured training. Rollers win for technique and warm-ups. Most serious indoor trainers choose smart trainer; rollers are a supplement.",
    verdictWinner: "A", pillar: "community",
    features: [
      { feature: "Power accuracy", optionA: "±1-2% built-in", optionB: "None (need separate meter)" },
      { feature: "ERG mode", optionA: "Yes", optionB: "No" },
      { feature: "Platform support", optionA: "Zwift, TrainerRoad, Rouvy", optionB: "Limited" },
      { feature: "Pedalling technique", optionA: "No benefit", optionB: "Excellent — forces smoothness" },
      { feature: "Portability", optionA: "Heavy (15-25kg)", optionB: "Light (5-8kg)" },
    ],
    bestForA: ["Structured training", "Zwift/TrainerRoad users", "3x/week+ indoor"],
    bestForB: ["Pre-race warm-ups", "Technique drills", "Travel training"],
    relatedArticle: "/compare/indoor-vs-outdoor-training",
  },
  {
    slug: "strava-vs-trainingpeaks",
    title: "Strava vs TrainingPeaks for Cyclists",
    seoTitle: "Strava vs TrainingPeaks: Which Do You Need?",
    seoDescription: "Strava for social, TrainingPeaks for coaching? When you need one, both, or neither.",
    optionA: "Strava", optionB: "TrainingPeaks",
    verdict: "Different purposes — most serious cyclists use both. Strava for social + routes. TrainingPeaks for plans + analytics. One pick: Strava if self-coached, TrainingPeaks if coached.",
    verdictWinner: "depends", pillar: "coaching",
    features: [
      { feature: "Purpose", optionA: "Social + logging", optionB: "Planning + analytics" },
      { feature: "Structured workouts", optionA: "Basic", optionB: "Excellent" },
      { feature: "Coach integration", optionA: "None", optionB: "Full" },
      { feature: "Analytics depth", optionA: "Fitness/freshness", optionB: "CTL, ATL, TSB, IF, NP" },
      { feature: "Social features", optionA: "Excellent", optionB: "Minimal" },
      { feature: "Cost", optionA: "Free / $8/month", optionB: "Free / $20/month" },
    ],
    bestForA: ["Self-coached riders", "Social riders", "Route explorers", "Budget riders"],
    bestForB: ["Coached athletes", "Serious self-coached riders", "Data analysts"],
    relatedArticle: "/compare/trainerroad-vs-trainingpeaks",
  },
];

export function getComparisonBySlug(slug: string): ComparisonPage | null {
  return COMPARISONS.find((c) => c.slug === slug) ?? null;
}

export function getAllComparisonSlugs(): string[] {
  return COMPARISONS.map((c) => c.slug);
}
