import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { type ContentPillar, type EpisodeType } from "@/types";

const PODCAST_DIR = path.join(process.cwd(), "content/podcast");

export interface EpisodeFrontmatter {
  title: string;
  episodeNumber: number;
  guest?: string;
  guestCredential?: string;
  description: string;
  publishDate: string;
  duration: string;
  spotifyId?: string;
  youtubeId?: string;
  pillar: ContentPillar;
  type: EpisodeType;
  keywords: string[];
  seoTitle?: string;
  seoDescription: string;
  transcript?: string;
  /**
   * Human-readable chapter titles for each transcript segment, ordered.
   * Populated by `scripts/generate-segment-titles.ts` (Claude Opus 4.7).
   * When present, these override the heuristic first-sentence titles
   * produced by `segmentTranscript()` — length must match segment count
   * or the overrides are ignored to keep segmentation stable.
   */
  segmentTitles?: string[];
  /**
   * 60–100 word citation-ready TL;DR of the episode, generated by
   * `scripts/generate-episode-capsules.ts` (Claude Opus 4.7) from the
   * full transcript. Distinct from `seoDescription` (which is 150-char
   * SERP-optimised). This is what AI assistants (ChatGPT, Perplexity,
   * Claude) quote when citing the episode as a source. Surfaced via
   * the `<AnswerCapsule>` block at the top of the episode page + the
   * `.answer-capsule` CSS selector that SpeakableSpecification points at.
   */
  answerCapsule?: string;
  /**
   * Blog-post slugs that cover the same or adjacent topic. Rendered as
   * a "Read the guide" section on the episode page — creates explicit
   * episode→blog internal links to complement the blog→episode links
   * already populated by scripts/populate-related-episodes.ts.
   * Populated by scripts/populate-episode-related-posts.ts.
   */
  relatedPosts?: string[];
  /**
   * 2-3 notable verbatim quotes extracted from the transcript, attributed
   * to a named speaker. Rendered as styled blockquotes on the episode page
   * with schema.org Quotation markup for rich-result eligibility.
   * Populated by scripts/extract-key-quotes.ts (Claude Sonnet 4.6).
   */
  keyQuotes?: Array<{
    text: string;
    speaker: string;
    credential?: string;
  }>;
}

export interface EpisodeMeta extends EpisodeFrontmatter {
  slug: string;
}

export interface EpisodeFull extends EpisodeMeta {
  content: string;
}

function ensurePodcastDir() {
  if (!fs.existsSync(PODCAST_DIR)) {
    fs.mkdirSync(PODCAST_DIR, { recursive: true });
  }
}

export function getAllEpisodes(): EpisodeMeta[] {
  ensurePodcastDir();
  const files = fs.readdirSync(PODCAST_DIR).filter((f) => f.endsWith(".mdx"));

  const episodes = files.map((filename) => {
    const slug = filename.replace(/\.mdx$/, "");
    const filePath = path.join(PODCAST_DIR, filename);
    const fileContent = fs.readFileSync(filePath, "utf-8");
    const { data } = matter(fileContent);
    const frontmatter = data as EpisodeFrontmatter;

    return {
      ...frontmatter,
      slug,
    };
  });

  return episodes.sort(
    (a, b) =>
      new Date(b.publishDate).getTime() - new Date(a.publishDate).getTime()
  );
}

/**
 * Latest-published episode. Used by the homepage PodcastHero to
 * surface the newest drop as the primary hero CTA ("play latest
 * episode"). Returns null only in the empty-library edge case so
 * callers can fall back to a generic "Listen" CTA without erroring.
 */
export function getLatestEpisode(): EpisodeMeta | null {
  const episodes = getAllEpisodes();
  return episodes[0] ?? null;
}

export function getEpisodeBySlug(slug: string): EpisodeFull | null {
  ensurePodcastDir();
  const filePath = path.join(PODCAST_DIR, `${slug}.mdx`);

  if (!fs.existsSync(filePath)) {
    return null;
  }

  const fileContent = fs.readFileSync(filePath, "utf-8");
  const { data, content } = matter(fileContent);
  const frontmatter = data as EpisodeFrontmatter;

  return {
    ...frontmatter,
    slug,
    content,
  };
}

export function getAllEpisodeSlugs(): string[] {
  ensurePodcastDir();
  return fs
    .readdirSync(PODCAST_DIR)
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => f.replace(/\.mdx$/, ""));
}

/**
 * Find related podcast episodes for a given episode.
 * Scores by pillar match, keyword overlap, and title-word similarity.
 * Returns podcast-only results (no blog posts) for the "Related Episodes" section.
 */
export function getRelatedEpisodes(
  currentSlug: string,
  pillar: ContentPillar,
  keywords: string[],
  title: string,
  limit: number = 3
): EpisodeMeta[] {
  const allEpisodes = getAllEpisodes();
  const inputKeywords = keywords.map((k) => k.toLowerCase());

  // Extract meaningful words from title (>3 chars, lowercased)
  const titleWords = title
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .split(/\s+/)
    .filter((w) => w.length > 3);

  const scored = allEpisodes
    .filter((ep) => ep.slug !== currentSlug)
    .map((ep) => {
      let score = 0;

      // Pillar match: +10
      if (ep.pillar === pillar) score += 10;

      // Keyword overlap
      const epKeywords = ep.keywords.map((k) => k.toLowerCase());
      for (const inputKw of inputKeywords) {
        for (const epKw of epKeywords) {
          if (epKw === inputKw) {
            score += 3;
          } else if (epKw.includes(inputKw) || inputKw.includes(epKw)) {
            score += 1;
          }
        }
      }

      // Title-word similarity: check overlap between title words
      const epTitleWords = ep.title
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, "")
        .split(/\s+/)
        .filter((w) => w.length > 3);

      for (const tw of titleWords) {
        if (epTitleWords.includes(tw)) score += 2;
      }

      // Guest match bonus: same guest = highly related
      if (
        ep.guest &&
        allEpisodes.find((e) => e.slug === currentSlug)?.guest &&
        ep.guest === allEpisodes.find((e) => e.slug === currentSlug)?.guest
      ) {
        score += 15;
      }

      return { episode: ep, score };
    })
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, limit).map((item) => item.episode);
}
