INSERT INTO "recommendation_brands" ("name", "slug", "website_url")
VALUES
  ('MAAP', 'maap', 'https://maap.cc/'),
  ('Continental', 'continental', 'https://www.continental-tires.com/'),
  ('Wahoo', 'wahoo', 'https://www.wahoofitness.com/'),
  ('Zwift', 'zwift', 'https://www.zwift.com/'),
  ('Muc-Off', 'muc-off', 'https://muc-off.com/')
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "website_url" = EXCLUDED."website_url",
  "updated_at" = now();
--> statement-breakpoint
INSERT INTO "recommendation_products" (
  "brand_id",
  "category_id",
  "name",
  "slug",
  "status",
  "badge",
  "evidence_status",
  "verdict",
  "short_description",
  "why_recommend",
  "who_for",
  "who_skip",
  "strengths",
  "limitations",
  "specifications",
  "use_cases",
  "tags",
  "disciplines",
  "seasons",
  "price_band",
  "image_url",
  "image_alt",
  "featured",
  "best_value",
  "sort_order",
  "published_at",
  "last_reviewed_at"
)
SELECT
  b."id",
  c."id",
  v."name",
  v."slug",
  'published',
  v."badge",
  'editorial',
  v."verdict",
  v."short_description",
  v."why_recommend",
  v."who_for",
  v."who_skip",
  v."strengths"::jsonb,
  v."limitations"::jsonb,
  v."specifications"::jsonb,
  v."use_cases"::jsonb,
  v."tags"::jsonb,
  v."disciplines"::jsonb,
  v."seasons"::jsonb,
  v."price_band",
  v."image_url",
  v."image_alt",
  v."featured",
  v."best_value",
  v."sort_order",
  now(),
  now()
FROM (
  VALUES
    (
      'maap',
      'clothing',
      'MAAP Team Bib Evo',
      'maap-team-bib-evo',
      'Premium pick',
      'A premium race-cut bib for riders who care as much about long-ride comfort as a clean, modern silhouette.',
      'MAAP''s endurance-focused bib combines an advanced chamois, supportive Italian fabric and a high-airflow mesh back.',
      'The Team Bib Evo gets the important details right: a supportive cut, seamless brace straps and a chamois designed for long days. It is expensive, but this is the MAAP piece to start with if comfort takes priority over building a full matching wardrobe.',
      'Road riders who want premium bib shorts for long training rides, sportives and fast group rides.',
      'Occasional riders, anyone who prefers a relaxed fit, or cyclists who would get more value from a dependable mid-price bib.',
      '["Advanced chamois designed for all-day wear","Breathable high-airflow back mesh","Four-way stretch Italian fabric","Seamless straps reduce pressure points"]',
      '["Premium price","Close performance fit will not suit everyone","Colour and size availability changes quickly"]',
      '{"Fit":"Performance","Fabric":"Italian, four-way stretch","Chamois":"Male-specific endurance pad"}',
      '["Long road rides","Sportives","Fast group rides"]',
      '["bib shorts","premium cycling kit","MAAP","road apparel"]',
      '["Road","Gravel"]',
      '["Spring","Summer","Autumn"]',
      'Premium',
      'https://cdn.shopify.com/s/files/1/1431/8222/products/Male_TeamBibEvoMAP-Charcoal_PRODUCT_CARD_ALT.jpg?v=1664768351',
      'MAAP Team Bib Evo cycling bib shorts in charcoal',
      true,
      false,
      20
    ),
    (
      'maap',
      'clothing',
      'MAAP Evade Pro Base Jersey 2.0',
      'maap-evade-pro-base-jersey-2',
      'Hot-weather pick',
      'A sharp, breathable race-fit jersey for warm rides when you want technical kit without the shouty graphics.',
      'A lightweight MAAP jersey using recycled Italian fabric, honeycomb mesh sleeves and low-profile pocket construction.',
      'The Evade Pro Base 2.0 balances a very clean look with the practical details a fast summer jersey needs: moisture management, breathable sleeves, secure pockets and a low-profile collar.',
      'Riders who like a close race fit and want a premium warm-weather jersey for training, events and café rides.',
      'Riders who prefer a relaxed cut, need cold-weather insulation or do not want to pay a premium for apparel.',
      '["Breathable honeycomb mesh sleeves","Secure rear pockets with a zipped valuables pocket","Light 150g construction","Recycled and bluesign-approved fabrics"]',
      '["Race fit can feel restrictive if sizing is wrong","Best suited to warm conditions","Premium pricing"]',
      '{"Weight":"150g","Temperature":"18–35°C","Fit":"Core performance fit"}',
      '["Warm-weather road rides","Events","Fast training"]',
      '["cycling jersey","summer kit","MAAP","race fit"]',
      '["Road","Gravel"]',
      '["Summer"]',
      'Premium',
      'https://maap-product-images.b-cdn.net//1431/8222/files/MPMJE221924_GHST.Evade-Pro-Base-Jersey-2.0_GREY_PDP_01.jpg?v=1728451724',
      'MAAP Evade Pro Base Jersey 2.0 in Ghost Grey',
      false,
      false,
      30
    ),
    (
      'continental',
      'tyres-tubes',
      'Continental Grand Prix 5000 S TR',
      'continental-grand-prix-5000-s-tr',
      'Fast tyre pick',
      'A benchmark fast road tyre that gives race-day speed without becoming too precious for regular training.',
      'Continental''s tubeless-ready road tyre combines BlackChili rubber, Vectran puncture protection and hookless compatibility.',
      'The GP5000 S TR is the sensible high-performance choice: quick enough to race, grippy enough for everyday road riding and available in useful widths from 25mm to 35mm.',
      'Road riders moving to tubeless who want a fast tyre for training, sportives and racing.',
      'Riders prioritising maximum winter durability, anyone whose rims are not tubeless compatible, or cyclists outside the US for this retailer offer.',
      '["Low rolling resistance BlackChili compound","Tubeless-ready for hooked and hookless rims","Useful 25–35mm size range","Vectran puncture protection"]',
      '["More expensive than an everyday training tyre","Tubeless installation can take patience","This Competitive Cyclist offer is US-only"]',
      '{"Type":"Tubeless-ready clincher","Sizes":"700c × 25, 28, 30, 32 or 35","Maximum pressure":"73 psi"}',
      '["Fast road riding","Sportives","Racing","Tubeless setups"]',
      '["road tyre","tubeless","Continental","GP5000"]',
      '["Road"]',
      '["Spring","Summer","Autumn"]',
      '$102.95–$116.95',
      'https://static.biketiresdirect.com/productimages/images650/COJUY13-1.jpg',
      'Continental Grand Prix 5000 S TR tubeless-ready road cycling tyre',
      true,
      false,
      40
    ),
    (
      'wahoo',
      'indoor-training',
      'Wahoo KICKR CORE 2 with Zwift Cog and Click',
      'wahoo-kickr-core-2',
      'Indoor pick',
      'The sweet-spot smart trainer for riders who want a convincing indoor ride and quiet virtual shifting without flagship pricing.',
      'A direct-drive smart trainer with Zwift Cog pre-installed, handlebar-mounted Click controls and automatic resistance.',
      'KICKR CORE 2 covers the things that matter for consistent indoor riding: reliable resistance, a built-in power meter, broad 8–13-speed compatibility and Zwift virtual shifting straight out of the box.',
      'Cyclists building a dependable indoor setup for structured training, racing and winter mileage.',
      'Riders who need a fully integrated smart bike, do not use Zwift, or only ride indoors occasionally enough for a basic trainer to do the job.',
      '["Zwift Cog and Click included","Fits most 8–13-speed bikes","Automatic gradient-matched resistance","Direct-drive design keeps noise down"]',
      '["Requires a separate bike and training screen","Virtual shifting is most valuable inside Zwift","A trainer mat and fan are still separate purchases"]',
      '{"Drive":"Direct drive","Compatibility":"Most 8–13-speed bikes","Controls":"Zwift Click"}',
      '["Indoor intervals","Zwift racing","Winter training"]',
      '["smart trainer","Wahoo","Zwift","indoor cycling"]',
      '["Indoor","Road","Triathlon"]',
      '["All year","Winter"]',
      '€549.99 RRP',
      'https://eu.zwift.com/cdn/shop/files/black-friday-promo_10-25_PDP-kickr-core-1-month_d26d0fec-747a-4ee6-9e83-3c80c9550a92.jpg?v=1764633904',
      'Wahoo KICKR CORE 2 smart trainer with Zwift Cog and Click controls',
      true,
      true,
      50
    ),
    (
      'zwift',
      'indoor-training',
      'Zwift Ride Smart Frame',
      'zwift-ride-smart-frame',
      'Shared-home pick',
      'A tidy way to turn a compatible trainer into an always-ready indoor bike that can be adjusted quickly between riders.',
      'An adjustable indoor frame with integrated Zwift controls, virtual shifting and an included Zwift Cog.',
      'The Smart Frame solves the friction that kills indoor consistency: no outdoor bike to mount, no cassette to match and quick adjustment for different riders at home.',
      'Regular Zwift users with a compatible trainer who want a permanent, shareable indoor setup.',
      'Riders without a compatible smart trainer, anyone short on permanent floor space, or cyclists who want a platform-agnostic smart bike.',
      '["Adjusts for riders from 152–198cm","Integrated steering and game controls","Quiet virtual shifting","Keeps the outdoor bike ready to ride"]',
      '["A compatible smart trainer is still required","Not compatible with every trainer","Indoor-only and should not be stored vertically"]',
      '{"Rider height":"152–198cm","Weight":"25.5kg","Drivetrain":"Single-speed Zwift Cog"}',
      '["Permanent pain cave","Shared indoor setup","Zwift racing"]',
      '["smart bike","Zwift Ride","indoor frame","virtual shifting"]',
      '["Indoor"]',
      '["All year","Winter"]',
      '€799.99',
      'https://eu.zwift.com/cdn/shop/files/zwift-ride-smart-frame_89c125f7-3250-4296-bb79-6cea1211b9cf.jpg?v=1724450021',
      'Zwift Ride adjustable smart frame for indoor cycling',
      false,
      false,
      60
    ),
    (
      'muc-off',
      'tools-accessories',
      'Muc-Off All Weather Lube',
      'muc-off-all-weather-lube',
      'Everyday essential',
      'A simple one-bottle chain lube for riders who would rather ride than debate the forecast.',
      'A durable synthetic lube made for road, gravel, commuting and mountain biking in changing conditions.',
      'One dependable bottle is often better than a shelf of specialist lubes. This penetrates the rollers, resists water and uses a pipette so it is easy to apply without flooding the drivetrain.',
      'Year-round riders who want a straightforward lube for mixed weather and regular maintenance.',
      'Wax devotees, riders chasing the absolute lowest drivetrain friction, or anyone who only rides in consistently dry conditions.',
      '["Works in wet and dry conditions","Pipette makes accurate application easy","Helps reduce friction and shifting noise","Suitable for road, gravel, MTB and commuting"]',
      '["Clean and dry the chain before application","Excess lube must be wiped away","Specialist wet or dry lubes may suit extreme conditions better"]',
      '{"Sizes":"50ml or 120ml","Application":"1–2 drops per roller","Formula":"Readily biodegradable synthetic lube"}',
      '["Mixed-weather riding","Routine chain care","Commuting"]',
      '["chain lube","bike maintenance","Muc-Off","all weather"]',
      '["Road","Gravel","MTB","Commuting"]',
      '["All year"]',
      'From €10',
      'https://eu.muc-off.com/cdn/shop/products/Web_20891-AllWeatherLube50ml_2022.jpg?v=1774015829',
      'Muc-Off All Weather bicycle chain lube bottle',
      false,
      true,
      70
    ),
    (
      'muc-off',
      'tools-accessories',
      'Muc-Off X-3 Dirty Chain Machine',
      'muc-off-x3-chain-machine',
      'Workshop pick',
      'A fast, contained way to deep-clean a grimy chain without removing it from the bike.',
      'A reusable chain cleaner with 120 contact points, separate dirty-fluid reservoir and 75ml drivetrain cleaner.',
      'The X-3 makes the unglamorous job easier: cleaner goes into the upper chamber, dirty fluid drops away from the chain, and the brushes reach every face of each link.',
      'Riders who train outdoors year-round and want a repeatable drivetrain-cleaning routine.',
      'Hot-wax users who remove the chain for cleaning, infrequent riders, or anyone happy with a brush and rag.',
      '["120 chain contact points","Separates dirty fluid from the cleaned chain","Heavy-duty reusable body","Includes 75ml drivetrain cleaner"]',
      '["Costs more than a basic brush","Still needs rinsing and drying afterwards","Not suitable for motorcycle chains"]',
      '{"Contact points":"120","Included":"75ml drivetrain cleaner","Compatibility":"Road, gravel, MTB and cyclocross chains"}',
      '["Deep chain cleaning","Winter maintenance","Workshop routine"]',
      '["chain cleaner","drivetrain","Muc-Off","bike tools"]',
      '["Road","Gravel","MTB"]',
      '["All year","Winter"]',
      '£37',
      'https://muc-off.com/cdn/shop/products/277-X3-Chain-Machine_Grey.jpg?v=1616054888',
      'Muc-Off X-3 Dirty Chain Machine and drivetrain cleaner',
      false,
      false,
      80
    ),
    (
      'muc-off',
      'tools-accessories',
      'Muc-Off 8 in 1 Bicycle Cleaning Kit',
      'muc-off-8-in-1-cleaning-kit',
      'Starter kit',
      'The useful all-in-one cleaning kit for a new bike owner—or anyone still washing an expensive bike with one tired sponge.',
      'Cleaner, protectant, sponge and four purpose-made brushes packed in a storage tub that doubles as a parts washer.',
      'It covers a complete bike wash without making you work out which brushes and sprays to buy individually. The tub keeps everything together and becomes genuinely useful when cleaning small parts.',
      'New bike owners, riders setting up a home cleaning station, or anyone buying a practical cycling gift.',
      'Riders who already own good brushes and cleaner, or cyclists without somewhere suitable to wash a bike.',
      '["Complete wash kit in one tub","Four brushes for frames and hard-to-reach areas","Includes cleaner and post-wash protection","Suitable for every type of bicycle"]',
      '["Bulkier than buying only the essentials","Does not include a dedicated chain degreaser","A hose or separate water supply is still needed"]',
      '{"Contents":"Cleaner, Bike Protect, sponge, four brushes and storage tub","Pieces":"8","Compatibility":"All bicycle types"}',
      '["Complete bike wash","New-rider setup","Cycling gift"]',
      '["bike cleaning","cleaning kit","Muc-Off","bike care"]',
      '["Road","Gravel","MTB","Commuting"]',
      '["All year"]',
      '£50',
      'https://muc-off.com/cdn/shop/products/Web_250_8-IN-1-BICYCLE_CLEANING_KIT_ALL_2021.jpg?v=1633005800',
      'Muc-Off 8 in 1 Bicycle Cleaning Kit with brushes and sprays',
      false,
      false,
      90
    )
) AS v(
  "brand_slug",
  "category_slug",
  "name",
  "slug",
  "badge",
  "verdict",
  "short_description",
  "why_recommend",
  "who_for",
  "who_skip",
  "strengths",
  "limitations",
  "specifications",
  "use_cases",
  "tags",
  "disciplines",
  "seasons",
  "price_band",
  "image_url",
  "image_alt",
  "featured",
  "best_value",
  "sort_order"
)
INNER JOIN "recommendation_brands" b ON b."slug" = v."brand_slug"
INNER JOIN "recommendation_categories" c ON c."slug" = v."category_slug"
ON CONFLICT ("slug") DO UPDATE SET
  "brand_id" = EXCLUDED."brand_id",
  "category_id" = EXCLUDED."category_id",
  "status" = EXCLUDED."status",
  "badge" = EXCLUDED."badge",
  "evidence_status" = EXCLUDED."evidence_status",
  "verdict" = EXCLUDED."verdict",
  "short_description" = EXCLUDED."short_description",
  "why_recommend" = EXCLUDED."why_recommend",
  "who_for" = EXCLUDED."who_for",
  "who_skip" = EXCLUDED."who_skip",
  "strengths" = EXCLUDED."strengths",
  "limitations" = EXCLUDED."limitations",
  "specifications" = EXCLUDED."specifications",
  "use_cases" = EXCLUDED."use_cases",
  "tags" = EXCLUDED."tags",
  "disciplines" = EXCLUDED."disciplines",
  "seasons" = EXCLUDED."seasons",
  "price_band" = EXCLUDED."price_band",
  "image_url" = EXCLUDED."image_url",
  "image_alt" = EXCLUDED."image_alt",
  "featured" = EXCLUDED."featured",
  "best_value" = EXCLUDED."best_value",
  "sort_order" = EXCLUDED."sort_order",
  "last_reviewed_at" = now(),
  "updated_at" = now();
--> statement-breakpoint
INSERT INTO "recommendation_offers" (
  "product_id",
  "retailer_name",
  "affiliate_program",
  "destination_url",
  "regions",
  "currency",
  "price_label",
  "priority",
  "active",
  "last_checked_at",
  "last_http_status"
)
SELECT
  p."id",
  v."retailer_name",
  v."affiliate_program",
  v."destination_url",
  v."regions"::jsonb,
  v."currency",
  v."price_label",
  0,
  true,
  now(),
  200
FROM (
  VALUES
    ('maap-team-bib-evo', 'MAAP', 'MAAP Cycling Apparel — Impact, 8% online sale', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-team-bib-evo&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fteam-bib-evo-charcoal', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-evade-pro-base-jersey-2', 'MAAP', 'MAAP Cycling Apparel — Impact, 8% online sale', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-evade-pro-base-jersey-2&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fevade-pro-base-jersey-2-0-ghost-grey', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('continental-grand-prix-5000-s-tr', 'Competitive Cyclist', 'Competitive Cyclist — Impact, 5% online purchase', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=continental-grand-prix-5000-s-tr&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fcontinental-grand-prix-5000-s-tr-tire-tubeless', '["US"]', 'USD', 'From $102.95'),
    ('wahoo-kickr-core-2', 'Zwift', 'Zwift hardware — Impact, 5% hardware sales', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=wahoo-kickr-core-2&u=https%3A%2F%2Feu.zwift.com%2Fcollections%2Fequipment%2Fproducts%2Fwahoo-kickr-core-2', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('wahoo-kickr-core-2', 'Zwift US', 'Zwift hardware — Impact, 5% hardware sales', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=wahoo-kickr-core-2&u=https%3A%2F%2Fus.zwift.com%2Fproducts%2Fwahoo-kickr-core-2', '["US"]', 'USD', 'View current price'),
    ('zwift-ride-smart-frame', 'Zwift', 'Zwift hardware — Impact, 5% hardware sales', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=zwift-ride-smart-frame&u=https%3A%2F%2Feu.zwift.com%2Fproducts%2Fzwift-ride-smart-frame', '["IE","GB","EU"]', 'EUR', '€799.99'),
    ('zwift-ride-smart-frame', 'Zwift US', 'Zwift hardware — Impact, 5% hardware sales', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=zwift-ride-smart-frame&u=https%3A%2F%2Fus.zwift.com%2Fproducts%2Fzwift-ride-smart-frame', '["US"]', 'USD', '$799.99'),
    ('muc-off-all-weather-lube', 'Muc-Off', 'Muc-Off — Impact, 7–10% online sale', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-all-weather-lube&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fall-weather-lube', '["IE","GB","EU"]', 'EUR', 'From €10'),
    ('muc-off-x3-chain-machine', 'Muc-Off', 'Muc-Off — Impact, 7–10% online sale', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-x3-chain-machine&u=https%3A%2F%2Fmuc-off.com%2Fproducts%2Fx-3-dirty-chain-machine', '["IE","GB","EU"]', 'GBP', '£37'),
    ('muc-off-8-in-1-cleaning-kit', 'Muc-Off', 'Muc-Off — Impact, 7–10% online sale', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-8-in-1-cleaning-kit&u=https%3A%2F%2Fmuc-off.com%2Fproducts%2F8-in-1-bicycle-cleaning-kit', '["IE","GB","EU"]', 'GBP', '£50')
) AS v(
  "product_slug",
  "retailer_name",
  "affiliate_program",
  "destination_url",
  "regions",
  "currency",
  "price_label"
)
INNER JOIN "recommendation_products" p ON p."slug" = v."product_slug"
WHERE NOT EXISTS (
  SELECT 1
  FROM "recommendation_offers" o
  WHERE o."product_id" = p."id"
    AND o."retailer_name" = v."retailer_name"
);
