INSERT INTO "recommendation_products" (
  "brand_id", "category_id", "name", "slug", "status", "badge",
  "evidence_status", "verdict", "short_description", "why_recommend",
  "who_for", "who_skip", "strengths", "limitations", "specifications",
  "use_cases", "tags", "disciplines", "seasons", "price_band",
  "image_url", "image_alt", "featured", "best_value", "sort_order",
  "published_at", "last_reviewed_at"
)
SELECT
  b."id", c."id", v."name", v."slug", 'published', v."badge",
  'editorial', v."verdict", v."short_description", v."why_recommend",
  v."who_for", v."who_skip", v."strengths"::jsonb,
  v."limitations"::jsonb, v."specifications"::jsonb,
  v."use_cases"::jsonb, v."tags"::jsonb, v."disciplines"::jsonb,
  v."seasons"::jsonb, v."price_band", v."image_url", v."image_alt",
  v."featured", v."best_value", v."sort_order", now(), now()
FROM (
  VALUES
    ('MAAP Training Jersey 2.0', 'maap-training-jersey-2', 'Everyday jersey', 'The sensible MAAP jersey: clean-looking, comfortable and built for the rides you do every week.', 'A soft-touch training jersey made with lighter recycled Italian fabrics and breathable moisture management.', 'This is the MAAP jersey to buy before chasing the racier pieces. It keeps the premium finish but prioritises repeat-wear comfort and durability, making it easier to justify for regular training.', 'Road riders who want one dependable short-sleeve jersey for weekly training, club rides and long summer days.', 'Racers chasing the lightest, most aerodynamic option or riders who prefer a relaxed club-fit jersey.', '["Soft-touch recycled Italian fabric","Breathable moisture management","Comfort-led endurance fit","Built to keep its structure through regular use"]', '["Still priced above a basic training jersey","Close MAAP sizing rewards checking the size guide","Not designed for cold or wet conditions"]', '{"Category":"Short-sleeve training jersey","Fit":"Endurance performance","Colour":"Thistle"}', '["Weekly training","Club rides","Long road days"]', '["cycling jersey","training kit","MAAP","everyday jersey"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMJE260526_THIS.TrainingJersey2.0_PDP_01.jpg?v=1775541583', 'MAAP Training Jersey 2.0 in Thistle', false, true, 21),
    ('MAAP Spectrum Pro Air Jersey 3.0', 'maap-spectrum-pro-air-jersey-3', 'Hot-weather speed', 'A high-airflow jersey for hard summer rides when ordinary kit starts to feel heavy.', 'MAAP''s heat-focused jersey uses targeted open-mesh zones to push airflow during high-intensity efforts.', 'The Pro Air earns its place when both the temperature and the pace climb. The mapped mesh construction makes more sense for racing, climbing and fast group rides than it does for easy spins.', 'Riders training or racing in hot conditions who want maximum ventilation and a close performance fit.', 'Cool-weather riders, anyone who prefers more coverage, or cyclists looking for an all-season first jersey.', '["Targeted open-mesh ventilation","Designed for high-output riding","Close race-focused silhouette","Light feel in hot conditions"]', '["Specialist rather than all-season kit","Race fit will not suit every rider","Premium price for a summer-only jersey"]', '{"Category":"Hot-weather jersey","Fit":"Race performance","Colour":"Mirage"}', '["Hot-weather training","Racing","Mountain climbs"]', '["summer jersey","race jersey","MAAP","hot weather"]', '["Road"]', '["Summer"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMJE260726_MIRA.SpectrumProAirJersey3-0_PDP_01.jpg?v=1778468306', 'MAAP Spectrum Pro Air Jersey 3.0 in Mirage', false, false, 22),
    ('MAAP Alt_Road Jersey 2.0', 'maap-alt-road-jersey-2', 'Gravel jersey', 'The better MAAP choice for long, rough days where comfort and usable storage matter more than pure aero.', 'A lightweight Merino-blend jersey designed for breathable cooling, stable storage and mixed-terrain durability.', 'Alt_Road hits a useful middle ground: technical enough for hard riding but less road-race specific. The Merino blend and dependable storage make it a strong option for gravel loops and all-day exploring.', 'Gravel riders and road cyclists who value breathability, storage and long-distance comfort over a pure race cut.', 'Riders who want maximum aerodynamic performance or a budget jersey for short spins.', '["Lightweight Merino-blend fabric","High air permeability","Stable storage for rough surfaces","Designed for heat, distance and mixed terrain"]', '["Premium pricing","Merino blends need more careful washing","Less aero-focused than MAAP''s race jerseys"]', '{"Category":"Mixed-terrain jersey","Material":"Lightweight Merino blend","Colour":"Bijou Blue"}', '["Gravel rides","Bikepacking days","Long summer routes"]', '["gravel jersey","Merino cycling jersey","MAAP","Alt_Road"]', '["Gravel","Road","Bikepacking"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMJE241326_BIJO.Alt_RoadJersey2.0_PDP_01.jpg?v=1777439942', 'MAAP Alt_Road Jersey 2.0 in Bijou Blue', false, false, 23),
    ('MAAP Training Bib 3.0', 'maap-training-bib-3', 'Daily bib', 'A repeat-ride bib that puts dependable comfort ahead of marginal race-day gains.', 'A durable training bib with an ergonomic chamois and breathable four-way-stretch fabric.', 'Not every ride needs MAAP''s most expensive bib. The Training Bib 3.0 is the more practical rotation piece, with the support and construction needed for consistent mileage.', 'Cyclists building a quality bib rotation for training, club rides and regular weekend mileage.', 'Riders who want cargo storage, deep-winter insulation or MAAP''s lightest race construction.', '["Ergonomically engineered chamois","Breathable four-way-stretch fabric","Stable support for repeat use","Durable, clean construction"]', '["No cargo pockets","Premium compared with mainstream training bibs","Close fit requires careful sizing"]', '{"Category":"Training bib shorts","Fabric":"Breathable four-way stretch","Colour":"Cobblestone"}', '["Daily training","Club rides","Indoor sessions"]', '["bib shorts","training bib","MAAP","cycling shorts"]', '["Road","Gravel","Indoor"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMBS223126_CBBL.Training_20Bib_PDP_01.jpg?v=1775541238', 'MAAP Training Bib 3.0 in Cobblestone', false, false, 24),
    ('MAAP Alt_Road Cargo Bib 2.0', 'maap-alt-road-cargo-bib-2', 'Gravel cargo pick', 'The load-carrying bib for big gravel days when jersey pockets alone are not enough.', 'A durable mixed-terrain bib with an off-road chamois, triple rear pockets and multi-zone cargo storage.', 'This is a genuinely useful cargo layout rather than a token phone pocket. It spreads food, tools and layers across several secure zones while the off-road-specific pad targets long, uneven days.', 'Gravel riders, bikepackers and long-distance cyclists who want accessible storage without adding a bag.', 'Minimalist road riders, short-ride cyclists or anyone who never uses cargo pockets.', '["Off-road-specific chamois","Integrated rear triple-pocket system","Multiple cargo storage zones","Lightweight, durable stretch fabric"]', '["More expensive than a standard bib","Extra pockets are unnecessary for short rides","Close fit and loaded pockets need careful sizing"]', '{"Category":"Cargo bib shorts","Storage":"Rear triple pockets plus cargo zones","Colour":"Deep Navy"}', '["Gravel epics","Bikepacking","Long unsupported rides"]', '["cargo bib","gravel shorts","MAAP","Alt_Road"]', '["Gravel","Bikepacking","Road"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMBS240526_DPNV.Alt_RoadCargoBib2.0_PDP_01.jpg?v=1777440084', 'MAAP Alt_Road Cargo Bib 2.0 in Deep Navy', false, false, 25),
    ('MAAP Team Bib Evo Cargo', 'maap-team-bib-evo-cargo', 'Road cargo pick', 'Team Bib comfort with discreet side storage—the useful choice for long road days and pocket-heavy events.', 'MAAP''s performance bib adds two side cargo pockets, stable compression and an Elastic Interface chamois.', 'It keeps the road-focused feel of the Team Bib Evo but solves the storage problem on long rides. The two thigh pockets make gels, a phone or gloves easier to reach without turning it into full gravel kit.', 'Road and endurance riders who want premium bib comfort with quick-access storage.', 'Riders who prefer a completely clean race silhouette or need the larger storage system of the Alt_Road bib.', '["Two accessible side cargo pockets","3D thermo-moulded Elastic Interface chamois","Stable compression and moisture control","Seamless braces help secure the fit"]', '["Costs more than the standard Team Bib Evo","Side pockets change the classic road look","Premium fit is unforgiving of the wrong size"]', '{"Category":"Performance cargo bib shorts","Storage":"Dual side pockets","Colour":"Deep Navy"}', '["Long road rides","Sportives","Ultra-distance events"]', '["cargo bib","road bib shorts","MAAP","Team Bib Evo"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMBS240226_DPNV.TEAMBibEvoCargo_PDP_01.jpg?v=1772430947', 'MAAP Team Bib Evo Cargo in Deep Navy', false, false, 26),
    ('Women''s MAAP Training Jersey 2.0', 'womens-maap-training-jersey-2', 'Women''s everyday jersey', 'A women-specific MAAP training jersey that is made for repeat wear, not just race-day photos.', 'A lighter, soft-touch women''s jersey with recycled Italian fabrics and breathable moisture management.', 'It brings the same practical brief as the men''s Training Jersey into a women-specific cut: reliable fabric, clean construction and comfort that suits the bulk of weekly riding.', 'Women who want a premium short-sleeve jersey for training, club rides and long summer miles.', 'Riders wanting a relaxed fit, maximum aero performance or cold-weather protection.', '["Women-specific performance cut","Soft-touch recycled Italian fabric","Breathable moisture management","Durable construction for regular use"]', '["Premium price","Close sizing should be checked carefully","Short sleeves limit shoulder-season use"]', '{"Category":"Women''s short-sleeve training jersey","Fit":"Endurance performance","Colour":"Washed Red"}', '["Weekly training","Club rides","Long road days"]', '["women''s cycling jersey","training kit","MAAP","women''s apparel"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPWJE260526_WSHR.Women_27sTrainingJersey2.0_PDP_01.jpg?v=1775541595', 'Women''s MAAP Training Jersey 2.0 in Washed Red', false, false, 27),
    ('Women''s MAAP Team Bib Evo', 'womens-maap-team-bib-evo', 'Women''s premium bib', 'The women-specific version of MAAP''s core endurance bib, built around support rather than unnecessary detail.', 'A women''s performance bib with stable compression, seamless braces, a ventilated back and a 3D thermo-moulded chamois.', 'This is the anchor piece for a women''s MAAP kit. The construction focuses on the things that decide whether bibs work after several hours: stable fit, ventilation and pressure relief.', 'Women looking for premium bib shorts for long road rides, events and fast weekly training.', 'Occasional riders, cyclists wanting cargo storage or anyone who prefers a less compressive fit.', '["Women-specific fit","3D thermo-moulded Elastic Interface chamois","Ventilated back panel","Seamless braces and stable compression"]', '["Premium price","No cargo pockets","Performance fit needs careful sizing"]', '{"Category":"Women''s performance bib shorts","Chamois":"3D thermo-moulded Elastic Interface","Colour":"Titanium"}', '["Long road rides","Sportives","Fast group rides"]', '["women''s bib shorts","MAAP","Team Bib Evo","cycling kit"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPWBS211126_TITN.Women_27sTeamBibEvo_PDP_01.jpg?v=1772430341', 'Women''s MAAP Team Bib Evo in Titanium', false, false, 28),
    ('MAAP Atmos Vest', 'maap-atmos-vest', 'Packable rain layer', 'A tiny, serious rain layer for days when the forecast cannot make up its mind.', 'An ultra-packable Pertex Shield vest with two-way stretch and a 20,000mm waterproof rating.', 'Most emergency layers are either protective or genuinely pocketable. The Atmos Vest combines both, making it the layer to carry on exposed routes, changeable mountain days and fast rides with little spare storage.', 'Road riders who want lightweight wind and rain protection that disappears into a jersey pocket.', 'Cyclists needing full-sleeve winter protection or riders who rarely head out in unsettled weather.', '["20,000mm waterproof rating","Lightweight Pertex Shield fabric","Two-way stretch for on-bike movement","Packs into a jersey pocket"]', '["Very premium price for a vest","No sleeve protection","Minimal construction is less useful for deep winter"]', '{"Category":"Packable waterproof vest","Fabric":"Pertex Shield","Waterproofing":"20,000mm"}', '["Changeable forecasts","Mountain descents","Emergency layer"]', '["cycling vest","rain vest","MAAP","packable layer"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MAP-MAV129_BLK.ATMOS_20VEST_BLACK_PRODUCT_CARD_HERO.jpg?v=1738707617', 'Black MAAP Atmos waterproof cycling vest', false, false, 29),
    ('MAAP Elements Pro Race Jacket', 'maap-elements-pro-race-jacket', 'Wet-weather jacket', 'A race-cut waterproof for holding the pace when bad weather becomes the whole ride.', 'A waterproof, breathable Polartec Power Shield jacket with stretch panelling for on-bike movement.', 'This is not just an emergency shell. The stretch construction and close cut are designed for riding hard through persistent rain, when a flappy backup jacket becomes annoying.', 'Committed road riders who train through wet weather and want a close, performance-focused outer layer.', 'Fair-weather cyclists, commuters wanting a relaxed shell or riders prioritising maximum packability.', '["Waterproof Polartec Power Shield construction","Breathable fabric for higher-output riding","Stretch panelling supports movement","Race-focused fit reduces excess fabric"]', '["Premium investment for a weather layer","Race fit limits casual layering","Less pocketable than an emergency shell"]', '{"Category":"Waterproof race jacket","Fabric":"Polartec Power Shield RPM","Colour":"Black"}', '["Wet-weather training","Cold race days","Long rainy rides"]', '["cycling jacket","waterproof jacket","MAAP","winter kit"]', '["Road","Gravel"]', '["Autumn","Winter","Spring"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMJA250725_BLAK.Elements_20Pro_20Race_20Jacket_PDP_01_5249c09b-dd82-4d37-9ec4-60f8f7e8f419.jpg?v=1757554707', 'Black MAAP Elements Pro Race waterproof cycling jacket', false, false, 31),
    ('MAAP Team Mesh Base Layer', 'maap-team-mesh-base-layer', 'Summer layer', 'A light, quick-drying base layer that makes more sense as the ride gets hotter and harder.', 'An ultra-light mesh base layer with recycled nylon, anti-chafe seams and an ergonomic neckline.', 'A good summer base layer manages sweat without feeling like another jersey. This one is stripped back, highly ventilated and shaped to sit cleanly beneath close-fitting MAAP kit.', 'Riders who train hard in warm weather or dislike a clammy jersey directly against the skin.', 'Cold-weather riders looking for insulation or cyclists who prefer riding without a base layer in summer.', '["Ultra-light open-mesh construction","Quick-drying performance","Majority recycled nylon","Anti-chafe seams and ergonomic neckline"]', '["No insulation","White mesh needs careful washing","An optional layer rather than an essential for every rider"]', '{"Category":"Sleeveless summer base layer","Material":"Majority recycled nylon","Colour":"White"}', '["Hot training rides","Racing","Indoor sessions"]', '["base layer","summer cycling kit","MAAP","mesh vest"]', '["Road","Gravel","Indoor"]', '["Summer"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MPMBL250225_WHIT.Team_20Mesh_20Base_20Layer_PDP_01.jpg?v=1759300298', 'White MAAP Team Mesh sleeveless cycling base layer', false, false, 32),
    ('MAAP Spectrum Team Sock', 'maap-spectrum-team-sock', 'Finishing touch', 'The easy way to finish a MAAP kit without turning a pair of socks into a technical thesis.', 'A higher-gauge cycling sock with gentle compression, ribbed ventilation and moisture-wicking yarn.', 'Socks are the low-risk entry point into a premium kit. This pair keeps the design clean and adds the useful details—ventilation, moisture control and enough compression to stay put.', 'Road and gravel riders who want a clean, breathable sock to complete a MAAP kit.', 'Riders who prefer ankle socks, heavy winter socks or the cheapest multipack available.', '["Higher-gauge knit for softness and durability","Ribbed ventilation channels","Moisture-wicking yarn","Light compression helps hold the fit"]', '["Costs more than a standard cycling sock","Not insulated for deep winter","Tall cuff styling is personal"]', '{"Category":"Performance cycling sock","Knit":"High gauge with ribbed ventilation","Colour":"Black"}', '["Road rides","Gravel rides","Matching kit"]', '["cycling socks","MAAP","summer kit","accessories"]', '["Road","Gravel","Indoor"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://cdn.shopify.com/s/files/1/2180/3833/files/MAUSO260826_BLAK.SpectrumTeamSock_PDP_01.jpg?v=1778468179', 'Black MAAP Spectrum Team cycling sock', false, false, 33)
) AS v(
  "name", "slug", "badge", "verdict", "short_description",
  "why_recommend", "who_for", "who_skip", "strengths", "limitations",
  "specifications", "use_cases", "tags", "disciplines", "seasons",
  "price_band", "image_url", "image_alt", "featured", "best_value",
  "sort_order"
)
CROSS JOIN "recommendation_brands" b
CROSS JOIN "recommendation_categories" c
WHERE b."slug" = 'maap' AND c."slug" = 'clothing'
ON CONFLICT ("slug") DO UPDATE SET
  "brand_id" = EXCLUDED."brand_id",
  "category_id" = EXCLUDED."category_id",
  "status" = EXCLUDED."status",
  "badge" = EXCLUDED."badge",
  "evidence_status" = EXCLUDED."evidence_status",
  "verdict" = EXCLUDED."verdict",
  "short_description" = EXCLUDED."short_description",
  "why_recommend" = EXCLUDED."why_recommend",
  "who_for" = EXCLUDED."who_for",
  "who_skip" = EXCLUDED."who_skip",
  "strengths" = EXCLUDED."strengths",
  "limitations" = EXCLUDED."limitations",
  "specifications" = EXCLUDED."specifications",
  "use_cases" = EXCLUDED."use_cases",
  "tags" = EXCLUDED."tags",
  "disciplines" = EXCLUDED."disciplines",
  "seasons" = EXCLUDED."seasons",
  "price_band" = EXCLUDED."price_band",
  "image_url" = EXCLUDED."image_url",
  "image_alt" = EXCLUDED."image_alt",
  "featured" = EXCLUDED."featured",
  "best_value" = EXCLUDED."best_value",
  "sort_order" = EXCLUDED."sort_order",
  "last_reviewed_at" = now(),
  "updated_at" = now();
--> statement-breakpoint
INSERT INTO "recommendation_offers" (
  "product_id", "retailer_name", "affiliate_program", "destination_url",
  "regions", "currency", "price_label", "priority", "active",
  "last_checked_at", "last_http_status"
)
SELECT
  p."id", v."retailer_name", v."affiliate_program",
  v."destination_url", v."regions"::jsonb, v."currency",
  v."price_label", 0, true, now(), 200
FROM (
  VALUES
    ('maap-training-jersey-2', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-training-jersey-2&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Ftraining-jersey-2-0-thistle', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-spectrum-pro-air-jersey-3', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-spectrum-pro-air-jersey-3&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fspectrum-pro-air-jersey-3-0-mirage', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-alt-road-jersey-2', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-alt-road-jersey-2&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Falt_road-jersey-2-0-bijou-blue', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-training-bib-3', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-training-bib-3&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Ftraining-bib-3-0-cobblestone', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-alt-road-cargo-bib-2', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-alt-road-cargo-bib-2&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Falt_road-cargo-bib-2-0-deep-navy', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-team-bib-evo-cargo', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-team-bib-evo-cargo&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fteam-bib-evo-cargo-deep-navy', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('womens-maap-training-jersey-2', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=womens-maap-training-jersey-2&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fwomens-training-jersey-2-0-washed-red', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('womens-maap-team-bib-evo', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=womens-maap-team-bib-evo&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fwomens-team-bib-evo-titanium', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-atmos-vest', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-atmos-vest&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fatmos-vest-black', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-elements-pro-race-jacket', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-elements-pro-race-jacket&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Felements-pro-race-jacket-black', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-team-mesh-base-layer', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-team-mesh-base-layer&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fteam-mesh-base-layer-white', '["IE","GB","EU","US"]', 'EUR', 'View current price'),
    ('maap-spectrum-team-sock', 'MAAP', 'MAAP Cycling Apparel — Impact', 'https://maap.sjv.io/Ag027D?subId1=roadman-recommends&subId2=maap-spectrum-team-sock&u=https%3A%2F%2Fmaap.cc%2Fproducts%2Fspectrum-team-sock-black', '["IE","GB","EU","US"]', 'EUR', 'View current price')
) AS v(
  "product_slug", "retailer_name", "affiliate_program",
  "destination_url", "regions", "currency", "price_label"
)
INNER JOIN "recommendation_products" p ON p."slug" = v."product_slug"
WHERE NOT EXISTS (
  SELECT 1
  FROM "recommendation_offers" o
  WHERE o."product_id" = p."id"
    AND o."retailer_name" = v."retailer_name"
);
