INSERT INTO "recommendation_brands" ("name", "slug", "website_url")
VALUES
  ('Garmin', 'garmin', 'https://www.garmin.com/'),
  ('Shimano', 'shimano', 'https://bike.shimano.com/'),
  ('POC', 'poc', 'https://poc.com/'),
  ('Kask', 'kask', 'https://www.kask.com/'),
  ('Fizik', 'fizik', 'https://www.fizik.com/'),
  ('Vittoria', 'vittoria', 'https://www.vittoria.com/'),
  ('Pirelli', 'pirelli', 'https://www.pirelli.com/tyres/en-ww/bike'),
  ('Silca', 'silca', 'https://silca.cc/'),
  ('Feedback Sports', 'feedback-sports', 'https://feedbacksports.com/'),
  ('Oakley', 'oakley', 'https://www.oakley.com/')
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "website_url" = EXCLUDED."website_url",
  "updated_at" = now();
--> statement-breakpoint
INSERT INTO "recommendation_categories" (
  "name", "slug", "description", "sort_order"
)
VALUES (
  'Components & Upgrades',
  'components-upgrades',
  'Pedals, saddles and performance upgrades that make a meaningful difference on the road.',
  55
)
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "sort_order" = EXCLUDED."sort_order",
  "updated_at" = now();
--> statement-breakpoint
INSERT INTO "recommendation_products" (
  "brand_id", "category_id", "name", "slug", "status", "badge",
  "evidence_status", "verdict", "short_description", "why_recommend",
  "who_for", "who_skip", "strengths", "limitations", "specifications",
  "use_cases", "tags", "disciplines", "seasons", "price_band",
  "image_url", "image_alt", "featured", "best_value", "sort_order",
  "published_at", "last_reviewed_at"
)
SELECT
  b."id", c."id", v."name", v."slug", 'published', v."badge",
  'editorial', v."verdict", v."short_description", v."why_recommend",
  v."who_for", v."who_skip", v."strengths"::jsonb,
  v."limitations"::jsonb, v."specifications"::jsonb,
  v."use_cases"::jsonb, v."tags"::jsonb, v."disciplines"::jsonb,
  v."seasons"::jsonb, v."price_band", v."image_url", v."image_alt",
  v."featured", v."best_value", v."sort_order", now(), now()
FROM (
  VALUES
    ('garmin', 'tech-gps', 'Garmin Edge 1050', 'garmin-edge-1050', 'Flagship computer', 'The best Garmin screen and interface for riders who want maps, training and safety data in one place.', 'A premium GPS computer with a vivid 3.5-inch touchscreen, advanced navigation and broad sensor connectivity.', 'The Edge 1050 is expensive, but its bright, responsive display makes maps and data genuinely easier to read at speed. It is the choice for riders who use navigation, structured training and connected safety features every week.', 'High-mileage road riders, racers and explorers who want Garmin''s fullest navigation and training experience.', 'Riders happy with a smaller computer, ultra-distance cyclists prioritising maximum battery life or anyone who only needs speed and distance.', '["Bright 3.5-inch colour touchscreen","Up to 20 hours in demanding use or 60 hours in battery saver","Bluetooth, ANT+ and Wi-Fi connectivity","Detailed mapping, training and road-hazard features"]', '["Flagship price","Larger and heavier than simpler head units","Battery life trails the screen-free efficiency of endurance models"]', '{"Display":"3.5-inch colour touchscreen","Battery":"Up to 20 hours; 60 hours in battery saver","Connectivity":"Bluetooth, ANT+ and Wi-Fi"}', '["Navigation","Structured training","Long road events"]', '["bike computer","GPS","Garmin","navigation"]', '["Road","Gravel","Triathlon"]', '["All year"]', 'Flagship', 'https://content.competitivecyclist.com/images/items/large/GRM/GRMF07I/BLA.jpg', 'Garmin Edge 1050 GPS cycling computer', true, false, 100),
    ('garmin', 'safety-visibility', 'Garmin Varia RTL515', 'garmin-varia-rtl515', 'Safety essential', 'The rear light that also tells you what is approaching—one of the most useful road-safety upgrades available.', 'A rear radar and taillight that warns compatible computers or phones about vehicles approaching from behind.', 'The value is not replacing a shoulder check; it is getting an early warning before a vehicle reaches you. On quiet lanes, fast descents and solo rides, that extra awareness changes how calmly you hold your line.', 'Road riders who spend time on open roads and want better awareness of approaching traffic.', 'Riders who only cycle on traffic-free routes or do not use a compatible display or smartphone.', '["Detects vehicles from up to 140 metres","Taillight visible from up to one mile","Up to 16 hours in day-flash mode","Works with compatible Garmin, third-party computers and phones"]', '["Does not replace looking behind","Needs a compatible display for the best experience","Another device to charge"]', '{"Radar":"Up to 140m detection range","Light":"Up to one-mile visibility","Battery":"Up to 16 hours in day flash"}', '["Solo road rides","Country lanes","Low-light training"]', '["rear radar","bike light","Garmin","road safety"]', '["Road","Gravel","Commuting"]', '["All year"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/GRM/GRMF011/ONECOL.jpg', 'Garmin Varia RTL515 rear radar and taillight', true, false, 110),
    ('garmin', 'components-upgrades', 'Garmin Rally RS110 Power Pedals', 'garmin-rally-rs110-power-pedals', 'Power upgrade', 'A clean route into reliable power data for Shimano-cleat riders who want easy bike-to-bike swaps.', 'Single-sided SPD-SL-compatible power pedals with rechargeable batteries and claimed ±1% accuracy.', 'Pedal power is the easiest format to move between bikes. The RS110 keeps the familiar Shimano road interface, adds long rechargeable runtime and leaves an upgrade path to dual-sided measurement.', 'Road riders starting structured power training or sharing one power meter across several bikes.', 'Riders who need left-right balance now, use Look or Speedplay cleats, or already own a crank-based meter.', '["Claimed ±1% power accuracy","Shimano SPD-SL cleat compatibility","Up to 90 hours per charge","Modular and upgradeable pedal design"]', '["Single-sided measurement estimates total power","Costs far more than standard pedals","Pedal bodies can collect cosmetic crash damage"]', '{"Measurement":"Single-sided power and cadence","Accuracy":"Claimed ±1%","Battery":"Rechargeable, up to 90 hours"}', '["Power-based training","Bike-to-bike swaps","Race pacing"]', '["power meter","pedals","Garmin","SPD-SL"]', '["Road","Triathlon"]', '["All year"]', 'Flagship', 'https://content.competitivecyclist.com/images/items/large/GRM/GRMF091/BLA.jpg', 'Garmin Rally RS110 single-sided power meter pedals', false, false, 120),
    ('shimano', 'components-upgrades', 'Shimano Ultegra PD-R8000 Pedals', 'shimano-ultegra-pd-r8000-pedals', 'Dependable pedal', 'The road pedal sweet spot: stable, light enough and famously easy to live with.', 'Carbon-composite SPD-SL pedals with a wide platform and adjustable cleat-retention tension.', 'Ultegra pedals do not need novelty to justify themselves. They offer a broad, reassuring platform, predictable engagement and Shimano serviceability without the cost of Dura-Ace.', 'Road riders wanting a durable performance pedal for training, racing and year-round mileage.', 'Riders who walk frequently, prefer dual-sided entry or want integrated power measurement.', '["Wide, stable carbon-composite platform","Adjustable entry and release tension","Proven SPD-SL cleat system","Competitive 248g claimed pair weight"]', '["Single-sided entry takes practice","Road cleats are awkward for walking","No power measurement"]', '{"System":"Shimano SPD-SL","Body":"Carbon composite with steel plate","Weight":"248g claimed per pair"}', '["Daily road riding","Racing","Sportives"]', '["road pedals","Shimano","Ultegra","SPD-SL"]', '["Road","Triathlon"]', '["All year"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/SHI/SHI00G3/GY.jpg', 'Shimano Ultegra PD-R8000 SPD-SL road pedals', false, true, 121),
    ('shimano', 'clothing', 'Shimano S-PHYRE RC903 Shoes', 'shimano-s-phyre-rc903-shoes', 'Race shoe', 'A benchmark race shoe for riders who want a locked-in heel and a very stiff connection to the bike.', 'Shimano''s flagship road shoe combines a carbon sole, wraparound upper and dual BOA Li2 adjustment.', 'The RC903 focuses on fit security and power transfer rather than gimmicks. The heel cup stays planted under hard efforts and the two BOA zones make small pressure adjustments possible while riding.', 'Racers and performance-focused road riders with narrow-to-average feet who value stiffness and precise adjustment.', 'Wide-footed riders without access to the wide version, casual cyclists or anyone who prioritises walking comfort.', '["Very stiff carbon sole","Dual BOA Li2 micro-adjustment","Secure anti-twist heel cup","Perforated upper for ventilation"]', '["Runs narrow and sizing needs care","Race stiffness is excessive for some riders","Flagship price"]', '{"Closure":"Dual BOA Li2","Cleats":"Three-bolt road","Weight":"225g claimed per shoe in size 42"}', '["Road racing","Fast training","Time trials"]', '["cycling shoes","Shimano","S-PHYRE","race kit"]', '["Road","Triathlon"]', '["Spring","Summer","Autumn"]', 'Flagship', 'https://content.competitivecyclist.com/images/items/large/SHI/SHIU30X/BLA.jpg', 'Black Shimano S-PHYRE RC903 road cycling shoes', false, false, 130),
    ('poc', 'safety-visibility', 'POC Ventral Air MIPS', 'poc-ventral-air-mips', 'Hot-weather helmet', 'A highly ventilated road helmet that keeps the safety story strong without looking bulky.', 'A performance road helmet with MIPS Integra, 18 vents, a unibody shell and an eyewear garage.', 'The Ventral Air is the pick for long climbs and hot days. Its internal channels move a meaningful amount of air, while the integrated MIPS system avoids making the helmet feel overbuilt.', 'Road riders and racers who prioritise ventilation, secure eyewear storage and rotational-impact protection.', 'Cold-weather riders, cyclists who prefer a compact rounder fit or anyone shopping at entry-level prices.', '["MIPS Integra rotational-impact system","18-vent airflow design","Fully wrapped unibody shell","Integrated eyewear garage"]', '["Premium price","Fit shape will not suit every head","Open ventilation gives less cold-weather coverage"]', '{"Safety":"MIPS Integra","Ventilation":"18 vents","Adjustment":"Lightweight ratcheting dial"}', '["Hot road rides","Climbing","Racing"]', '["road helmet","MIPS","POC","summer cycling"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/POC/POCZ1MR/APANAVMAT.jpg', 'POC Ventral Air MIPS road cycling helmet', false, false, 131),
    ('kask', 'safety-visibility', 'Kask Protone Icon', 'kask-protone-icon', 'All-round helmet', 'The polished all-round road helmet for riders who care equally about fit, airflow and a low-profile shape.', 'Kask''s performance road helmet uses a 14-vent shell, OCTOFIT+ adjustment and WG11-tested protection.', 'The Protone Icon has become a road staple because it works across racing, endurance and everyday riding. Its compact profile and vertically adjustable retention system make it especially good for riders who struggle with tall-looking helmets.', 'Road cyclists wanting one premium helmet for training, events and fast summer riding.', 'Riders who specifically want a MIPS-labelled system or need a budget helmet.', '["Compact aerodynamic profile","OCTOFIT+ micro-adjustment","Kask WG11 rotational-impact testing","Fast-drying Coolmax padding"]', '["Premium price","Fourteen vents are fewer than the most open climbing helmets","Helmet fit remains highly individual"]', '{"Safety":"Kask WG11 and CPSC","Ventilation":"14 vents","Adjustment":"OCTOFIT+"}', '["Road racing","Endurance rides","Daily training"]', '["road helmet","Kask","Protone","cycling safety"]', '["Road","Gravel"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/KSK/KSKZ00J/ESPBROMAT.jpg', 'Kask Protone Icon performance road cycling helmet', false, false, 132),
    ('fizik', 'components-upgrades', 'Fizik Vento Argo R1 Adaptive', 'fizik-vento-argo-r1-adaptive', 'Premium saddle', 'A supportive short-nose race saddle with pressure-mapped 3D padding—excellent when the shape matches you.', 'A carbon-railed short-nose saddle using zonal 3D-printed Adaptive cushioning.', 'The benefit is not softness everywhere; it is different support through distinct zones. The short nose suits a rotated, performance position and the open lattice sheds heat better than traditional foam.', 'Flexible road riders who like short-nose saddles and want targeted support in an aggressive position.', 'Riders who have not measured sit-bone width, prefer a rounded endurance shape or expect any saddle to be universally comfortable.', '["Pressure-mapped 3D-printed cushioning","Short-nose performance shape","Breathable open-lattice padding","Light carbon rail construction"]', '["Saddle fit is highly personal","Very expensive","Open lattice needs more detailed cleaning"]', '{"Shape":"Short nose","Padding":"3D-printed Adaptive lattice","Widths":"140mm or 150mm"}', '["Fast road riding","Racing","Aggressive bike fits"]', '["road saddle","Fizik","3D printed","bike fit"]', '["Road","Gravel"]', '["All year"]', 'Flagship', 'https://content.competitivecyclist.com/images/items/large/FIZ/FIZZ047/BLA.jpg', 'Black Fizik Vento Argo R1 Adaptive 3D-printed saddle', false, false, 140),
    ('vittoria', 'tyres-tubes', 'Vittoria Corsa Pro G2.0 TLR', 'vittoria-corsa-pro-g2-tlr', 'Supple race tyre', 'The race tyre for riders who value a beautifully supple feel as much as outright speed.', 'A 320 TPI tubeless-ready cotton tyre using a graphene and silica compound for speed and grip.', 'The Corsa Pro''s appeal is the way it takes the sting out of imperfect roads while still feeling genuinely fast. It is a strong alternative to the GP5000 for riders who prioritise ride quality and cornering feel.', 'Road racers and fast riders seeking a premium tubeless tyre with a supple casing.', 'Winter commuters, durability-first riders or cyclists who want a low-maintenance training tyre.', '["Supple 320 TPI cotton casing","Graphene and silica compound","Tubeless-ready construction","Widths from 24mm to 32mm"]', '["Premium price and race-focused lifespan","Cotton sidewalls need more care","Tubeless installation can be messy"]', '{"Type":"Tubeless-ready","Casing":"320 TPI cotton","Sizes":"700 × 24–32c"}', '["Road racing","Fast summer riding","Gran fondos"]', '["road tyre","tubeless","Vittoria","race tyre"]', '["Road"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/VIT/VITC04F/REDBLA.jpg', 'Vittoria Corsa Pro G2.0 tubeless-ready road tyre', false, false, 41),
    ('pirelli', 'tyres-tubes', 'Pirelli P Zero Race TLR RS', 'pirelli-p-zero-race-tlr-rs', 'Fast race tyre', 'A direct, quick race tyre for riders chasing low rolling resistance without abandoning wet-road grip.', 'Pirelli''s tubeless-ready road race tyre combines SmartEVO rubber with a 120 TPI SpeedCORE casing.', 'The RS is the sharpest P Zero choice for race day and fast summer events. It rewards good roads and confident handling more than it rewards riders looking for maximum winter protection.', 'Road racers and performance riders wanting Pirelli''s fastest tubeless-ready road construction.', 'High-mileage winter riders, puncture-anxious commuters or cyclists prioritising value per kilometre.', '["Fast SpeedCORE construction","SmartEVO wet-and-dry compound","Modern 26–32mm size range","Tubeless-ready"]', '["Race durability rather than winter toughness","Premium price","Limited benefit on rough, debris-heavy roads"]', '{"Type":"Tubeless-ready","Casing":"120 TPI SpeedCORE","Sizes":"700 × 26–32c"}', '["Road racing","Fast events","Summer best-bike setup"]', '["road tyre","Pirelli","tubeless","race tyre"]', '["Road"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/PIR/PIR1WWI/BLA.jpg', 'Pirelli P Zero Race TLR RS road cycling tyre', false, false, 42),
    ('silca', 'tools-accessories', 'Silca Mattone Seat Pack', 'silca-mattone-seat-pack', 'Saddle-pack pick', 'A compact, rattle-free way to carry the road essentials without spoiling the lines of the bike.', 'A small structured saddle pack secured by a BOA dial, with organised storage for a tube, CO₂ and tools.', 'The Mattone sits tight against the saddle and avoids dangling straps. It is sized for the essentials rather than becoming a second luggage compartment, which is exactly right for everyday road riding.', 'Road riders who want a neat, secure home for a tube, inflator, levers and multi-tool.', 'Bikepackers, riders carrying bulky jackets or cyclists who prefer tools in a jersey pocket.', '["Secure BOA closure","Compact structured shape","Internal organisation","Low movement and rattle"]', '["Limited capacity","Costs more than a basic saddle bag","Careful packing is required"]', '{"Closure":"BOA dial","Position":"Under saddle","Capacity":"Road repair essentials"}', '["Daily road kit","Race spares","Minimal repair carry"]', '["saddle bag","Silca","ride essentials","road accessories"]', '["Road","Gravel"]', '["All year"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/SLC/SLCD01E/BLA.jpg', 'Black Silca Mattone compact saddle pack', false, true, 150),
    ('silca', 'tools-accessories', 'Silca Super Secret 2.0', 'silca-super-secret-2-chain-lube', 'Drip-wax pick', 'Wax-like cleanliness and efficiency without setting up a hot-wax kitchen.', 'An air-drying tungsten-disulfide drip wax that works alone or as a top-up for hot-waxed chains.', 'Super Secret is the bridge between oily lubes and full hot waxing. Applied to a properly stripped chain and allowed to cure, it stays far cleaner than conventional oil and is easy to refresh.', 'Road riders who want a cleaner drivetrain and lower-friction wax performance with a simple bottle application.', 'Riders unwilling to deep-clean the chain first or anyone who needs a last-minute wet-weather application.', '["Dry, low-grime finish","Tungsten-disulfide wax formula","Compatible with hot-waxed chains","Simple drip application"]', '["Best results require a fully stripped chain","Needs curing time","Poor preparation undermines performance"]', '{"Type":"Air-drying drip wax","Volume":"100ml","Application":"Clean chain; apply and cure"}', '["Clean road drivetrains","Wax top-ups","Race preparation"]', '["chain wax","Silca","drivetrain","bike maintenance"]', '["Road","Gravel","Triathlon"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/SLC/SLCD03J/ONECOL.jpg', 'Silca Super Secret 2.0 drip wax chain lubricant', false, false, 151),
    ('feedback-sports', 'tools-accessories', 'Feedback Sports Pro Mechanic HD', 'feedback-pro-mechanic-hd', 'Workshop stand', 'A buy-once repair stand for serious home maintenance, with enough stability for almost any bike.', 'A folding aluminium work stand with a fast-action clamp, 360-degree adjustment and a 100lb capacity.', 'A stable stand turns cleaning and servicing from an awkward balancing act into a repeatable routine. This is expensive, but the clamp, footprint and folding design are all built for years of use.', 'Cyclists who clean, adjust and service bikes regularly and want a stable home-workshop setup.', 'Riders who outsource all maintenance, have very limited storage or only need a basic wash stand.', '["100lb load capacity","Fast one-handed clamp","Folds for storage or travel","Durable 6061 aluminium construction"]', '["High purchase price","Overkill for occasional adjustments","Still occupies meaningful floor space"]', '{"Capacity":"100lb","Clamp":"Up to 2.6 inches","Weight":"18lb claimed"}', '["Home servicing","Bike washing","Race preparation"]', '["repair stand","workshop","Feedback Sports","bike tools"]', '["Road","Gravel","MTB"]', '["All year"]', 'Flagship', 'https://content.competitivecyclist.com/images/items/large/USS/USSP01B/ONECOL.jpg', 'Feedback Sports Pro Mechanic HD bicycle repair stand', false, false, 152),
    ('oakley', 'safety-visibility', 'Oakley Sutro Prizm', 'oakley-sutro-prizm', 'Road eyewear', 'The big-lens road glasses that deliver excellent coverage and clear contrast without feeling delicate.', 'Shield-style cycling sunglasses with Oakley Prizm optics, a lightweight frame and high-coverage lens.', 'The Sutro became popular for a reason: the lens gives a wide, uninterrupted field of view and keeps wind, spray and insects out. Prizm Road options also make surface detail easier to pick out in changing light.', 'Road riders wanting broad eye coverage, strong contrast and a bold modern shape.', 'Small-faced riders, minimalists who prefer half-frame glasses or cyclists needing interchangeable lenses in one purchase.', '["Wide shield coverage","Prizm contrast-enhancing optics","Stable nose contact","Good wind and debris protection"]', '["Large styling is not subtle","Fit can overwhelm smaller faces","Premium replacement lenses"]', '{"Lens":"Prizm shield","Frame":"Lightweight O Matter","Fit":"High coverage"}', '["Road riding","Racing","Bright and mixed light"]', '["cycling sunglasses","Oakley","Prizm","eye protection"]', '["Road","Gravel"]', '["All year"]', 'Premium', 'https://content.competitivecyclist.com/images/items/large/OAK/OAK01UN/MATCARS24K.jpg', 'Oakley Sutro cycling sunglasses with Prizm shield lens', false, false, 153),
    ('muc-off', 'tools-accessories', 'Muc-Off Nano Tech Bike Cleaner', 'muc-off-nano-tech-bike-cleaner', 'Wash-day essential', 'The dependable spray-on cleaner for regular bike washes without overcomplicating the job.', 'A biodegradable bike cleaner designed to break down dirt while remaining safe on common bike finishes and components.', 'This is the foundation of a simple cleaning setup: rinse, spray, agitate stubborn areas and rinse again. It is easier and safer than reaching for household detergents around a good bike.', 'Any rider who washes a road or gravel bike at home.', 'Riders without access to water or anyone only needing a concentrated drivetrain degreaser.', '["Simple spray-on application","Safe for common bike surfaces","Biodegradable formula","Available in useful refill sizes"]', '["Heavy grime still needs a brush","Not a dedicated chain degreaser","Requires rinsing"]', '{"Type":"General bike cleaner","Formula":"Biodegradable Nano Tech","Application":"Spray, agitate and rinse"}', '["Routine bike washing","Post-rain clean-up","Frame care"]', '["bike cleaner","Muc-Off","washing","maintenance"]', '["Road","Gravel","MTB"]', '["All year"]', 'Everyday', 'https://eu.muc-off.com/cdn/shop/products/WEB_904-CTJ_NANO_TECH_BIKE_CLEANER_2021.jpg?v=1636041591', 'Pink bottle of Muc-Off Nano Tech Bike Cleaner', false, true, 160),
    ('muc-off', 'tools-accessories', 'Muc-Off Bio Drivetrain Cleaner', 'muc-off-bio-drivetrain-cleaner', 'Drivetrain cleaner', 'The stronger cleaner for chains, cassettes and chainrings when general bike wash is not enough.', 'A biodegradable drivetrain degreaser for chains, chainrings, cassettes and derailleurs.', 'A clean frame with a black, gritty chain is only half a job. This cuts through old lubricant and road grime quickly, making it the product to use before relubing.', 'Year-round road riders and anyone maintaining more than one drivetrain.', 'Hot-wax users following a solvent-based stripping process or riders who only need light surface cleaning.', '["Targets oily drivetrain contamination","Works on chains, rings, cassettes and derailleurs","Biodegradable formula","Can be brushed or used in a chain cleaner"]', '["Needs thorough rinsing and drying","Overuse removes fresh lubricant","Keep away from brake surfaces"]', '{"Type":"Drivetrain degreaser","Volume":"500ml","Formula":"Biodegradable"}', '["Deep drivetrain cleaning","Pre-lube preparation","Winter maintenance"]', '["degreaser","drivetrain","Muc-Off","chain cleaning"]', '["Road","Gravel","MTB"]', '["All year"]', 'Everyday', 'https://eu.muc-off.com/cdn/shop/files/Drivetrain_Cleaner_500ml_grey.png?v=1746608495', 'Muc-Off Bio Drivetrain Cleaner spray bottle', false, false, 161),
    ('muc-off', 'tools-accessories', 'Muc-Off C3 Wet Ceramic Lube', 'muc-off-c3-wet-ceramic-lube', 'Wet-weather lube', 'The long-ride chain lube for properly wet days when lighter formulas wash away too quickly.', 'A ceramic wet lube using boron nitride for durable low-friction protection in rain and mud.', 'For Irish winter riding, longevity matters more than a perfectly dry-looking chain. C3 Wet stays put through sustained rain and its pipette makes controlled application straightforward.', 'Road and gravel riders training through persistent wet weather.', 'Dry-climate riders, wax devotees or anyone unwilling to wipe the chain carefully after application.', '["Built for long wet rides","Ceramic coating for drivetrain protection","Precise pipette application","UV dye helps check coverage"]', '["Attracts more grime than a dry lube","Excess must be wiped carefully","Best applied several hours before riding"]', '{"Conditions":"Wet and muddy","Formula":"Ceramic with boron nitride","Application":"Pipette"}', '["Winter road riding","Rainy sportives","Wet gravel"]', '["wet lube","Muc-Off","chain lube","winter cycling"]', '["Road","Gravel","Cyclocross"]', '["Autumn","Winter","Spring"]', 'Premium', 'https://eu.muc-off.com/cdn/shop/products/Web_869_c3_wet_weather_cermaic_lube_50ml_2021.jpg?v=1636041487', 'Muc-Off C3 Wet Weather Ceramic chain lube', false, false, 162),
    ('muc-off', 'tools-accessories', 'Muc-Off Hydrodynamic Lube', 'muc-off-hydrodynamic-lube', 'Performance lube', 'A high-end oil-based lube for riders who want race-level smoothness without moving to wax.', 'Muc-Off''s performance chain lubricant, developed for low friction and changing conditions.', 'Hydrodynamic is for riders who care about drivetrain efficiency but still want a conventional bottle-and-chain routine. It works across more varied weather than a specialist dry race lube.', 'Performance road riders, racers and time triallists who prefer oil-based chain care.', 'Budget-focused riders, wax users or cyclists who prioritise the cleanest possible drivetrain.', '["Low-friction performance focus","Works across changeable conditions","Precise application","Suited to high-output road riding"]', '["Expensive per application","Still attracts some road contamination","Needs a clean, dry chain"]', '{"Type":"Performance chain lubricant","Conditions":"Dry to changeable","Application":"Direct to clean chain"}', '["Race preparation","Fast road riding","Time trials"]', '["performance lube","Muc-Off","drivetrain","race prep"]', '["Road","Triathlon"]', '["Spring","Summer","Autumn"]', 'Premium', 'https://eu.muc-off.com/cdn/shop/products/895-1_Hydrodynamic_Lube__GREY_2021.jpg?v=1636041617', 'Muc-Off Hydrodynamic performance chain lubricant', false, false, 163),
    ('muc-off', 'tyres-tubes', 'Muc-Off Ultimate Tubeless Setup Kit', 'muc-off-ultimate-tubeless-setup-kit', 'Tubeless starter kit', 'The easiest one-box route from tubeless-ready wheels to a complete working setup.', 'A conversion kit with rim tape, valves, seal patches and sealant in road, gravel and MTB sizes.', 'Tubeless shopping becomes confusing when tape width, valve length and sealant are all separate. Choosing the correct kit removes that friction and gets both wheels covered in one purchase.', 'Riders converting a tubeless-ready road or gravel wheelset for the first time.', 'Cyclists whose rims or tyres are not tubeless-ready, or experienced users who already own valves and tape.', '["Tape, valves, patches and sealant included","Road and gravel options for shallow or deep rims","Covers a complete wheelset","Colour-coded size choices"]', '["Correct tape width and valve length still matter","Installation can be messy","Not compatible with every rim and tyre"]', '{"Includes":"Tape, two valves, seal patches and sealant","Options":"Road/gravel shallow or deep rim kits","Requirement":"Tubeless-ready wheels and tyres"}', '["First tubeless conversion","Wheelset refresh","Road and gravel setup"]', '["tubeless kit","Muc-Off","rim tape","sealant"]', '["Road","Gravel"]', '["All year"]', 'Mid-range', 'https://eu.muc-off.com/cdn/shop/files/WebSKU-20086-Muc-Off-Ultimate-Tubeless-Setup-Kit---DH_Trail_Enduro-Collection.jpg?v=1763640789', 'Muc-Off Ultimate Tubeless Setup Kit with tape valves and sealant', false, true, 43),
    ('muc-off', 'tyres-tubes', 'Muc-Off Puncture Plug Repair Kit', 'muc-off-puncture-plug-repair-kit', 'Ride-saving tool', 'The compact backup for a tubeless puncture that sealant cannot close on its own.', 'A reusable 2-in-1 reamer and plug tool with three plug sizes stored in the handle.', 'Tubeless sealant handles small holes; this handles the bigger cut that would otherwise end the ride. It is light enough to stay in the saddle bag permanently.', 'Any road or gravel rider running tubeless tyres.', 'Tube-only riders or cyclists who already carry a dependable plug tool.', '["Compact all-in-one handle","Three plug thicknesses included","Reusable metal tool","Fast roadside repair"]', '["Does not replace inflation","Some cuts still require a tube or tyre boot","Plugging takes practice"]', '{"Tool":"2-in-1 plugger and reamer","Plugs":"Five each of thin, medium and thick","Compatibility":"Tubeless tyres"}', '["Roadside punctures","Tubeless emergency kit","Gravel repairs"]', '["tubeless repair","puncture plug","Muc-Off","ride essentials"]', '["Road","Gravel","MTB"]', '["All year"]', 'Everyday', 'https://eu.muc-off.com/cdn/shop/files/20131_-_Puncture_Plug_Repair_Kit_updated.jpg?v=1769082585', 'Muc-Off Puncture Plug Repair Kit and assorted tyre plugs', false, false, 44),
    ('muc-off', 'tyres-tubes', 'Muc-Off Road & Gravel Tubeless Sealant', 'muc-off-road-gravel-tubeless-sealant', 'Road sealant', 'A road-pressure sealant designed for modern narrow tyres rather than repackaged MTB use.', 'A water-based road and gravel sealant rated up to 110psi and designed to seal holes up to 7mm.', 'Road tubeless needs a fast-flowing formula that works at higher pressure. This is easy to add through a Presta valve and comes in ride-pack and workshop sizes.', 'Road, gravel and cyclocross riders using tubeless tyres.', 'Tube users, riders mixing sealant brands or anyone unwilling to check levels every few months.', '["Works up to 110psi","Designed to seal holes up to 7mm","Ammonia-free water-based formula","Available from 80ml pouches to bulk refills"]', '["Needs checking every three to six months","Should not be mixed with other sealants","Large cuts still need a plug"]', '{"Pressure":"Up to 110psi","Seal":"Up to 7mm claimed","Formula":"Water-based, ammonia-free"}', '["Road tubeless","Gravel tubeless","Sealant top-ups"]', '["tubeless sealant","Muc-Off","road tyres","puncture prevention"]', '["Road","Gravel","Cyclocross"]', '["All year"]', 'Everyday', 'https://eu.muc-off.com/cdn/shop/files/80ml-Road-and-Gravel_4b584c97-72b9-48a7-8fc0-715be1020f5f.jpg?v=1719492785', 'Muc-Off Road and Gravel Tubeless Sealant pouch', false, false, 45),
    ('muc-off', 'tools-accessories', 'Muc-Off Bike Protect', 'muc-off-bike-protect', 'Post-wash protection', 'The useful final step after a wet wash: disperse leftover moisture and leave vulnerable metal better protected.', 'A water-dispersing after-wash spray designed to inhibit corrosion and freshen the bike.', 'Bike Protect makes most sense through winter, when water hides in bolts and awkward junctions. A light application after drying helps finish the wash properly.', 'Year-round riders storing bikes after wet washes or salty winter roads.', 'Riders who only need frame polish or anyone unable to keep spray away from braking surfaces.', '["Disperses residual water","Helps inhibit corrosion","Useful after winter washes","Simple aerosol application"]', '["Must stay off rotors, pads and tyre tread","Not a substitute for drying","Overspray needs care"]', '{"Type":"After-wash protection spray","Volume":"500ml","Purpose":"Water dispersion and corrosion protection"}', '["Post-wash care","Winter maintenance","Storage preparation"]', '["bike protect","Muc-Off","corrosion","winter maintenance"]', '["Road","Gravel","MTB"]', '["All year","Winter"]', 'Everyday', 'https://eu.muc-off.com/cdn/shop/products/Web_909_Bike_Protect_2021_9310634e-c062-49ed-bfa4-30eb9b1af11f.jpg?v=1636041448', 'Muc-Off Bike Protect after-wash spray', false, false, 164),
    ('zwift', 'indoor-training', 'Zwift Ride with KICKR CORE 2', 'zwift-ride-with-kickr-core-2', 'Complete indoor setup', 'The simplest route to an always-ready, shareable Zwift bike without flagship smart-bike pricing.', 'An adjustable Zwift Ride frame bundled with the Wahoo KICKR CORE 2 trainer and integrated controls.', 'Buying the bundle removes the compatibility work. It arrives as a complete adjustable setup with virtual shifting, game controls and enough trainer performance for serious intervals and racing.', 'Regular indoor riders, multi-rider households and cyclists who do not want to mount an outdoor bike for every session.', 'Occasional indoor riders, athletes who need an open-platform flagship smart bike or homes without permanent floor space.', '["Complete trainer and adjustable frame bundle","Fits riders from 152cm to 198cm","Integrated Zwift controls and virtual shifting","KICKR CORE 2 provides up to 1800W and 16% gradient simulation"]', '["Large purchase and shipping cost","Zwift-first ecosystem","Needs permanent floor space and a display"]', '{"Rider":"152–198cm; 120kg maximum","Trainer":"±2% accuracy; 1800W; 16% grade","Footprint":"136 × 60.2cm"}', '["Permanent pain cave","Shared indoor bike","Zwift racing"]', '["smart bike","Zwift Ride","KICKR CORE 2","indoor cycling"]', '["Indoor","Road","Triathlon"]', '["All year","Winter"]', 'Premium', 'https://eu.zwift.com/cdn/shop/files/zwift-ride-with-kickr-core-2-all-in-one-cycling-setup.jpg?v=1756237929', 'Zwift Ride smart frame with Wahoo KICKR CORE 2 trainer', true, false, 90),
    ('zwift', 'indoor-training', 'Zwift Cog and Click Upgrade Kit', 'zwift-cog-click-upgrade-kit', 'Trainer upgrade', 'The low-cost upgrade that gives a compatible smart trainer quiet virtual gears and handlebar control.', 'A Zwift Cog V2 and wireless Click controller delivering 24 virtual gears on supported trainers.', 'For a compatible trainer, this solves cassette matching and makes virtual shifting much more accessible. It is particularly useful when several bikes share one indoor setup.', 'Owners of compatible direct-drive trainers who want Zwift virtual shifting without replacing the trainer.', 'Riders whose trainer is not on the compatibility list or cyclists who prefer mechanical cassette shifting.', '["Twenty-four silent virtual gears","Handlebar shifting and in-game controls","Adjustable chain-line positions","Quick installation on compatible trainers"]', '["Trainer compatibility must be checked first","Indoor use only","Best value is inside Zwift"]', '{"Gears":"24 virtual","Controller":"Bluetooth; CR2032; 100+ hours","Compatibility":"Selected direct-drive smart trainers"}', '["Trainer conversion","Multi-bike setup","Virtual shifting"]', '["Zwift Cog","Zwift Click","virtual shifting","trainer upgrade"]', '["Indoor"]', '["All year","Winter"]', 'Accessible', 'https://eu.zwift.com/cdn/shop/files/zwift-cog-click-2-upgrade-kit.jpg?v=1756227303', 'Zwift Cog and Click virtual shifting upgrade kit', false, true, 91)
) AS v(
  "brand_slug", "category_slug", "name", "slug", "badge", "verdict",
  "short_description", "why_recommend", "who_for", "who_skip",
  "strengths", "limitations", "specifications", "use_cases", "tags",
  "disciplines", "seasons", "price_band", "image_url", "image_alt",
  "featured", "best_value", "sort_order"
)
INNER JOIN "recommendation_brands" b ON b."slug" = v."brand_slug"
INNER JOIN "recommendation_categories" c ON c."slug" = v."category_slug"
ON CONFLICT ("slug") DO UPDATE SET
  "brand_id" = EXCLUDED."brand_id",
  "category_id" = EXCLUDED."category_id",
  "status" = EXCLUDED."status",
  "badge" = EXCLUDED."badge",
  "evidence_status" = EXCLUDED."evidence_status",
  "verdict" = EXCLUDED."verdict",
  "short_description" = EXCLUDED."short_description",
  "why_recommend" = EXCLUDED."why_recommend",
  "who_for" = EXCLUDED."who_for",
  "who_skip" = EXCLUDED."who_skip",
  "strengths" = EXCLUDED."strengths",
  "limitations" = EXCLUDED."limitations",
  "specifications" = EXCLUDED."specifications",
  "use_cases" = EXCLUDED."use_cases",
  "tags" = EXCLUDED."tags",
  "disciplines" = EXCLUDED."disciplines",
  "seasons" = EXCLUDED."seasons",
  "price_band" = EXCLUDED."price_band",
  "image_url" = EXCLUDED."image_url",
  "image_alt" = EXCLUDED."image_alt",
  "featured" = EXCLUDED."featured",
  "best_value" = EXCLUDED."best_value",
  "sort_order" = EXCLUDED."sort_order",
  "last_reviewed_at" = now(),
  "updated_at" = now();
--> statement-breakpoint
INSERT INTO "recommendation_offers" (
  "product_id", "retailer_name", "affiliate_program", "destination_url",
  "regions", "currency", "price_label", "priority", "active",
  "last_checked_at", "last_http_status"
)
SELECT
  p."id", v."retailer_name", v."affiliate_program",
  v."destination_url", v."regions"::jsonb, v."currency",
  v."price_label", 0, true, now(), 200
FROM (
  VALUES
    ('garmin-edge-1050', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=garmin-edge-1050&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fgarmin-edge-1050-gps-bike-computer', '["US"]', 'USD', 'View current price'),
    ('garmin-varia-rtl515', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=garmin-varia-rtl515&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fgarmin-varia-rtl515-rearview-radar-with-taillight', '["US"]', 'USD', 'View current price'),
    ('garmin-rally-rs110-power-pedals', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=garmin-rally-rs110-power-pedals&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fgarmin-rally-rs110-power-clipless-pedals', '["US"]', 'USD', 'View current price'),
    ('shimano-ultegra-pd-r8000-pedals', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=shimano-ultegra-pd-r8000-pedals&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fshimano-ultegra-pd-r8000-pedals', '["US"]', 'USD', 'View current price'),
    ('shimano-s-phyre-rc903-shoes', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=shimano-s-phyre-rc903-shoes&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fshimano-rc903-s-phyre-cycling-shoe-mens', '["US"]', 'USD', 'View current price'),
    ('poc-ventral-air-mips', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=poc-ventral-air-mips&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fpoc-ventral-air-mips-helmet', '["US"]', 'USD', 'View current price'),
    ('kask-protone-icon', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=kask-protone-icon&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fkask-protone-icon-helmet', '["US"]', 'USD', 'View current price'),
    ('fizik-vento-argo-r1-adaptive', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=fizik-vento-argo-r1-adaptive&u=https%3A%2F%2Fwww.competitivecyclist.com%2Ffi-zik-vento-argo-r1-adaptive-saddle', '["US"]', 'USD', 'View current price'),
    ('vittoria-corsa-pro-g2-tlr', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=vittoria-corsa-pro-g2-tlr&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fvittoria-corsa-pro-g2.0-tlr-tire', '["US"]', 'USD', 'View current price'),
    ('pirelli-p-zero-race-tlr-rs', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=pirelli-p-zero-race-tlr-rs&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fpirelli-p-zero-race-tlr-rs-tire', '["US"]', 'USD', 'View current price'),
    ('silca-mattone-seat-pack', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=silca-mattone-seat-pack&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fsilca-mattone-seat-pack', '["US"]', 'USD', 'View current price'),
    ('silca-super-secret-2-chain-lube', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=silca-super-secret-2-chain-lube&u=https%3A%2F%2Fwww.competitivecyclist.com%2Fsilca-super-secret-2.0-chain-lube', '["US"]', 'USD', 'View current price'),
    ('feedback-pro-mechanic-hd', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=feedback-pro-mechanic-hd&u=https%3A%2F%2Fwww.competitivecyclist.com%2Ffeedback-sports-pro-mechanic-hd', '["US"]', 'USD', 'View current price'),
    ('oakley-sutro-prizm', 'Competitive Cyclist', 'Competitive Cyclist — Impact', 'https://competitivecyclist.g39l.net/9VQ6AE?subId1=roadman-recommends&subId2=oakley-sutro-prizm&u=https%3A%2F%2Fwww.competitivecyclist.com%2Foakley-sutro-prizm-sunglasses', '["US"]', 'USD', 'View current price'),
    ('muc-off-nano-tech-bike-cleaner', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-nano-tech-bike-cleaner&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fnano-tech-bike-cleaner', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-bio-drivetrain-cleaner', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-bio-drivetrain-cleaner&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fbio-drivetrain-cleaner', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-c3-wet-ceramic-lube', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-c3-wet-ceramic-lube&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fc3-wet-ceramic-lube', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-hydrodynamic-lube', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-hydrodynamic-lube&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fhydrodynamic-lube', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-ultimate-tubeless-setup-kit', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-ultimate-tubeless-setup-kit&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fultimate-tubeless-setup-kit', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-puncture-plug-repair-kit', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-puncture-plug-repair-kit&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fpuncture-plug-repair-kit', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-road-gravel-tubeless-sealant', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-road-gravel-tubeless-sealant&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Froad-gravel-tubeless-sealant', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('muc-off-bike-protect', 'Muc-Off', 'Muc-Off — Impact', 'https://mucoff.sjv.io/aN6o5o?subId1=roadman-recommends&subId2=muc-off-bike-protect&u=https%3A%2F%2Feu.muc-off.com%2Fproducts%2Fbike-protect', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('zwift-ride-with-kickr-core-2', 'Zwift', 'Zwift hardware — Impact', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=zwift-ride-with-kickr-core-2&u=https%3A%2F%2Feu.zwift.com%2Fproducts%2Fzwift-ride-kickr-core-2', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('zwift-ride-with-kickr-core-2', 'Zwift US', 'Zwift hardware — Impact', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=zwift-ride-with-kickr-core-2&u=https%3A%2F%2Fus.zwift.com%2Fproducts%2Fzwift-ride-kickr-core-2', '["US"]', 'USD', 'View current price'),
    ('zwift-cog-click-upgrade-kit', 'Zwift', 'Zwift hardware — Impact', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=zwift-cog-click-upgrade-kit&u=https%3A%2F%2Feu.zwift.com%2Fproducts%2Fzwift-cog-and-click-upgrade-kit', '["IE","GB","EU"]', 'EUR', 'View current price'),
    ('zwift-cog-click-upgrade-kit', 'Zwift US', 'Zwift hardware — Impact', 'https://zwiftinc.sjv.io/qWNKAN?subId1=roadman-recommends&subId2=zwift-cog-click-upgrade-kit&u=https%3A%2F%2Fus.zwift.com%2Fproducts%2Fzwift-cog-and-click-upgrade-kit', '["US"]', 'USD', 'View current price')
) AS v(
  "product_slug", "retailer_name", "affiliate_program",
  "destination_url", "regions", "currency", "price_label"
)
INNER JOIN "recommendation_products" p ON p."slug" = v."product_slug"
WHERE NOT EXISTS (
  SELECT 1
  FROM "recommendation_offers" o
  WHERE o."product_id" = p."id"
    AND o."retailer_name" = v."retailer_name"
);
