import { SITE_ORIGIN } from "@/lib/brand-facts";

/**
 * Welcome email sent to /masters-report subscribers immediately after the
 * Beehiiv subscribe succeeds. Wired up in src/app/api/newsletter/route.ts —
 * any signup whose `source` starts with "masters-report" gets this email.
 *
 * The PDF lives at /downloads/masters-cycling-training-report-2026.pdf,
 * generated by scripts/generate-masters-report-pdf.ts from the canonical
 * MDX. Regenerate after any edit to the underlying report.
 *
 * Voice notes: written in Anthony's first person, peer-to-peer, low on
 * marketing texture, high on signal. Dark theme with a coral CTA matches
 * the squeeze page and the PDF.
 */

const PDF_PATH = "/downloads/masters-cycling-training-report-2026.pdf";
const PLATEAU_PATH = "/go";
const REPORT_HTML_PATH = "/blog/masters-cycling-training-report-2026";

export interface MastersReportWelcomeEmail {
  subject: string;
  html: string;
  text: string;
}

export function buildMastersReportWelcomeEmail(): MastersReportWelcomeEmail {
  const pdfUrl = `${SITE_ORIGIN}${PDF_PATH}`;
  const plateauUrl = `${SITE_ORIGIN}${PLATEAU_PATH}`;
  const reportUrl = `${SITE_ORIGIN}${REPORT_HTML_PATH}`;
  const logoUrl = `${SITE_ORIGIN}/images/logo-white.png`;
  const unsubscribeFooter = `${SITE_ORIGIN}/privacy`;

  const subject = "Your Masters Cycling Training Report 2026 (PDF inside)";

  const text = [
    "Thanks for grabbing the Masters Cycling Training Report 2026.",
    "",
    `Download the PDF: ${pdfUrl}`,
    "",
    "What's inside:",
    "  - What actually declines after 35, 45, 55 — and what doesn't",
    "  - The intensity distribution most masters get wrong",
    "  - Strength training: the masters-appropriate dose, programmed",
    "  - Recovery, sleep, HRV, protein, fuelling — the numbers in plain English",
    "  - Five real coaching case studies (named, with watts)",
    "  - A 12-week sample block you can run on Monday",
    "",
    "If you're not sure where you're stuck, the Plateau Diagnostic is the",
    "four-minute audit that returns a specific prescription, free:",
    plateauUrl,
    "",
    "You're not done yet.",
    "— Anthony",
    "Roadman Cycling",
    "",
    `Prefer to read it in the browser? ${reportUrl}`,
    `Privacy: ${unsubscribeFooter}`,
  ].join("\n");

  // Inlined styles only. Most mail clients strip <style> in head; this is
  // table-based dark-theme layout so it survives Gmail / Apple Mail / Outlook
  // with the look largely intact. The Bebas Neue font won't render in
  // most mail clients — fallback stack handles that gracefully.
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="x-apple-disable-message-reformatting" />
  <meta name="color-scheme" content="dark" />
  <meta name="supported-color-schemes" content="dark" />
  <title>${subject}</title>
  <style>
    @media (max-width: 600px) {
      .container { width: 100% !important; }
      .px { padding-left: 22px !important; padding-right: 22px !important; }
      h1.hero { font-size: 30px !important; line-height: 1.05 !important; }
    }
    a { color: #F16363; }
    /* Dark-mode email clients (Apple Mail) — keep our colours */
    :root { color-scheme: dark; }
  </style>
</head>
<body style="margin:0;padding:0;background:#1a1a1b;color:#FAFAFA;font-family:'Work Sans',-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;">
  <!-- Preheader: shown in inbox preview, hidden in body -->
  <div style="display:none;font-size:1px;color:#1a1a1b;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">
    The PDF is inside — what actually declines after 40, what doesn't, and the training that holds up.
  </div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#1a1a1b;">
    <tr>
      <td align="center" style="padding:32px 16px;">
        <table role="presentation" class="container" width="600" cellpadding="0" cellspacing="0" border="0" style="width:600px;max-width:600px;background:#252526;border:1px solid rgba(255,255,255,0.06);border-radius:12px;overflow:hidden;">

          <!-- Header / logo -->
          <tr>
            <td class="px" style="padding:28px 36px 12px 36px;background:#210140;border-bottom:1px solid rgba(255,255,255,0.08);">
              <img
                src="${logoUrl}"
                alt="Roadman Cycling"
                width="140"
                height="auto"
                style="display:block;width:140px;height:auto;border:0;outline:0;"
              />
            </td>
          </tr>

          <!-- Hero -->
          <tr>
            <td class="px" style="padding:36px 36px 8px 36px;">
              <p style="margin:0 0 14px 0;font-family:'Bebas Neue','Work Sans',sans-serif;color:#F16363;font-size:12px;letter-spacing:0.28em;">
                YOUR REPORT IS HERE
              </p>
              <h1 class="hero" style="margin:0 0 18px 0;font-family:'Bebas Neue','Work Sans',sans-serif;font-weight:400;font-size:38px;line-height:1;color:#FAFAFA;letter-spacing:0.01em;">
                THE MASTERS CYCLING<br/>
                <span style="color:#F16363;">TRAINING REPORT 2026</span>
              </h1>
            </td>
          </tr>

          <!-- Body copy -->
          <tr>
            <td class="px" style="padding:0 36px 8px 36px;">
              <p style="margin:0 0 14px 0;font-size:16px;line-height:1.6;color:#FAFAFA;">
                Cheers for grabbing the report.
              </p>
              <p style="margin:0 0 14px 0;font-size:16px;line-height:1.6;color:rgba(250,250,250,0.86);">
                The PDF below is the 2026 reference for training after 40 &mdash;
                informed by a 1,400+ episode podcast catalogue and the
                peer-reviewed evidence behind it. 18 sections, 40+ citations,
                five named coaching case studies, and a 12-week sample block
                you can run on Monday.
              </p>
              <p style="margin:0 0 22px 0;font-size:16px;line-height:1.6;color:rgba(250,250,250,0.86);">
                If you only have ten minutes today, read Sections 4 and 5 &mdash;
                that&rsquo;s the distribution question, which is the one most
                masters cyclists get wrong, and where the biggest gains hide.
              </p>
            </td>
          </tr>

          <!-- Primary CTA -->
          <tr>
            <td class="px" style="padding:8px 36px 28px 36px;" align="left">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td bgcolor="#F16363" style="border-radius:6px;">
                    <a
                      href="${pdfUrl}"
                      style="display:inline-block;padding:16px 28px;font-family:'Bebas Neue','Work Sans',sans-serif;font-size:16px;letter-spacing:0.12em;color:#FAFAFA;text-decoration:none;background:#F16363;border-radius:6px;font-weight:600;"
                    >
                      DOWNLOAD THE REPORT (PDF)
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin:12px 0 0 0;font-size:13px;color:rgba(250,250,250,0.55);">
                Or read it in the browser: <a href="${reportUrl}" style="color:#F16363;">roadmancycling.com</a>
              </p>
            </td>
          </tr>

          <!-- Teaser of what's inside -->
          <tr>
            <td class="px" style="padding:0 36px 8px 36px;">
              <p style="margin:0 0 10px 0;font-family:'Bebas Neue','Work Sans',sans-serif;color:#F16363;font-size:11px;letter-spacing:0.28em;">
                WHAT&rsquo;S INSIDE
              </p>
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.06);font-size:15px;color:#FAFAFA;">
                    <span style="color:#F16363;font-weight:600;">&middot;</span> What actually declines after 35, 45, 55 &mdash; and what doesn&rsquo;t
                  </td>
                </tr>
                <tr>
                  <td style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.06);font-size:15px;color:#FAFAFA;">
                    <span style="color:#F16363;font-weight:600;">&middot;</span> The intensity dose that still works after 40 &mdash; and the one that&rsquo;s wasted
                  </td>
                </tr>
                <tr>
                  <td style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.06);font-size:15px;color:#FAFAFA;">
                    <span style="color:#F16363;font-weight:600;">&middot;</span> Strength training: why it&rsquo;s non-negotiable, with the exact programme
                  </td>
                </tr>
                <tr>
                  <td style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.06);font-size:15px;color:#FAFAFA;">
                    <span style="color:#F16363;font-weight:600;">&middot;</span> Perimenopause and menopause &mdash; the section nobody writes properly
                  </td>
                </tr>
                <tr>
                  <td style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.06);font-size:15px;color:#FAFAFA;">
                    <span style="color:#F16363;font-weight:600;">&middot;</span> Five named case studies &mdash; riders 41 to 52, real numbers, real plans
                  </td>
                </tr>
                <tr>
                  <td style="padding:8px 0;font-size:15px;color:#FAFAFA;">
                    <span style="color:#F16363;font-weight:600;">&middot;</span> A 12-week block you can run on Monday
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Secondary CTA -->
          <tr>
            <td class="px" style="padding:28px 36px 8px 36px;border-top:1px solid rgba(255,255,255,0.06);">
              <p style="margin:18px 0 12px 0;font-family:'Bebas Neue','Work Sans',sans-serif;color:#F16363;font-size:11px;letter-spacing:0.28em;">
                ONE MORE THING
              </p>
              <p style="margin:0 0 14px 0;font-size:15px;line-height:1.6;color:rgba(250,250,250,0.86);">
                If you&rsquo;re reading the report and you already know which
                section applies to you &mdash; you&rsquo;re plateaued, you&rsquo;ve
                tried things, the numbers aren&rsquo;t moving &mdash; the
                <strong style="color:#FAFAFA;">Plateau Diagnostic</strong> is
                the four-minute audit that returns a specific prescription. Free.
                Built off the same coaching framework as the report.
              </p>
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="border:1px solid #F16363;border-radius:6px;">
                    <a
                      href="${plateauUrl}"
                      style="display:inline-block;padding:13px 22px;font-family:'Bebas Neue','Work Sans',sans-serif;font-size:14px;letter-spacing:0.12em;color:#F16363;text-decoration:none;font-weight:600;"
                    >
                      RUN THE PLATEAU DIAGNOSTIC &rarr;
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Signoff -->
          <tr>
            <td class="px" style="padding:28px 36px 32px 36px;">
              <p style="margin:0 0 6px 0;font-size:15px;line-height:1.6;color:rgba(250,250,250,0.86);">
                You&rsquo;re not done yet.
              </p>
              <p style="margin:0;font-size:15px;line-height:1.6;color:#FAFAFA;">
                &mdash; Anthony<br/>
                <span style="color:rgba(250,250,250,0.55);font-size:13px;">Roadman Cycling</span>
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td class="px" style="padding:18px 36px 24px 36px;background:#1a1a1b;border-top:1px solid rgba(255,255,255,0.06);">
              <p style="margin:0;font-size:12px;line-height:1.6;color:rgba(250,250,250,0.45);">
                Roadman Cycling &middot; You&rsquo;re receiving this because you asked for the Masters Cycling Training Report 2026 at roadmancycling.com/masters-report. One-click unsubscribe is in every Saturday Spin issue. <a href="${SITE_ORIGIN}/privacy" style="color:rgba(250,250,250,0.6);text-decoration:underline;">Privacy</a>.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  return { subject, html, text };
}
