import { MDXRemote } from "next-mdx-remote/rsc";
import { methodMdxComponents } from "./MethodMDXComponents";
import { PROTOCOL_BODIES } from "@/lib/method/protocol-content";
import type { MethodModule } from "@/lib/method/modules";

interface MethodProtocolProps {
  module: MethodModule;
}

/**
 * Server-side MDX renderer for a Method module protocol.
 *
 * Protocol bodies are inlined at build time in `protocol-content.ts`
 * (generated by `npm run method:protocols` from the MDX in
 * `content/method/protocols/`). We look the body up by slug and hand it
 * to next-mdx-remote/rsc with the Method-themed component map.
 *
 * Reading from an in-memory map — rather than `fs.readFile`-ing a dynamic
 * path at request time — keeps Next's file tracer from bundling the whole
 * ~46MB content/ directory into this route's serverless function.
 *
 * If a slug has no body (protocol not yet written) we fall back to a quiet
 * placeholder — the module data drives the rest of the page, the protocol
 * is one surface among several.
 */
export function MethodProtocol({ module }: MethodProtocolProps) {
  const body = PROTOCOL_BODIES[module.slug];
  if (!body) {
    return <ProtocolFallback minutes={module.estimatedReadMinutes} />;
  }

  return (
    <section
      aria-label="Protocol"
      className="rounded-xl border border-white/10 bg-charcoal/60 p-6 md:p-10"
    >
      <p className="font-heading text-coral text-[11px] tracking-[0.3em] uppercase mb-6">
        Protocol · {module.estimatedReadMinutes} min read
      </p>
      <div className="prose-method">
        <MDXRemote source={body} components={methodMdxComponents} />
      </div>
    </section>
  );
}

function ProtocolFallback({ minutes }: { minutes: number }) {
  return (
    <section className="rounded-xl border border-white/10 bg-charcoal/60 p-6 md:p-8 prose-method">
      <h2 className="font-heading uppercase tracking-wider text-2xl mb-4">
        Protocol
      </h2>
      <p className="text-foreground-muted leading-relaxed mb-3">
        Written protocol for this module is being finalised. When it
        publishes, you&apos;ll see the full breakdown here — the work, the why,
        and how it sits inside the twelve-week build.
      </p>
      <p className="text-sm text-foreground-muted">
        Approximate read: {minutes} min when published.
      </p>
    </section>
  );
}
