/**
 * Guest profile overrides — curated, verified entity data for featured
 * podcast guests.
 *
 * Populated by hand from public sources (Wikipedia, official team pages,
 * verified social profiles). Every URL here has been verified via live
 * WebSearch — do NOT add entries without verifying the profile exists
 * and belongs to the right person. Inventing social URLs is the Google
 * Knowledge Graph equivalent of the AggregateRating footgun: it looks
 * authoritative, it fails audit trivially.
 *
 * The SEO value:
 *   - `sameAs` is the single strongest signal for Knowledge Graph entity
 *     disambiguation. It tells Google "this Greg LeMond is THE Greg
 *     LeMond (matching his Wikipedia entry, his official site, his
 *     Instagram), not some other person with the same name."
 *   - `worksFor` anchors the guest to a recognised org (SportsTeam or
 *     CollegeOrUniversity), which powers sitelinks and career-context
 *     panels in SERPs.
 *   - `image` surfaces a verified headshot in the Knowledge Panel.
 *
 * Coverage target: the 12 featured experts shown on /about. Easy to
 * extend — add new entries keyed by the guest's slug (the same slug
 * generated by `slugify()` in guests.ts).
 */

export interface GuestProfileOverride {
  /** Absolute URL of a headshot. Prefer a verified public photo. */
  image?: string;
  /**
   * Canonical "same as" URLs for Knowledge Graph entity disambiguation.
   * Order suggests priority — Wikipedia / Wikidata first, then official
   * personal site, then verified social profiles.
   */
  sameAs?: string[];
  /**
   * Organisation the guest currently works for or is affiliated with.
   * Used to populate schema.org `worksFor` with a proper type —
   * SportsTeam for pros, CollegeOrUniversity for academics, Organization
   * for everyone else.
   */
  worksFor?: {
    name: string;
    type: "SportsTeam" | "CollegeOrUniversity" | "Organization";
    url?: string;
  };
  /**
   * Optional longer-form description, replacing the auto-generated
   * "X — expert guest on The Roadman Cycling Podcast" fallback for
   * higher-profile entries.
   */
  description?: string;
  /**
   * Blog slugs that explicitly feature or cite this guest. Surfaced on
   * the /guests/[slug] page as a "Featured in" section. Creates a
   * bidirectional entity↔content link from the guest page to the
   * articles that reference them.
   */
  featuredArticles?: string[];
}

/**
 * Slug → override map. Slugs match the output of `slugify()` in
 * `src/lib/guests.ts` applied to the canonical name after alias
 * normalisation (so "Professor Stephen Seiler" → "Stephen Seiler"
 * → slug `stephen-seiler`).
 */
export const GUEST_PROFILE_OVERRIDES: Record<string, GuestProfileOverride> = {
  "greg-lemond": {
    description:
      "Three-time Tour de France winner (1986, 1989, 1990) and two-time UCI Road World Champion. The only American man to win the Tour de France.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Greg_LeMond",
      "https://www.wikidata.org/wiki/Q312697",
      "https://www.instagram.com/greg.lemond/",
      "https://www.facebook.com/greglemond/",
      "https://www.procyclingstats.com/rider/greg-lemond",
    ],
  },

  "stephen-seiler": {
    description:
      "Professor of Sport Science at the University of Agder, Norway. Exercise physiologist who coined the polarised-training model and the 80/20 rule of intensity distribution.",
    worksFor: {
      name: "University of Agder",
      type: "CollegeOrUniversity",
      url: "https://www.uia.no/english/",
    },
    sameAs: [
      "https://x.com/StephenSeiler",
      "https://www.uia.no/english/about-uia/employees/stephens/",
      "https://www.linkedin.com/in/stephen-seiler-668202a/",
      "https://www.researchgate.net/profile/Stephen-Seiler",
    ],
    featuredArticles: [
      "every-roadman-episode-with-stephen-seiler",
      "polarised-vs-sweet-spot-training",
      "what-cycling-podcasts-got-wrong-about-polarised-training",
    ],
  },

  "tim-spector": {
    description:
      "British epidemiologist, Professor of Genetic Epidemiology at King's College London, and co-founder of the nutrition-science company ZOE. Author of Spoon-Fed, The Diet Myth and Food for Life.",
    worksFor: {
      name: "ZOE",
      type: "Organization",
      url: "https://zoe.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Tim_Spector",
      "https://www.instagram.com/tim.spector/",
      "https://x.com/timspector",
      "https://uk.linkedin.com/in/timspector",
      "https://zoe.com/learn/tim-spector",
    ],
  },

  "lachlan-morton": {
    description:
      "Australian professional cyclist for EF Education–EasyPost, ultra-distance and alt-racing pioneer. Former Everesting world record holder, 2024 Unbound Gravel 200 winner, Great Divide ultra-endurance rider.",
    worksFor: {
      name: "EF Education–EasyPost",
      type: "SportsTeam",
      url: "https://www.efprocycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Lachlan_Morton",
      "https://www.efprocycling.com/our-team/lachlan-morton/",
      "https://www.procyclingstats.com/rider/lachlan-morton",
    ],
  },

  "joe-friel": {
    description:
      "Endurance sports coach and author. Wrote The Cyclist's Training Bible (now in its fifth edition), co-founded TrainingPeaks, and served as chairman of the USA Triathlon National Coaching Commission.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Joe_Friel",
      "https://joefrieltraining.com/",
    ],
    featuredArticles: [
      "how-to-periodise-cycling-season",
      "how-to-structure-cycling-training-plan",
      "masters-cyclist-guide-getting-faster-after-40",
    ],
  },

  "ben-healy": {
    description:
      "Irish professional cyclist for EF Education–EasyPost. Winner of stage 6 of the 2025 Tour de France, and later wore the yellow jersey after stage 10 — the first Irish rider in yellow since Stephen Roche in 1987.",
    worksFor: {
      name: "EF Education–EasyPost",
      type: "SportsTeam",
      url: "https://www.efprocycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Ben_Healy_(cyclist)",
      "https://www.efprocycling.com/our-team/ben-healy/",
      "https://www.instagram.com/benhealy._/",
      "https://www.procyclingstats.com/rider/ben-healy",
    ],
  },

  "michael-matthews": {
    description:
      "Australian professional road and track cyclist for Team Jayco–AlUla. 2010 U23 Road Race World Champion, Tour de France green jersey winner, and Grand Tour stage winner across all three Grand Tours.",
    worksFor: {
      name: "Team Jayco–AlUla",
      type: "SportsTeam",
      url: "https://greenedgecycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Michael_Matthews_(cyclist)",
      "https://www.procyclingstats.com/rider/michael-matthews",
    ],
  },

  "dan-bigham": {
    description:
      "British aerodynamics engineer, former UCI Hour Record holder (55.548km, 2022), and Head of Engineering for Red Bull–Bora–Hansgrohe. Won multiple track cycling national, European and world championship medals.",
    worksFor: {
      name: "Red Bull–Bora–Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Daniel_Bigham",
      "https://www.britishcycling.org.uk/gbcyclingteam/bio/Dan_Bigham",
    ],
  },

  "dan-lorang": {
    description:
      "German performance coach. Long-time triathlon coach to Jan Frodeno, Anne Haug and Lucy Charles-Barclay; Head of Performance at Red Bull–Bora–Hansgrohe from 2017 through the 2025 season. Now Head of Endurance Sports at Red Bull's Athletic Performance Centre.",
    worksFor: {
      name: "Red Bull — Athletic Performance Centre",
      type: "Organization",
    },
    sameAs: ["https://de.linkedin.com/in/dan-lorang-33296319"],
    featuredArticles: [
      "every-roadman-episode-with-dan-lorang",
      "ironman-bike-training-plan-16-weeks",
      "bike-leg-of-triathlon-why-age-groupers-get-it-wrong",
    ],
  },

  "john-wakefield": {
    description:
      "Cycling coach, bike fitter and Director of Development at Red Bull–Bora–Hansgrohe. Runs the Science to Sport Performance Laboratory in Girona, Spain. Previously Performance Co-ordinator and Coach at UAE Team Emirates over four seasons.",
    worksFor: {
      name: "Red Bull–Bora–Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: [
      "https://www.linkedin.com/in/john-wakefield-a7449785/",
      "https://www.trainingpeaks.com/coach/john-sciencetosport",
    ],
  },

  "david-dunne": {
    description:
      "Performance nutritionist and researcher. PhD in Behaviour Change, Design Thinking, and Technology Innovation in Sports Nutrition from Liverpool John Moores University. IOC alumnus. Co-founder and CEO of Hexis, a personalised sports-nutrition platform; has worked with athletes across World Tour cycling, Premier League, NBA, Super League and Ryder Cup Team Europe.",
    worksFor: {
      name: "Hexis",
      type: "Organization",
      url: "https://www.hexis.live",
    },
    sameAs: [
      "https://www.researchgate.net/profile/David-Dunne-9",
      "https://www.hexis.live/blog/meet-the-team-david-dunne",
    ],
  },

  "rosa-kloser": {
    description:
      "German professional gravel and road cyclist, 2024 Unbound Gravel 200 winner and 2025 German gravel national champion. Races both as a gravel privateer and for the CANYON//SRAM zondacrypto road team. PhD researcher in green shipping at Copenhagen Business School.",
    worksFor: {
      name: "CANYON//SRAM zondacrypto",
      type: "SportsTeam",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Rosa_Kl%C3%B6ser",
      "https://www.canyon.com/en-us/blog-content/athletes/rosa-kloser-the-new-fast/b19122025.html",
    ],
  },
};

/** Look up overrides for a guest by slug. Returns undefined if no curated data. */
export function getGuestProfileOverride(
  slug: string,
): GuestProfileOverride | undefined {
  return GUEST_PROFILE_OVERRIDES[slug];
}
