/**
 * Guest profile overrides $€” curated, verified entity data for featured
 * podcast guests.
 *
 * Populated by hand from public sources (Wikipedia, official team pages,
 * verified social profiles). Every URL here has been verified via live
 * WebSearch $€” do NOT add entries without verifying the profile exists
 * and belongs to the right person. Inventing social URLs is the Google
 * Knowledge Graph equivalent of the AggregateRating footgun: it looks
 * authoritative, it fails audit trivially.
 *
 * The SEO value:
 *   - `sameAs` is the single strongest signal for Knowledge Graph entity
 *     disambiguation. It tells Google "this Greg LeMond is THE Greg
 *     LeMond (matching his Wikipedia entry, his official site, his
 *     Instagram), not some other person with the same name."
 *   - `worksFor` anchors the guest to a recognised org (SportsTeam or
 *     CollegeOrUniversity), which powers sitelinks and career-context
 *     panels in SERPs.
 *   - `image` surfaces a verified headshot in the Knowledge Panel.
 *
 * Coverage target: the 12 featured experts shown on /about. Easy to
 * extend $€” add new entries keyed by the guest's slug (the same slug
 * generated by `slugify()` in guests.ts).
 */

export interface GuestProfileOverride {
  /** Absolute URL of a headshot. Prefer a verified public photo. */
  image?: string;
  /**
   * Canonical "same as" URLs for Knowledge Graph entity disambiguation.
   * Order suggests priority $€” Wikipedia / Wikidata first, then official
   * personal site, then verified social profiles.
   */
  sameAs?: string[];
  /**
   * Organisation the guest currently works for or is affiliated with.
   * Used to populate schema.org `worksFor` with a proper type $€”
   * SportsTeam for pros, CollegeOrUniversity for academics, Organization
   * for everyone else.
   */
  worksFor?: {
    name: string;
    type: "SportsTeam" | "CollegeOrUniversity" | "Organization";
    url?: string;
  };
  /**
   * Optional longer-form description, replacing the auto-generated
   * "X $€” expert guest on The Roadman Cycling Podcast" fallback for
   * higher-profile entries.
   */
  description?: string;
  /**
   * Blog slugs that explicitly feature or cite this guest. Surfaced on
   * the /guests/[slug] page as a "Featured in" section. Creates a
   * bidirectional entity$†”content link from the guest page to the
   * articles that reference them.
   */
  featuredArticles?: string[];
  /**
   * Long-form "why this person matters in cycling" paragraph rendered
   * as visible content under the hero. Gives entity context that goes
   * beyond a one-line credential $€” what they did, why it changed the
   * sport, who they coached, what they invented. AEO/SGE-friendly:
   * the literal answer to "who is X?" / "why is X famous?" sits on
   * the page Google can quote.
   */
  whyMatters?: string;
  /**
   * Bullet list of the major ideas this guest is known for in the
   * cycling world. Each item should be a short, citable claim
   * (8-25 words) $€” the kind of thing an LLM can pull as an answer.
   */
  keyIdeas?: string[];
  /**
   * Optional list of related topic hub slugs to surface under the
   * guest. Falls back to the auto-derived pillar$†’topic mapping when
   * absent.
   */
  relatedHubs?: string[];
}

/**
 * Slug $†’ override map. Slugs match the output of `slugify()` in
 * `src/lib/guests.ts` applied to the canonical name after alias
 * normalisation (so "Professor Stephen Seiler" $†’ "Stephen Seiler"
 * $†’ slug `stephen-seiler`).
 */
export const GUEST_PROFILE_OVERRIDES: Record<string, GuestProfileOverride> = {
  "greg-lemond": {
    description:
      "Three-time Tour de France winner (1986, 1989, 1990) and two-time UCI Road World Champion. The only American man to win the Tour de France.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Greg_LeMond",
      "https://www.wikidata.org/wiki/Q312697",
      "https://www.instagram.com/greg.lemond/",
      "https://www.facebook.com/greglemond/",
      "https://www.procyclingstats.com/rider/greg-lemond",
    ],
    whyMatters:
      "Greg LeMond is the only American man to win the Tour de France and remains one of the most influential riders in the sport's history. His 1989 Tour victory by 8 seconds $€” won on the final-day Champs-Ã‰lysÃ©es time trial using aero bars and a Scott aerodynamic position the peloton had dismissed $€” is the most famous margin in cycling. He pioneered modern training-by-power, was an early adopter of wind-tunnel work, and has spent the post-EPO decades as one of the sport's most credible voices on doping, governance, and what clean riders are physiologically capable of. Every conversation about pro cycling history runs through him.",
    keyIdeas: [
      "Won the 1989 Tour de France by 8 seconds $€” the smallest margin in Tour history $€” using aero bars on the final time trial.",
      "First non-European to win the Tour, opened the sport to a global generation of riders.",
      "Early advocate for power-based training and wind-tunnel testing decades before the World Tour standardised both.",
      "Outspoken, evidence-based critic of EPO-era and Armstrong-era doping when it cost him sponsorships and friendships.",
      "Shot in 1987 in a hunting accident, returned to win two more Tours $€” a comeback case study cited across endurance sport.",
    ],
    relatedHubs: ["cycling-coaching", "cycling-training-plans"],
  },

  "stephen-seiler": {
    description:
      "Professor of Sport Science at the University of Agder, Norway. Exercise physiologist who coined the polarised-training model and the 80/20 rule of intensity distribution.",
    worksFor: {
      name: "University of Agder",
      type: "CollegeOrUniversity",
      url: "https://www.uia.no/english/",
    },
    sameAs: [
      "https://x.com/StephenSeiler",
      "https://www.uia.no/english/about-uia/employees/stephens/",
      "https://www.linkedin.com/in/stephen-seiler-668202a/",
      "https://www.researchgate.net/profile/Stephen-Seiler",
    ],
    featuredArticles: [
      "every-roadman-episode-with-stephen-seiler",
      "polarised-vs-sweet-spot-training",
      "what-cycling-podcasts-got-wrong-about-polarised-training",
    ],
    whyMatters:
      "Stephen Seiler is the exercise physiologist who, more than any other researcher, defined how modern endurance athletes structure their training. Working from his lab at the University of Agder, he documented that elite athletes across cycling, rowing, cross-country skiing and running converge on the same intensity distribution $€” roughly 80% easy, 20% hard, with very little time in the middle. That observation is now known as polarised training and the 80/20 rule, and it is the framework Roadman builds every training conversation on.",
    keyIdeas: [
      "Polarised training: ~80% of sessions at low intensity, ~20% at high intensity, very little time in the threshold/tempo grey zone.",
      "Elite endurance athletes across disciplines converge on the same intensity distribution $€” it is not a coaching opinion but a measured pattern.",
      "The biggest single mistake amateurs make is riding their easy days too hard, which compromises the quality of their hard days.",
      "Long, slow distance is the irreplaceable foundation $€” high-intensity work without an aerobic base produces short-lived gains.",
      "Heart rate, RPE, and lactate at sub-2 mmol/L are all reliable markers for genuine Zone 2 $€” power alone misses the day-to-day variation.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "tim-spector": {
    description:
      "British epidemiologist, Professor of Genetic Epidemiology at King's College London, and co-founder of the nutrition-science company ZOE. Author of Spoon-Fed, The Diet Myth and Food for Life.",
    worksFor: {
      name: "ZOE",
      type: "Organization",
      url: "https://zoe.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Tim_Spector",
      "https://www.instagram.com/tim.spector/",
      "https://x.com/timspector",
      "https://uk.linkedin.com/in/timspector",
      "https://zoe.com/learn/tim-spector",
    ],
    whyMatters:
      "Tim Spector is one of the most-cited researchers in nutrition science globally. His work on the gut microbiome, twin studies, and personalised nutrition through ZOE has reframed how endurance athletes think about food $€” moving the conversation away from generic macros and toward individual metabolic response, fibre diversity, and the gut as a performance organ. For cyclists chasing the last 2-3% of body composition or trying to fix mid-ride GI distress, his work is the most credible starting point.",
    keyIdeas: [
      "Individual metabolic response to identical foods varies enormously $€” population-level guidelines miss what actually works for a given athlete.",
      "Gut microbiome diversity, driven by 30+ different plant foods per week, predicts both general health and recovery markers in athletes.",
      "Ultra-processed foods drive the majority of negative health outcomes regardless of total calories or macros.",
      "Continuous glucose monitoring exposes how badly amateur athletes mistime carbohydrate intake around training.",
      "The fibre and polyphenol content of recovery meals matters as much as the protein dose for long-term adaptation.",
    ],
    relatedHubs: ["cycling-nutrition", "cycling-weight-loss"],
  },

  "lachlan-morton": {
    description:
      "Australian professional cyclist for EF Education$€“EasyPost, ultra-distance and alt-racing pioneer. Former Everesting world record holder, 2024 Unbound Gravel 200 winner, Great Divide ultra-endurance rider.",
    worksFor: {
      name: "EF Education$€“EasyPost",
      type: "SportsTeam",
      url: "https://www.efprocycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Lachlan_Morton",
      "https://www.efprocycling.com/our-team/lachlan-morton/",
      "https://www.procyclingstats.com/rider/lachlan-morton",
    ],
    whyMatters:
      "Lachlan Morton is the World Tour rider who proved you can race the Tour de France in July, set the Great Divide bikepacking record, and win Unbound Gravel $€” all in the same career. He has redefined what a pro cyclist's calendar can look like, championed alt-racing as a serious discipline, and become the public face of the link between ultra-endurance riding and World Tour fitness. For amateurs trying to figure out how to balance long days, racing, and adventure on the same engine, he is the model.",
    keyIdeas: [
      "Ultra-distance volume and World Tour racing fitness are not in conflict $€” they reinforce each other when periodised properly.",
      "Alt-racing (gravel, ultra, FKT attempts) is now a legitimate parallel career path, not a downshift from road racing.",
      "Mental durability on multi-day rides is built by spending genuine time alone on the bike, not by training plan structure alone.",
      "Pacing for ultra is closer to Zone 2 discipline than to threshold work $€” the riders who blow up are the ones who race the first half.",
      "Equipment choices for ultra (tyres, lighting, bag setup) matter more for finish-line performance than chasing 5W of aero gain.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-recovery"],
  },

  "joe-friel": {
    description:
      "Endurance sports coach and author. Wrote The Cyclist's Training Bible (now in its fifth edition), co-founded TrainingPeaks, and served as chairman of the USA Triathlon National Coaching Commission.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Joe_Friel",
      "https://joefrieltraining.com/",
    ],
    featuredArticles: [
      "how-to-periodise-cycling-season",
      "how-to-structure-cycling-training-plan",
      "masters-cyclist-guide-getting-faster-after-40",
    ],
    whyMatters:
      "Joe Friel wrote The Cyclist's Training Bible $€” the book that taught a generation of amateur cyclists how to think about periodisation, training stress, and the structure of a season. Co-founder of TrainingPeaks and former chairman of the USA Triathlon National Coaching Commission, he is the bridge between sports science and the home-trainer cyclist trying to peak for one event a year. Most modern amateur coaching software still leans on his vocabulary: periodisation, A/B/C races, base, build, peak, recovery weeks.",
    keyIdeas: [
      "Periodisation: structure your year into base, build, peak, race, and transition phases $€” each with a different physiological focus.",
      "Train your weakness, race your strength $€” the off-season is for fixing limiters, the in-season is for sharpening what already works.",
      "Recovery weeks every 3-4 weeks are not optional $€” they are the mechanism that allows training stress to convert to fitness.",
      "Heart rate zones are still the most accessible intensity tool for amateurs, and pair well with power for the riders who have both.",
      "After 50, the priorities shift: more strength work, slightly fewer high-intensity sessions, longer recovery between hard days.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training", "cycling-coaching"],
  },

  "ben-healy": {
    description:
      "Irish professional cyclist for EF Education$€“EasyPost. Winner of stage 6 of the 2025 Tour de France, and later wore the yellow jersey after stage 10 $€” the first Irish rider in yellow since Stephen Roche in 1987.",
    worksFor: {
      name: "EF Education$€“EasyPost",
      type: "SportsTeam",
      url: "https://www.efprocycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Ben_Healy_(cyclist)",
      "https://www.efprocycling.com/our-team/ben-healy/",
      "https://www.instagram.com/benhealy._/",
      "https://www.procyclingstats.com/rider/ben-healy",
    ],
    whyMatters:
      "Ben Healy is the Irish EF Education$€“EasyPost rider who became the first Irishman in the yellow jersey since Stephen Roche in 1987 after his stage 6 win at the 2025 Tour de France. He represents a generation of riders who blend long-range attacking with one-day Classics aptitude $€” and his rise has reshaped how the next wave of Irish riders think about turning pro through a domestic and continental development pathway rather than waiting on a national-team conveyor belt.",
    keyIdeas: [
      "The modern attacking puncheur model: confident on rolling parcours, capable of solo wins from 50km out.",
      "A development pathway through domestic UK/Irish racing into a continental team is now a viable route to the World Tour.",
      "Race weight matters less than power durability across multiple climbs in the final hour $€” a different optimisation than 1990s GC riders.",
      "Mental approach to long breakaways: commit early, ride your own threshold, ignore the gap until 10km to go.",
      "Irish cycling now has a structural pipeline $€” coaches, sponsors, junior racing $€” that was missing in the post-Roche decades.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training"],
  },

  "michael-matthews": {
    description:
      "Australian professional road and track cyclist for Team Jayco$€“AlUla. 2010 U23 Road Race World Champion, Tour de France green jersey winner, and Grand Tour stage winner across all three Grand Tours.",
    worksFor: {
      name: "Team Jayco$€“AlUla",
      type: "SportsTeam",
      url: "https://greenedgecycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Michael_Matthews_(cyclist)",
      "https://www.procyclingstats.com/rider/michael-matthews",
    ],
    whyMatters:
      "Michael Matthews is one of the most consistent stage-race sprinters of his generation: 2010 U23 World Champion, multiple Tour de France stage wins, Tour points jersey wearer, and a Grand Tour stage winner across all three. His career is a case study in adapting a sprint engine to a punchy stage-racing parcours $€” useful reading for any amateur trying to translate raw power into actual race finishes.",
    keyIdeas: [
      "A sprint career built on punchy finishes is more sustainable than chasing pure flat bunch sprints.",
      "Stage racing requires you to defend your fitness across three weeks $€” the riders who fade are the ones who under-recover in week one.",
      "Sprint training in the gym matters: explosive lifts and plyometrics translate directly to closing speed.",
      "Reading the finish $€” wind, road furniture, lead-out trains $€” wins more sprints than raw watts.",
      "Recovery between stages is mostly about sleep, fuelling within 30 minutes of the line, and protecting the next morning's intensity.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training"],
  },

  "dan-bigham": {
    description:
      "British aerodynamics engineer, former UCI Hour Record holder (55.548km, 2022), and Head of Engineering for Red Bull$€“Bora$€“Hansgrohe. Won multiple track cycling national, European and world championship medals.",
    worksFor: {
      name: "Red Bull$€“Bora$€“Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Daniel_Bigham",
      "https://www.britishcycling.org.uk/gbcyclingteam/bio/Dan_Bigham",
    ],
    whyMatters:
      "Dan Bigham is the British engineer-rider who held the UCI Hour Record at 55.548km in 2022 and now leads engineering at Red Bull$€“Bora$€“Hansgrohe. He is one of a small group of people who can talk credibly about both sides of the marginal-gains conversation: the wind-tunnel physics, and what it actually feels like to hold an aero position at threshold for an hour. His work on time-trial position, equipment selection, and pacing strategy has shaped how the modern peloton approaches every TT stage.",
    keyIdeas: [
      "Aero gains are real, but only after you have hit your achievable position $€” fit comes before kit.",
      "Time-trial pacing is a power-based problem: even-pace at the highest sustainable wattage, with course-aware adjustments for wind and gradient.",
      "The Hour Record is the cleanest aerodynamic test in cycling $€” no team tactics, no draft, just position and equipment.",
      "Most amateurs leave 20-40W on the table at the same FTP by riding a position that compromises them aerodynamically.",
      "Engineering rigor $€” measure, hypothesise, test, iterate $€” is more valuable in a TT programme than in any other discipline of cycling.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "dan-lorang": {
    description:
      "Luxembourgish performance coach. Long-time triathlon coach to Jan Frodeno, Anne Haug and Lucy Charles-Barclay; Head of Performance at Red Bull$€“Bora$€“Hansgrohe since 2017, announced in April 2026 that he will leave at the end of the 2026 season.",
    worksFor: {
      name: "Red Bull$€“Bora$€“Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: ["https://de.linkedin.com/in/dan-lorang-33296319"],
    featuredArticles: [
      "every-roadman-episode-with-dan-lorang",
      "ironman-bike-training-plan-16-weeks",
      "bike-leg-of-triathlon-why-age-groupers-get-it-wrong",
    ],
    whyMatters:
      "Dan Lorang is one of the most respected coaches in endurance sport $€” the long-time coach to triathlon greats Jan Frodeno, Anne Haug, and Lucy Charles-Barclay, and Head of Performance at Red Bull$€“Bora$€“Hansgrohe since 2017. He is the rare coach who has produced Ironman world champions and Grand Tour stage winners using the same underlying principles. His public work on training-load management, polarised intensity, and the long-arc development of an athlete has influenced how the smarter end of the amateur world structures their season.",
    keyIdeas: [
      "Long-term athlete development trumps short-term peaking $€” the best athletes are the ones who improve year-on-year for a decade.",
      "Polarised intensity distribution applies to both Ironman triathletes and Grand Tour riders $€” the principles cross disciplines.",
      "Training load is best managed by listening to the athlete daily, not by following a plan in spite of the body's signals.",
      "Strength work is non-negotiable for endurance athletes over 30 $€” durability prevents the late-season collapse.",
      "The bike leg of a triathlon is paced for the run that follows, not as a standalone TT $€” most age-groupers ignore this and fade in the marathon.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans", "triathlon-cycling"],
  },

  "john-wakefield": {
    description:
      "Cycling coach, bike fitter and Director of Coaching & Sports Science at Red Bull$€“Bora$€“Hansgrohe. Runs the Science to Sport Performance Laboratory in Girona, Spain. Previously Performance Co-ordinator and Coach at UAE Team Emirates over four seasons.",
    worksFor: {
      name: "Red Bull$€“Bora$€“Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: [
      "https://www.linkedin.com/in/john-wakefield-a7449785/",
      "https://www.trainingpeaks.com/coach/john-sciencetosport",
    ],
  },

  "david-dunne": {
    description:
      "Performance nutritionist and researcher. PhD in Behaviour Change, Design Thinking, and Technology Innovation in Sports Nutrition from Liverpool John Moores University. IOC alumnus. Co-founder and CEO of Hexis, a personalised sports-nutrition platform; has worked with athletes across World Tour cycling, Premier League, NBA, Super League and Ryder Cup Team Europe.",
    worksFor: {
      name: "Hexis",
      type: "Organization",
      url: "https://www.hexis.live",
    },
    sameAs: [
      "https://www.researchgate.net/profile/David-Dunne-9",
      "https://www.hexis.live/blog/meet-the-team-david-dunne",
    ],
  },

  "rosa-kloser": {
    description:
      "German professional gravel and road cyclist, 2024 Unbound Gravel 200 winner and 2025 German gravel national champion. Races both as a gravel privateer and for the CANYON//SRAM zondacrypto road team. PhD researcher in green shipping at Copenhagen Business School.",
    worksFor: {
      name: "CANYON//SRAM zondacrypto",
      type: "SportsTeam",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Rosa_Kl%C3%B6ser",
      "https://www.canyon.com/en-us/blog-content/athletes/rosa-kloser-the-new-fast/b19122025.html",
    ],
    whyMatters:
      "Rosa KlÃ¶ser is a model for the modern dual-discipline rider: a UCI Women's WorldTour rider for CANYON//SRAM zondacrypto on the road, and a winner of the 2024 Unbound Gravel 200 $€” the most prestigious privateer gravel race in the world. She combines that schedule with PhD research at Copenhagen Business School. For amateurs juggling life, work, and a full racing calendar, she is the proof that you can race seriously across disciplines without compromising either.",
    keyIdeas: [
      "Road and gravel fitness reinforce each other $€” the bike-handling, pacing, and fuelling demands of gravel translate back to the bunch.",
      "Privateer gravel is now a viable parallel career for World Tour-level riders, with its own sponsorship and prize-money economy.",
      "Long off-road events are won on fuelling discipline more than on raw power $€” the riders who blow up are the ones who under-eat in hour two.",
      "Position-specific gravel training (rough terrain at threshold) builds resilience that a smooth-road FTP block cannot.",
      "Balancing elite sport with a research career proves that the binary of pro-or-amateur is more flexible than the cycling press portrays.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-nutrition"],
  },
};

/** Look up overrides for a guest by slug. Returns undefined if no curated data. */
export function getGuestProfileOverride(
  slug: string,
): GuestProfileOverride | undefined {
  return GUEST_PROFILE_OVERRIDES[slug];
}
