/**
 * Guest profile overrides — curated, verified entity data for featured
 * podcast guests.
 *
 * Populated by hand from public sources (Wikipedia, official team pages,
 * verified social profiles). Every URL here has been verified via live
 * WebSearch — do NOT add entries without verifying the profile exists
 * and belongs to the right person. Inventing social URLs is the Google
 * Knowledge Graph equivalent of the AggregateRating footgun: it looks
 * authoritative, it fails audit trivially.
 *
 * The SEO value:
 *   - `sameAs` is the single strongest signal for Knowledge Graph entity
 *     disambiguation. It tells Google "this Greg LeMond is THE Greg
 *     LeMond (matching his Wikipedia entry, his official site, his
 *     Instagram), not some other person with the same name."
 *   - `worksFor` anchors the guest to a recognised org (SportsTeam or
 *     CollegeOrUniversity), which powers sitelinks and career-context
 *     panels in SERPs.
 *   - `image` surfaces a verified headshot in the Knowledge Panel.
 *
 * Coverage target: the 12 featured experts shown on /about. Easy to
 * extend — add new entries keyed by the guest's slug (the same slug
 * generated by `slugify()` in guests.ts).
 */

export interface GuestProfileOverride {
  /** Absolute URL of a headshot. Prefer a verified public photo. */
  image?: string;
  /**
   * Canonical "same as" URLs for Knowledge Graph entity disambiguation.
   * Order suggests priority — Wikipedia / Wikidata first, then official
   * personal site, then verified social profiles.
   */
  sameAs?: string[];
  /**
   * Organisation the guest currently works for or is affiliated with.
   * Used to populate schema.org `worksFor` with a proper type —
   * SportsTeam for pros, CollegeOrUniversity for academics, Organization
   * for everyone else.
   */
  worksFor?: {
    name: string;
    type: "SportsTeam" | "CollegeOrUniversity" | "Organization";
    url?: string;
  };
  /**
   * Optional longer-form description, replacing the auto-generated
   * "X — expert guest on The Roadman Cycling Podcast" fallback for
   * higher-profile entries.
   */
  description?: string;
  /**
   * Blog slugs that explicitly feature or cite this guest. Surfaced on
   * the /guests/[slug] page as a "Featured in" section. Creates a
   * bidirectional entity↔content link from the guest page to the
   * articles that reference them.
   */
  featuredArticles?: string[];
  /**
   * Long-form "why this person matters in cycling" paragraph rendered
   * as visible content under the hero. Gives entity context that goes
   * beyond a one-line credential — what they did, why it changed the
   * sport, who they coached, what they invented. AEO/SGE-friendly:
   * the literal answer to "who is X?" / "why is X famous?" sits on
   * the page Google can quote.
   */
  whyMatters?: string;
  /**
   * Bullet list of the major ideas this guest is known for in the
   * cycling world. Each item should be a short, citable claim
   * (8-25 words) — the kind of thing an LLM can pull as an answer.
   */
  keyIdeas?: string[];
  /**
   * Optional list of related topic hub slugs to surface under the
   * guest. Falls back to the auto-derived pillar→topic mapping when
   * absent.
   */
  relatedHubs?: string[];
}

/**
 * Slug → override map. Slugs match the output of `slugify()` in
 * `src/lib/guests.ts` applied to the canonical name after alias
 * normalisation (so "Professor Stephen Seiler" → "Stephen Seiler"
 * → slug `stephen-seiler`).
 */
export const GUEST_PROFILE_OVERRIDES: Record<string, GuestProfileOverride> = {
  "greg-lemond": {
    description:
      "Three-time Tour de France winner (1986, 1989, 1990) and two-time UCI Road World Champion. The only American man to win the Tour de France.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Greg_LeMond",
      "https://www.wikidata.org/wiki/Q312697",
      "https://www.instagram.com/greg.lemond/",
      "https://www.facebook.com/greglemond/",
      "https://www.procyclingstats.com/rider/greg-lemond",
    ],
    whyMatters:
      "Greg LeMond is the only American man to win the Tour de France and remains one of the most influential riders in the sport's history. His 1989 Tour victory by 8 seconds — won on the final-day Champs-Élysées time trial using aero bars and a Scott aerodynamic position the peloton had dismissed — is the most famous margin in cycling. He pioneered modern training-by-power, was an early adopter of wind-tunnel work, and has spent the post-EPO decades as one of the sport's most credible voices on doping, governance, and what clean riders are physiologically capable of. Every conversation about pro cycling history runs through him.",
    keyIdeas: [
      "Won the 1989 Tour de France by 8 seconds — the smallest margin in Tour history — using aero bars on the final time trial.",
      "First non-European to win the Tour, opened the sport to a global generation of riders.",
      "Early advocate for power-based training and wind-tunnel testing decades before the World Tour standardised both.",
      "Outspoken, evidence-based critic of EPO-era and Armstrong-era doping when it cost him sponsorships and friendships.",
      "Shot in 1987 in a hunting accident, returned to win two more Tours — a comeback case study cited across endurance sport.",
    ],
    relatedHubs: ["cycling-coaching", "cycling-training-plans"],
  },

  "stephen-seiler": {
    description:
      "Professor of Sport Science at the University of Agder, Norway. Exercise physiologist who coined the polarised-training model and the 80/20 rule of intensity distribution.",
    worksFor: {
      name: "University of Agder",
      type: "CollegeOrUniversity",
      url: "https://www.uia.no/english/",
    },
    sameAs: [
      "https://x.com/StephenSeiler",
      "https://www.uia.no/english/about-uia/employees/stephens/",
      "https://www.linkedin.com/in/stephen-seiler-668202a/",
      "https://www.researchgate.net/profile/Stephen-Seiler",
    ],
    featuredArticles: [
      "every-roadman-episode-with-stephen-seiler",
      "polarised-vs-sweet-spot-training",
      "what-cycling-podcasts-got-wrong-about-polarised-training",
    ],
    whyMatters:
      "Stephen Seiler is the exercise physiologist who, more than any other researcher, defined how modern endurance athletes structure their training. Working from his lab at the University of Agder, he documented that elite athletes across cycling, rowing, cross-country skiing and running converge on the same intensity distribution — roughly 80% easy, 20% hard, with very little time in the middle. That observation is now known as polarised training and the 80/20 rule, and it is the framework Roadman builds every training conversation on.",
    keyIdeas: [
      "Polarised training: ~80% of sessions at low intensity, ~20% at high intensity, very little time in the threshold/tempo grey zone.",
      "Elite endurance athletes across disciplines converge on the same intensity distribution — it is not a coaching opinion but a measured pattern.",
      "The biggest single mistake amateurs make is riding their easy days too hard, which compromises the quality of their hard days.",
      "Long, slow distance is the irreplaceable foundation — high-intensity work without an aerobic base produces short-lived gains.",
      "Heart rate, RPE, and lactate at sub-2 mmol/L are all reliable markers for genuine Zone 2 — power alone misses the day-to-day variation.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "tim-spector": {
    description:
      "British epidemiologist, Professor of Genetic Epidemiology at King's College London, and co-founder of the nutrition-science company ZOE. Author of Spoon-Fed, The Diet Myth and Food for Life.",
    worksFor: {
      name: "ZOE",
      type: "Organization",
      url: "https://zoe.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Tim_Spector",
      "https://www.instagram.com/tim.spector/",
      "https://x.com/timspector",
      "https://uk.linkedin.com/in/timspector",
      "https://zoe.com/learn/tim-spector",
    ],
    whyMatters:
      "Tim Spector is one of the most-cited researchers in nutrition science globally. His work on the gut microbiome, twin studies, and personalised nutrition through ZOE has reframed how endurance athletes think about food — moving the conversation away from generic macros and toward individual metabolic response, fibre diversity, and the gut as a performance organ. For cyclists chasing the last 2-3% of body composition or trying to fix mid-ride GI distress, his work is the most credible starting point.",
    keyIdeas: [
      "Individual metabolic response to identical foods varies enormously — population-level guidelines miss what actually works for a given athlete.",
      "Gut microbiome diversity, driven by 30+ different plant foods per week, predicts both general health and recovery markers in athletes.",
      "Ultra-processed foods drive the majority of negative health outcomes regardless of total calories or macros.",
      "Continuous glucose monitoring exposes how badly amateur athletes mistime carbohydrate intake around training.",
      "The fibre and polyphenol content of recovery meals matters as much as the protein dose for long-term adaptation.",
    ],
    relatedHubs: ["cycling-nutrition", "cycling-weight-loss"],
  },

  "lachlan-morton": {
    description:
      "Australian professional cyclist for EF Education–EasyPost, ultra-distance and alt-racing pioneer. Former Everesting world record holder, 2024 Unbound Gravel 200 winner, Great Divide ultra-endurance rider.",
    worksFor: {
      name: "EF Education–EasyPost",
      type: "SportsTeam",
      url: "https://www.efprocycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Lachlan_Morton",
      "https://www.efprocycling.com/our-team/lachlan-morton/",
      "https://www.procyclingstats.com/rider/lachlan-morton",
    ],
    whyMatters:
      "Lachlan Morton is the World Tour rider who proved you can race the Tour de France in July, set the Great Divide bikepacking record, and win Unbound Gravel — all in the same career. He has redefined what a pro cyclist's calendar can look like, championed alt-racing as a serious discipline, and become the public face of the link between ultra-endurance riding and World Tour fitness. For amateurs trying to figure out how to balance long days, racing, and adventure on the same engine, he is the model.",
    keyIdeas: [
      "Ultra-distance volume and World Tour racing fitness are not in conflict — they reinforce each other when periodised properly.",
      "Alt-racing (gravel, ultra, FKT attempts) is now a legitimate parallel career path, not a downshift from road racing.",
      "Mental durability on multi-day rides is built by spending genuine time alone on the bike, not by training plan structure alone.",
      "Pacing for ultra is closer to Zone 2 discipline than to threshold work — the riders who blow up are the ones who race the first half.",
      "Equipment choices for ultra (tyres, lighting, bag setup) matter more for finish-line performance than chasing 5W of aero gain.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-recovery"],
  },

  "joe-friel": {
    description:
      "Endurance sports coach and author. Wrote The Cyclist's Training Bible (now in its fifth edition), co-founded TrainingPeaks, and served as chairman of the USA Triathlon National Coaching Commission.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Joe_Friel",
      "https://joefrieltraining.com/",
    ],
    featuredArticles: [
      "how-to-periodise-cycling-season",
      "how-to-structure-cycling-training-plan",
      "masters-cyclist-guide-getting-faster-after-40",
    ],
    whyMatters:
      "Joe Friel wrote The Cyclist's Training Bible — the book that taught a generation of amateur cyclists how to think about periodisation, training stress, and the structure of a season. Co-founder of TrainingPeaks and former chairman of the USA Triathlon National Coaching Commission, he is the bridge between sports science and the home-trainer cyclist trying to peak for one event a year. Most modern amateur coaching software still leans on his vocabulary: periodisation, A/B/C races, base, build, peak, recovery weeks.",
    keyIdeas: [
      "Periodisation: structure your year into base, build, peak, race, and transition phases — each with a different physiological focus.",
      "Train your weakness, race your strength — the off-season is for fixing limiters, the in-season is for sharpening what already works.",
      "Recovery weeks every 3-4 weeks are not optional — they are the mechanism that allows training stress to convert to fitness.",
      "Heart rate zones are still the most accessible intensity tool for amateurs, and pair well with power for the riders who have both.",
      "After 50, the priorities shift: more strength work, slightly fewer high-intensity sessions, longer recovery between hard days.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training", "cycling-coaching"],
  },

  "ben-healy": {
    description:
      "Irish professional cyclist for EF Education–EasyPost. Winner of stage 6 of the 2025 Tour de France, and later wore the yellow jersey after stage 10 — the first Irish rider in yellow since Stephen Roche in 1987.",
    worksFor: {
      name: "EF Education–EasyPost",
      type: "SportsTeam",
      url: "https://www.efprocycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Ben_Healy_(cyclist)",
      "https://www.efprocycling.com/our-team/ben-healy/",
      "https://www.instagram.com/benhealy._/",
      "https://www.procyclingstats.com/rider/ben-healy",
    ],
    whyMatters:
      "Ben Healy is the Irish EF Education–EasyPost rider who became the first Irishman in the yellow jersey since Stephen Roche in 1987 after his stage 6 win at the 2025 Tour de France. He represents a generation of riders who blend long-range attacking with one-day Classics aptitude — and his rise has reshaped how the next wave of Irish riders think about turning pro through a domestic and continental development pathway rather than waiting on a national-team conveyor belt.",
    keyIdeas: [
      "The modern attacking puncheur model: confident on rolling parcours, capable of solo wins from 50km out.",
      "A development pathway through domestic UK/Irish racing into a continental team is now a viable route to the World Tour.",
      "Race weight matters less than power durability across multiple climbs in the final hour — a different optimisation than 1990s GC riders.",
      "Mental approach to long breakaways: commit early, ride your own threshold, ignore the gap until 10km to go.",
      "Irish cycling now has a structural pipeline — coaches, sponsors, junior racing — that was missing in the post-Roche decades.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training"],
  },

  "michael-matthews": {
    description:
      "Australian professional road and track cyclist for Team Jayco–AlUla. 2010 U23 Road Race World Champion, Tour de France green jersey winner, and Grand Tour stage winner across all three Grand Tours.",
    worksFor: {
      name: "Team Jayco–AlUla",
      type: "SportsTeam",
      url: "https://greenedgecycling.com",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Michael_Matthews_(cyclist)",
      "https://www.procyclingstats.com/rider/michael-matthews",
    ],
    whyMatters:
      "Michael Matthews is one of the most consistent stage-race sprinters of his generation: 2010 U23 World Champion, multiple Tour de France stage wins, Tour points jersey wearer, and a Grand Tour stage winner across all three. His career is a case study in adapting a sprint engine to a punchy stage-racing parcours — useful reading for any amateur trying to translate raw power into actual race finishes.",
    keyIdeas: [
      "A sprint career built on punchy finishes is more sustainable than chasing pure flat bunch sprints.",
      "Stage racing requires you to defend your fitness across three weeks — the riders who fade are the ones who under-recover in week one.",
      "Sprint training in the gym matters: explosive lifts and plyometrics translate directly to closing speed.",
      "Reading the finish — wind, road furniture, lead-out trains — wins more sprints than raw watts.",
      "Recovery between stages is mostly about sleep, fuelling within 30 minutes of the line, and protecting the next morning's intensity.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training"],
  },

  "dan-bigham": {
    description:
      "British aerodynamics engineer, former UCI Hour Record holder (55.548km, 2022), and Head of Engineering for Red Bull–Bora–Hansgrohe. Won multiple track cycling national, European and world championship medals.",
    worksFor: {
      name: "Red Bull–Bora–Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Daniel_Bigham",
      "https://www.britishcycling.org.uk/gbcyclingteam/bio/Dan_Bigham",
    ],
    whyMatters:
      "Dan Bigham is the British engineer-rider who held the UCI Hour Record at 55.548km in 2022 and now leads engineering at Red Bull–Bora–Hansgrohe. He is one of a small group of people who can talk credibly about both sides of the marginal-gains conversation: the wind-tunnel physics, and what it actually feels like to hold an aero position at threshold for an hour. His work on time-trial position, equipment selection, and pacing strategy has shaped how the modern peloton approaches every TT stage.",
    keyIdeas: [
      "Aero gains are real, but only after you have hit your achievable position — fit comes before kit.",
      "Time-trial pacing is a power-based problem: even-pace at the highest sustainable wattage, with course-aware adjustments for wind and gradient.",
      "The Hour Record is the cleanest aerodynamic test in cycling — no team tactics, no draft, just position and equipment.",
      "Most amateurs leave 20-40W on the table at the same FTP by riding a position that compromises them aerodynamically.",
      "Engineering rigor — measure, hypothesise, test, iterate — is more valuable in a TT programme than in any other discipline of cycling.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "dan-lorang": {
    description:
      "Luxembourgish performance coach. Long-time triathlon coach to Jan Frodeno, Anne Haug and Lucy Charles-Barclay; Head of Performance at Red Bull–Bora–Hansgrohe since 2017, announced in April 2026 that he will leave at the end of the 2026 season.",
    worksFor: {
      name: "Red Bull–Bora–Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: ["https://de.linkedin.com/in/dan-lorang-33296319"],
    featuredArticles: [
      "every-roadman-episode-with-dan-lorang",
      "ironman-bike-training-plan-16-weeks",
      "bike-leg-of-triathlon-why-age-groupers-get-it-wrong",
    ],
    whyMatters:
      "Dan Lorang is one of the most respected coaches in endurance sport — the long-time coach to triathlon greats Jan Frodeno, Anne Haug, and Lucy Charles-Barclay, and Head of Performance at Red Bull–Bora–Hansgrohe since 2017. He is the rare coach who has produced Ironman world champions and Grand Tour stage winners using the same underlying principles. His public work on training-load management, polarised intensity, and the long-arc development of an athlete has influenced how the smarter end of the amateur world structures their season.",
    keyIdeas: [
      "Long-term athlete development trumps short-term peaking — the best athletes are the ones who improve year-on-year for a decade.",
      "Polarised intensity distribution applies to both Ironman triathletes and Grand Tour riders — the principles cross disciplines.",
      "Training load is best managed by listening to the athlete daily, not by following a plan in spite of the body's signals.",
      "Strength work is non-negotiable for endurance athletes over 30 — durability prevents the late-season collapse.",
      "The bike leg of a triathlon is paced for the run that follows, not as a standalone TT — most age-groupers ignore this and fade in the marathon.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans", "triathlon-cycling"],
  },

  "john-wakefield": {
    description:
      "Cycling coach, bike fitter and Director of Coaching & Sports Science at Red Bull–Bora–Hansgrohe. Runs the Science to Sport Performance Laboratory in Girona, Spain. Previously Performance Co-ordinator and Coach at UAE Team Emirates over four seasons.",
    worksFor: {
      name: "Red Bull–Bora–Hansgrohe",
      type: "SportsTeam",
    },
    sameAs: [
      "https://www.linkedin.com/in/john-wakefield-a7449785/",
      "https://www.trainingpeaks.com/coach/john-sciencetosport",
    ],
    whyMatters:
      "John Wakefield is the South African-born coach and bike fitter who runs Science to Sport in Girona — one of the leading lab-to-bike performance facilities in cycling — and now serves as Director of Coaching & Sports Science at Red Bull–Bora–Hansgrohe. He spent four seasons as Performance Coordinator and Coach at UAE Team Emirates working alongside the Pogačar-era programme, and has coached riders from amateur to Grand Tour level using a metabolic-testing-led methodology. His work matters because he is one of the few coaches who systematically translates lab data — VO2max, Fat Max, lactate response — into the actual training week amateurs and pros ride.",
    keyIdeas: [
      "Lab-based metabolic testing reveals zone errors that FTP-derived calculations always miss.",
      "Most amateurs ride too hard on easy days because their power-derived Zone 2 is set too high.",
      "Aerobic-base deficits show up as second-half fade on rides over 2 hours — not on 20-minute tests.",
      "Bike fit is a performance variable, not a comfort one — the Girona lab combines fit and physiology testing on the same day.",
      "Pro and amateur training principles converge on the same physiology — the difference is the volume and the recovery.",
    ],
    relatedHubs: ["cycling-coaching", "cycling-training-plans", "ftp-training"],
  },

  "david-dunne": {
    description:
      "Performance nutritionist and researcher. PhD in Behaviour Change, Design Thinking, and Technology Innovation in Sports Nutrition from Liverpool John Moores University. IOC alumnus. Co-founder and CEO of Hexis, a personalised sports-nutrition platform; has worked with athletes across World Tour cycling, Premier League, NBA, Super League and Ryder Cup Team Europe.",
    worksFor: {
      name: "Hexis",
      type: "Organization",
      url: "https://www.hexis.live",
    },
    sameAs: [
      "https://www.researchgate.net/profile/David-Dunne-9",
      "https://www.hexis.live/blog/meet-the-team-david-dunne",
    ],
    whyMatters:
      "David Dunne is the performance nutritionist behind Hexis, the personalised sports-nutrition platform used by World Tour cyclists, Premier League clubs, NBA franchises, Super League sides, and Ryder Cup Team Europe. With a PhD in behaviour change, design thinking, and technology innovation in sports nutrition, and IOC alumnus credentials, he sits at the intersection of academic research and practical application. His work matters because he turned periodised nutrition — matching carb intake to training load day by day — from a coaching idea into a measurable system used by hundreds of elite athletes and tens of thousands of amateurs.",
    keyIdeas: [
      "Carbohydrate periodisation matches daily intake to training load — it is not low-carb, it is right-carb.",
      "Energy availability is the unsung lever for body-composition change and long-term training durability.",
      "Fuelling around training matters more than total daily macro targets — the timing changes the adaptation.",
      "Behaviour change in nutrition is a design problem — make the right thing easy and the wrong thing inconvenient.",
      "Personalised plans outperform generic ones at every level, but only if they are actually used — adherence is the limiting factor.",
    ],
    relatedHubs: ["cycling-nutrition", "cycling-weight-loss"],
  },

  "alan-murchison": {
    description:
      "Scottish chef and elite sports nutritionist. Held a Michelin star at L'Ortolan in Berkshire from 2003 to 2014. Founder of Performance Chef LTD; consultant to British Cycling, the chef behind Specialized Factory Racing's race plates, and author of The Cycling Chef cookbook series (Bloomsbury). Multiple-time World and European age-group duathlon champion.",
    worksFor: {
      name: "Performance Chef",
      type: "Organization",
      url: "https://performancechef.com/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Alan_Murchison",
      "https://performancechef.com/",
      "https://www.instagram.com/performance.chef/",
      "https://twitter.com/AlanMurchison",
      "https://www.linkedin.com/in/alan-murchison-695668107/",
      "https://www.greatbritishchefs.com/chefs/alan-murchison",
    ],
    featuredArticles: [
      "alan-murchison-michelin-star-chef-cycling-nutrition",
      "cycling-protein-requirements",
      "cycling-in-ride-nutrition-guide",
      "cycling-weight-loss-fuel-for-the-work-required",
    ],
    whyMatters:
      "Alan Murchison is the chef who left Michelin-starred fine dining to feed Olympic cyclists, World Tour riders, and Formula 1 drivers. He spent over a decade running L'Ortolan in Berkshire to a Michelin star and four AA Rosettes, then walked away from the restaurant world to build Performance Chef — the food operation behind Specialized Factory Racing's Olympic medals, World Cup podiums, and the British Cycling consultancy that fuels riders from first-time finishers to gold medallists. He matters because he is the rare voice who can talk credibly about both the precision of fine-dining technique and the metabolic demands of racing a bike: the food still has to taste good, and it still has to land 90 grams of carbohydrate an hour without wrecking the gut. His Cycling Chef book series and his work with Canyon-SRAM have set the modern standard for what a serious amateur's kitchen actually looks like.",
    keyIdeas: [
      "Quality of food matters more than macros — chicken, rice, and broccoli twice a day will fuel performance and produce a malnourished athlete at the same time.",
      "30+ different plants a week is not a wellness fad — it is the simplest proxy for the gut diversity that supports recovery, immune function, and hard training.",
      "Race-day nutrition has to be rehearsed in training — the day of an event is the worst possible time to discover a gel does not agree with your gut.",
      "Recovery starts in the first 30 minutes after a hard session and is mostly about getting carbohydrate, protein, and fluid in fast — the format (real food, shake, smoothie) matters less than the timing.",
      "Plant-powered performance is genuinely possible at the elite level, but the protein and iron maths have to be deliberate — it is not just removing meat from a normal diet.",
    ],
    relatedHubs: ["cycling-nutrition", "cycling-weight-loss"],
  },

  "andy-galpin": {
    description:
      "Professor of Kinesiology at California State University, Fullerton, and one of the most cited muscle physiologists in the world. Founder of the Center for Sport Performance and the Biochemistry & Molecular Exercise Laboratory at Cal State Fullerton, co-author of more than ninety peer-reviewed papers on skeletal muscle, and host of the Perform with Dr Andy Galpin podcast.",
    worksFor: {
      name: "California State University, Fullerton",
      type: "CollegeOrUniversity",
      url: "https://hhd.fullerton.edu/knes/",
    },
    sameAs: [
      "https://www.andygalpin.com/",
      "https://hhd.fullerton.edu/knes/faculty-staff/fulltime-faculty/andy-galpin.html",
      "https://www.performpodcast.com/",
      "https://www.youtube.com/@drandygalpin",
      "https://www.instagram.com/drandygalpin/",
    ],
    featuredArticles: [
      "andy-galpin-fast-twitch-fibres-cyclist-after-40",
      "cycling-strength-training-guide",
      "cycling-training-plan-masters-over-40",
      "masters-cyclist-guide-getting-faster-after-40",
      "cycling-over-40-getting-faster",
    ],
    whyMatters:
      "Andy Galpin is the muscle physiologist most masters cyclists have been quoting without realising it. He runs the Center for Sport Performance and the Biochemistry & Molecular Exercise Laboratory at Cal State Fullerton, has co-authored more than ninety peer-reviewed papers on skeletal muscle, hypertrophy, fibre-type adaptation, and recovery, and consults for athletes across MMA, motorsport, the NBA, the NFL, and Olympic sport. If you have heard a coaching argument in the last three years that turned on type II fibre atrophy, velocity-based training, or protein dose timing for older athletes, the original work behind that argument almost certainly has Andy's name on it. He is also the rare academic whose communication ability matches his research credentials — his Perform podcast and Huberman Lab guest appearances have done more to translate skeletal muscle physiology into amateur-athlete language than any textbook ever has.",
    keyIdeas: [
      "Power output declines faster than maximal strength, and strength declines faster than muscle mass — the neuromuscular system is the first thing to age in an athlete.",
      "Type II (fast-twitch) fibres can shrink 10 to 40 percent in older adults compared to younger controls; type I fibres are relatively preserved, which is why endurance riding alone protects the wrong half of the system.",
      "Velocity-based training matters as much as load — moving a moderate weight fast does more for an older athlete's nervous system than grinding a heavier weight slowly.",
      "Daily protein for trained masters athletes should sit at 1.6 to 2.2 grams per kilogram, distributed across four meals, with at least one dose above 35 grams to clear the leucine threshold for older muscle.",
      "Recovery is the active process that turns training into adaptation — sleep, stress regulation, and the gap between hard sessions determine whether work compounds or just accumulates as fatigue.",
    ],
    relatedHubs: ["cycling-strength-conditioning", "cycling-recovery"],
  },

  "alistair-brownlee": {
    description:
      "British former professional triathlete. Two-time Olympic triathlon champion (London 2012, Rio 2016) — the only athlete to hold back-to-back Olympic individual triathlon titles — four-time European champion, and 2014 Commonwealth Games gold medallist. Retired from professional racing in November 2024.",
    worksFor: {
      name: "Brownlee Fitness",
      type: "Organization",
      url: "https://brownleefitness.com/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Alistair_Brownlee",
      "https://www.alistairbrownlee.com/",
      "https://www.instagram.com/alistair.brownlee/",
      "https://triathlon.org/athletes/profile/7788/alistair-brownlee",
      "https://www.teamgb.com/athlete/alistair-brownlee/VXXED6uYsmhlvhF6O8HIK",
    ],
    featuredArticles: [
      "alistair-brownlee-endurance-lessons",
      "triathlon-cycling-training-plan",
      "triathlon-ftp-pacing-strategy",
    ],
    whyMatters:
      "Alistair Brownlee is the standard the rest of triathlon spent a decade chasing. Back-to-back Olympic golds, four European titles, a Commonwealth title, and a career built on a training philosophy of high aerobic volume layered with brutal threshold work — the same template the Norwegian school then refined. For Roadman's masters and triathlete audience he is the bridge from World Tour-level cycling fitness to multi-discipline endurance, and a credible voice on what genuinely transfers from elite training and what does not.",
    keyIdeas: [
      "Back-to-back Olympic triathlon golds at London 2012 and Rio 2016 — the only athlete to hold the title in consecutive Games.",
      "Aerobic base done right beats fashionable intensity protocols — the volume he ran for ten years is what made the threshold sessions land.",
      "Cross-discipline transfer is real: cycling fitness builds the run, but only if the run gets specific work too — neither sport substitutes for the other.",
      "Race-day execution is built in training, not on the line. The Brownlee model is to rehearse pacing, fuelling, and pain tolerance until they're automatic.",
      "The athletic career is one chapter — coaching, business, and longevity matter more than another medal. Knowing when to retire is part of the craft.",
    ],
    relatedHubs: ["triathlon-cycling", "cycling-training-plans"],
  },

  "valtteri-bottas": {
    description:
      "Finnish Formula 1 driver, two-time World Drivers' Championship runner-up (2019, 2020) with Mercedes, ten-time Grand Prix winner. Returned to F1 with Cadillac for 2026. Outside racing he is a serious gravel cyclist and co-founder of FNLD GRVL in Finland.",
    worksFor: {
      name: "Cadillac F1 Team",
      type: "Organization",
      url: "https://www.formula1.com/en/teams/cadillac",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Valtteri_Bottas",
      "https://www.wikidata.org/wiki/Q138745",
      "https://www.formula1.com/en/drivers/valtteri-bottas",
      "https://www.instagram.com/valtteribottas/",
    ],
    whyMatters:
      "Valtteri Bottas is the F1 driver who became one of the most credible amateur gravel racers in the world while still in the paddock. Two seasons as Mercedes runner-up, ten Grand Prix wins, and a 2024 UCI Gravel World Championships start — plus FNLD GRVL, the Finnish gravel race he co-founded with partner Tiffany Cromwell. For Roadman's audience he is the proof that genuine cycling performance is reachable while holding down a career outside the sport, and a voice on what motorsport-grade preparation, recovery, and discipline look like applied to the bike.",
    keyIdeas: [
      "Cycling discipline transfers from motorsport — the same focus on data, recovery, and incremental gains drives both.",
      "Serious amateur cycling is compatible with a demanding career, but only if training is non-negotiable in the calendar before everything else fills in.",
      "Race weight matters less than year-round fuelling — under-eating to chase numbers compromises the F1 day job and the bike at once.",
      "Gravel events are the rare format where pros and amateurs share a course on a level playing field — a humbling and motivating reality check.",
      "Recovery is the limiting factor for athletes pushing two careers — sleep and stress regulation matter more than another training block.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-recovery"],
  },

  "andre-greipel": {
    description:
      "German former professional sprinter who rode at the WorldTour level from 2005 to 2021. 158 career wins including 22 Grand Tour stages — 11 Tour de France, 7 Giro d'Italia, 4 Vuelta — and the 2018 Belgian one-day classics circuit. Now national road coach for the German Cycling Federation.",
    worksFor: {
      name: "Bund Deutscher Radfahrer (German Cycling Federation)",
      type: "Organization",
      url: "https://www.rad-net.de/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Andr%C3%A9_Greipel",
      "https://www.wikidata.org/wiki/Q168712",
      "https://www.andregreipel.de/en/",
      "https://www.procyclingstats.com/rider/andre-greipel",
    ],
    featuredArticles: [
      "andre-greipel-sprint-captaincy-burnout",
      "andre-greipel-sprint-captains-code",
    ],
    whyMatters:
      "André Greipel is one of the most decorated Grand Tour sprinters of his generation — eleven Tour de France stage wins, twenty-two Grand Tour stages in total, and a fifteen-year top-flight career across Lotto, Arkéa, and Israel. He is also one of the few sprinters who has talked openly about the mental cost of the role: managing leadout teams, surviving non-sprint stages, and the burnout cycle that ends most sprinting careers early. As Germany's national road coach since 2023 he sees the next generation up close, which makes his perspective on what amateur sprinters get wrong unusually current.",
    keyIdeas: [
      "Sprinting is captaincy, not just kick — the leadout train, the protection in the bunch, and the radio calls determine whether the sprint even starts in the right position.",
      "Surviving the mountain stages is the unsexy skill that decides Grand Tour sprint careers — pure speed without resilience does not translate to GT stage wins.",
      "Burnout in pro sprinting is real and underdiscussed — the constant calorie management, post-stage recovery, and team pressure compound over a career.",
      "Amateur sprinters skip the positioning work and over-index on raw watts — the win is decided in the last 5km positioning, not the last 200m.",
      "The transition from rider to coach is brutal but clarifying — what looks like talent at WorldTour level is mostly accumulated decision-making under fatigue.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-coaching"],
  },

  "george-hincapie": {
    description:
      "American former professional cyclist (1994–2012), 17-time Tour de France finisher (a record at retirement), three-time US national road champion, and 2001 Gent-Wevelgem winner. Veteran of the US Postal / Discovery Channel era. Founder of Hincapie Sportswear and, in 2025, Modern Adventure Pro Cycling.",
    worksFor: {
      name: "Modern Adventure Pro Cycling",
      type: "SportsTeam",
      url: "https://hincapie.com/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/George_Hincapie",
      "https://www.procyclingstats.com/rider/george-hincapie",
      "https://www.olympedia.org/athletes/14752",
      "https://www.teamusa.com/profiles/george-hincapie",
      "https://hincapie.com/",
    ],
    featuredArticles: [
      "pogacar-van-der-poel-hincapie-paris-roubaix-2026",
      "tyler-hamilton-us-postal-doping-confession",
    ],
    whyMatters:
      "George Hincapie rode 17 Tours de France — the record when he retired — and was the only rider to support Lance Armstrong through all seven of his Tour wins (since stripped). He is one of the few American riders who has openly addressed the doping era, the team dynamics inside US Postal, and the post-Armstrong rebuilding of US cycling. His 2025 launch of Modern Adventure Pro Cycling, alongside his brother Richard, makes him both a primary historical witness and an active team owner — a rare combination for that era.",
    keyIdeas: [
      "Classics survival is built on positioning, not power — Hincapie's career proves that being in the right wheel for 250km matters more than peak watts.",
      "The doping era was a team-level decision, not an individual one — the post-Armstrong reckoning is also institutional, not just personal.",
      "American pro cycling's pipeline broke when US Postal dissolved — the Modern Adventure project is an attempt to rebuild that domestic pathway.",
      "Paris-Roubaix tactics have changed less than the equipment — the cobbles still reward the rider who reads the bunch and times the move into the right sector.",
      "Longevity at WorldTour level is a function of team role clarity — the riders who last are the ones who know exactly what they're paid to do each race.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-coaching"],
  },

  "alex-dowsett": {
    description:
      "British former professional road and time-trial cyclist (2011–2024). Held the UCI Hour Record in 2015 (52.937 km), six-time British national TT champion, Commonwealth Games gold medallist, and Giro d'Italia stage winner. Lifelong haemophilia campaigner and founder of the Little Bleeders charity.",
    worksFor: {
      name: "Little Bleeders",
      type: "Organization",
      url: "https://www.littlebleeders.org/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Alex_Dowsett",
      "https://www.procyclingstats.com/rider/alex-dowsett",
      "https://www.cyclingweekly.com/tag/alex-dowsett",
    ],
    featuredArticles: [
      "alex-dowsett-pro-cycling-lessons-amateur",
      "heat-training-cyclists-30-watts-ftp-protocol",
      "jack-burke-strava-records-stelvio-alpe-dhuez",
    ],
    whyMatters:
      "Alex Dowsett is the rare WorldTour rider whose entire career was built on aerodynamics, time-trialling, and methodical preparation rather than raw climbing wattage. The 2015 Hour Record (52.937km), six British TT titles, and a Giro d'Italia stage win came from being the most prepared rider on the start line, not the most genetically gifted. He has also been one of cycling's most public haemophilia campaigners, founding Little Bleeders to support kids with bleeding disorders into sport. His post-retirement coaching and content work — including Astana's aero programme — make him a current voice on what amateurs get wrong about position, equipment, and pacing.",
    keyIdeas: [
      "Aerodynamics is the cheapest watts amateurs ignore — position and skinsuit fit beat power upgrades for almost every age-grouper on flat or rolling terrain.",
      "Pacing the Hour Record is a discipline most amateurs cannot replicate — the brain wants to surge, the body needs absolutely flat power for sixty minutes.",
      "Time-trial preparation is a long-arc project — a Hour Record bike, position, and pacing model takes 18+ months to build, not a training block.",
      "Haemophilia did not stop a WorldTour career — adaptive training and medical support are the difference, not avoidance of the sport.",
      "Most amateur TT mistakes happen in the first 5km — going out too hard from a standing start blows the entire effort before the engine has settled.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "ed-clancy": {
    description:
      "British former track cyclist, three-time Olympic team-pursuit gold medallist (2008 Beijing, 2012 London, 2016 Rio) — the most successful team-pursuit rider in history. Eight-time UCI Track World Championship medallist. OBE for services to cycling. Now a coach, broadcaster, and motivational speaker.",
    worksFor: {
      name: "British Cycling",
      type: "Organization",
      url: "https://www.britishcycling.org.uk/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Ed_Clancy",
      "https://www.wikidata.org/wiki/Q712919",
      "https://www.olympedia.org/athletes/113193",
      "https://www.teamgb.com/athlete/ed-clancy/6H6EYRLX80BRZ7YF8n8fWk",
    ],
    whyMatters:
      "Ed Clancy holds three Olympic team-pursuit gold medals — Beijing, London, and Rio — and is the most successful team-pursuit rider in the discipline's history. He was the start-man on the British squad that turned a four-minute event into a sub-3:50 standard. His specialism — the thirty-second standing start that sets the team's pace — is the ultimate expression of trained anaerobic power, neuromuscular drive, and pressure management. For Roadman's audience he is the bridge between road cycling fitness and the explosive end of the sport that most amateurs never train.",
    keyIdeas: [
      "Standing-start power is a trainable skill, not a genetic gift — the British team built it through years of specific neuromuscular work and gym programming.",
      "Team pursuit teaches what amateurs never learn — pacing in a four-rider rotation under threshold-plus, where the wheel in front is the only thing that matters.",
      "The British Cycling marginal-gains era was real but oversold — the actual edge was strength training, sleep discipline, and recruitment, not magic kit.",
      "Track training transfers to road power — the threshold and VO2max work done at velodrome intensity translates directly to time-trial and climbing performance.",
      "Career transition for Olympians is brutal — the structure that made the medals possible is gone the day you retire, and the rebuild has to start from scratch.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "olav-bu": {
    description:
      "Norwegian sports scientist and head coach. Architect of the 'Norwegian Method' that produced Kristian Blummenfelt's 2021 Olympic triathlon gold and Gustav Iden's two Ironman 70.3 world titles plus 2022 Ironman world title. Now also head coach of Norwegian WorldTour cycling team Uno-X Mobility.",
    worksFor: {
      name: "Uno-X Mobility",
      type: "SportsTeam",
      url: "https://www.uno-x.no/",
    },
    sameAs: [
      "https://www.tri247.com/triathlon-news/elite/olav-aleksander-bu-pro-cycling-switch-kristian-blummenfelt-gustav-iden",
      "https://triathlonmagazine.ca/personalities/kristian-blummenfelts-coach-becomes-head-coach-of-norwegian-cycling-team-uno-x/",
    ],
    featuredArticles: [
      "cycling-hrv-training-guide",
      "triathlon-ftp-pacing-strategy",
      "triathlon-cycling-training-plan",
    ],
    whyMatters:
      "Olav Aleksander Bu is the sports scientist who turned a small Norwegian triathlon programme into the most replicated coaching template in modern endurance sport. The 'Norwegian Method' — high lactate-threshold volume, daily lactate testing, double-threshold sessions — produced Blummenfelt's Olympic gold, Iden's Ironman world titles, and a generation of imitators across cycling and running. His 2024 move to head coach of Uno-X Mobility makes him one of the few coaches who has run the same testing-driven, individualised approach across both World Tour cycling and elite triathlon.",
    keyIdeas: [
      "Threshold work, dosed correctly, is the single highest-leverage intervention for trained endurance athletes — but it requires lactate testing to dose right.",
      "Individualised lactate response trumps generic zones — two riders at the same FTP can need wildly different threshold prescriptions.",
      "The Norwegian Method scales — the same testing-led framework that built Olympic triathletes is now driving Uno-X cycling improvements.",
      "Endurance science has converged across sports — the biggest gains for cyclists now come from triathlon, running, and rowing literature, not cycling-specific research.",
      "Recovery quality is the rate-limiter — the volume and threshold work only land if sleep, fuelling, and stress are managed at the same level as the training.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training", "triathlon-cycling"],
  },

  "hannah-grant": {
    description:
      "Danish chef and author. Chef for Bjarne Riis' Tinkoff–Saxo cycling team for five years across multiple Grand Tours, Daytime Emmy winner for Amazon's Eat Race Win, and author of The Grand Tour Cookbook and The New Grand Tour Cookbook 2.0. Trained at Noma; founder of Musette Publishing.",
    worksFor: {
      name: "Musette Publishing",
      type: "Organization",
      url: "https://hannahgrant.com/",
    },
    sameAs: [
      "https://hannahgrant.com/",
      "https://www.imdb.com/name/nm9617179/",
      "https://hannahgrant.bigcartel.com/product/the-grand-tour-cookbook",
    ],
    featuredArticles: [
      "cycling-protein-requirements",
      "hannah-grant-pro-team-chef-weight-loss",
      "dr-allen-lim-cycling-after-armstrong-clean-innovation",
    ],
    whyMatters:
      "Hannah Grant fed a WorldTour team across five seasons of Grand Tours and turned the experience into the most credible cycling-nutrition cookbook ever published. Trained at Noma, chef for Tinkoff-Saxo from 2011, Daytime Emmy winner for Eat Race Win — she is the rare voice who has cooked at fine-dining level AND fed riders racing 200km a day for three weeks. For Roadman's audience she is the practical answer to the question most amateurs avoid: what do you actually put on the plate, every day, to fuel real training without ending up fat or under-recovered?",
    keyIdeas: [
      "Quality cooking and performance fuelling are not in conflict — the same flavour discipline that wins Michelin stars makes athletes eat more of the right food.",
      "Pro-team meals are mostly real food — pasta, rice, vegetables, fish — not gel-and-bar engineering. Amateurs who copy the supplements miss the actual diet.",
      "Recovery food has to be appetising or it does not get eaten — the protein dose post-stage matters less than whether the rider actually finishes the plate.",
      "Hydration is fuelling — the saltiest pro-team meal of the day is breakfast, deliberately, to set up the day's electrolyte balance.",
      "Race-week kitchen logistics decide outcomes — the team that can cook fresh in a hotel kitchen at 11pm has a genuine performance edge.",
    ],
    relatedHubs: ["cycling-nutrition", "cycling-weight-loss"],
  },

  "mark-beaumont": {
    description:
      "British long-distance cyclist, broadcaster, and author. Holder of the around-the-world cycling record at 78 days, 14 hours (2017), having ridden ~240 miles a day for nearly three months. BEM. Author of multiple bestselling adventure books and a regular BBC presenter.",
    worksFor: {
      name: "Mark Beaumont Online",
      type: "Organization",
      url: "https://markbeaumontonline.com/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Mark_Beaumont_(cyclist)",
      "https://markbeaumontonline.com/",
      "https://www.guinnessworldrecords.com/news/2019/8/mark-beaumont-explains-what-it-takes-to-cycle-around-the-world-in-record-time-585073",
    ],
    whyMatters:
      "Mark Beaumont rode around the world in 78 days — 18,000 miles, ~240 miles a day, sixteen hours in the saddle, five hours of sleep, for the better part of three months. The record beat the previous mark by 44 days and remains untouched. For Roadman's ultra-endurance and 'Not Done Yet' audience he is the proof that the human ceiling on volume is much higher than amateurs assume, and a credible voice on the recovery, fuelling, and mental discipline that ultra-distance demands. His broadcast career and books also make him one of the sport's most articulate ambassadors.",
    keyIdeas: [
      "The body adapts to ultra-distance volume faster than the brain does — the limiting factor on round-the-world rides is psychological, not aerobic.",
      "Sleep at five hours a night is survivable for weeks but not months — the around-the-world record is the edge of the human envelope, not a template.",
      "Fuel-on-the-bike is the difference between finishing and quitting — solid food intake at 2,000+ kcal/day was Beaumont's non-negotiable.",
      "Equipment failure ends ultra rides more often than fitness does — bikepacking durability beats marginal aero gains every time.",
      "The post-record decompression is the hardest phase — coming back to normal life and training rhythms after that volume takes longer than the ride itself.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-recovery"],
  },

  "eddie-dunbar": {
    description:
      "Irish professional cyclist from Banteer, County Cork. Two-stage winner at the 2024 Vuelta a España, 2024 Irish national time-trial champion. Rode for Team Sky, INEOS Grenadiers, and Jayco–AlUla; signed with Q36.5 Pro Cycling for 2026 alongside Tom Pidcock.",
    worksFor: {
      name: "Q36.5 Pro Cycling Team",
      type: "SportsTeam",
      url: "https://www.q36-5procycling.com/",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Eddie_Dunbar",
      "https://www.procyclingstats.com/rider.php?id=181466",
    ],
    featuredArticles: [
      "best-cycling-coach-ireland",
    ],
    whyMatters:
      "Eddie Dunbar is the Irish climber who turned a near-career-ending sequence of injuries and team transitions into two Vuelta stage wins in 2024 and a 2026 move to Q36.5 alongside Tom Pidcock. From Aqua Blue Sport to Team Sky to INEOS to Jayco-AlUla and now Q36.5, his career has been the modern WorldTour journeyman story — and his honesty about how close he came to being out of the sport makes him a rare voice on what genuine resilience looks like at the top end. For the Irish audience and the broader masters base, he is a credible model for staying in the fight when the data says you should not.",
    keyIdeas: [
      "Climbing form is built on consistent base years, not single training blocks — the riders who hold WorldTour climbing legs are the ones who never lost their base.",
      "Team fit matters more than team prestige — being a domestique at INEOS taught Dunbar what he could not do, but a leadership role at Q36.5 will reveal what he can.",
      "Stage racing is a recovery game — the Vuelta wins came after he stopped chasing every breakaway and started managing the three-week load.",
      "Injuries do not have to end careers — the rebuild model is to come back as a slightly different rider, not the same one.",
      "Irish cycling now has a structural pathway — coaches, junior racing, sponsors — that was missing in the post-Roche decades. Dunbar is part of that proof.",
    ],
    relatedHubs: ["cycling-training-plans", "ftp-training"],
  },

  "andy-mcgrath": {
    description:
      "British cycling journalist and author. Former editor of Rouleur magazine. Author of Tom Simpson: Bird on the Wire (2017 William Hill Sports Book of the Year), God Is Dead: The Rise and Fall of Frank Vandenbroucke, and Tadej Pogačar: Unstoppable. Contributor to The Guardian, Financial Times, and Cyclingnews.",
    sameAs: [
      "https://www.penguinrandomhouse.com/authors/2270469/andy-mcgrath/",
      "https://www.cyclingnews.com/author/andy-mcgrath/",
      "https://uk.linkedin.com/in/andy-mcgrath-b7442251",
    ],
    whyMatters:
      "Andy McGrath is the cycling journalist who has written the definitive modern biographies of three very different riders — Tom Simpson, Frank Vandenbroucke, and Tadej Pogačar. His Tom Simpson book won the 2017 William Hill Sports Book of the Year, the highest honour in British sportswriting, and his Vandenbroucke biography is the only credible English-language account of one of the sport's most tragic talents. As former editor of Rouleur and a long-form contributor to the Guardian and FT, he sits where most cycling fans wish they could — close enough to the riders for real access, far enough away to write honestly about them.",
    keyIdeas: [
      "Cycling journalism's golden age was built on long-form access — the era of riders sitting down for hours of interview is largely over, and that loss is showing.",
      "Tom Simpson's death at Mont Ventoux is the foundational story of professional cycling's drug culture — the modern peloton is still living in its shadow.",
      "Frank Vandenbroucke is the warning sign nobody wanted to see — extraordinary talent paired with managed mental illness, in a sport that had no framework for either.",
      "Tadej Pogačar is the most studied modern rider because the journalism finally caught up — his openness has reset what fans can know about a Tour winner's daily life.",
      "Books outlast features — the long-form biography is the format that survives the news cycle, and the one most cycling fans actually keep.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-coaching"],
  },

  "derek-teel": {
    description:
      "American strength coach. Founder of Dialed Health, an online cycling-specific strength and conditioning programme used by amateur and professional cyclists. Background in functional movement and corrective exercise.",
    worksFor: {
      name: "Dialed Health",
      type: "Organization",
    },
    whyMatters:
      "Derek Teel is the strength coach who built Dialed Health into one of the most accessible cycling-specific S&C programmes online. He works with amateurs from base level to category racing, and his frameworks for off-bike strength — single-leg work, hip hinges, posterior chain, mobility — have shaped how a generation of time-crunched riders think about supplementing their training. For Roadman listeners chasing power, durability, and longevity, his work is a primary practical reference for what strength training for cycling actually looks like.",
    keyIdeas: [
      "Cycling-specific strength is single-leg, hip-dominant, and built around movement quality, not max effort.",
      "Two 30-minute sessions a week is enough to change body composition and protect against injury for most amateurs.",
      "Mobility work pre-ride is not warm-up — it is a separate adaptation that protects the bike position long-term.",
      "Strength training fits inside a cycling week if you give up one easy spin and protect the hard sessions on the bike.",
      "Off-season is the highest-leverage window for building strength capacity that lasts through the racing year.",
    ],
    relatedHubs: ["cycling-strength-conditioning"],
  },

  "chris-voss": {
    description:
      "American author and former FBI lead international kidnapping negotiator (1992–2007). Founder of The Black Swan Group. Author of Never Split the Difference: Negotiating As If Your Life Depended On It.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Chris_Voss",
    ],
    whyMatters:
      "Chris Voss is the former FBI lead international kidnapping negotiator and author of Never Split the Difference, the modern textbook on high-stakes negotiation. His work on tactical empathy, mirroring, and labelling has reshaped how everyone from sales professionals to senior executives approaches difficult conversations. For Roadman listeners, his frameworks transfer directly to the negotiations cyclists face day-to-day — with sponsors, with employers about training time, with family about race weekends, and with their own internal voice when training gets hard.",
    keyIdeas: [
      "Tactical empathy: understanding the other person's perspective without agreeing with it is the foundation of every good negotiation.",
      "Mirroring and labelling open the other person's emotional state — they are simple, repeatable, and effective.",
      "'No' is the start of a negotiation, not the end — it is the moment you find out what the other person actually cares about.",
      "Black swans — unknown unknowns — are usually the difference between a good outcome and a great one.",
      "High-stakes negotiation principles work in low-stakes contexts too — every conversation about training time is a negotiation.",
    ],
    relatedHubs: ["cycling-coaching"],
  },

  "colin-o-brady": {
    description:
      "American endurance athlete. First person to complete a solo unsupported crossing of Antarctica (2018, 932 miles in 54 days). Set the Explorers Grand Slam record (Seven Summits plus skiing to both poles in 139 days, 2016). Author of The Impossible First.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Colin_O%27Brady",
    ],
    whyMatters:
      "Colin O'Brady is the American endurance athlete who completed the first solo unsupported Antarctic crossing — 932 miles, 54 days, dragging a 375-pound sled across the continent. He held the Explorers Grand Slam record (Seven Summits plus both poles in 139 days). His work matters for cyclists not because of the equipment overlap but because of the methodology: training for multi-week ultra-endurance, mental rehearsal under load, energy availability across 6,000-calorie days, and recovery from genuinely extreme physical demands. For Roadman listeners thinking about week-long bikepacking trips or Race Across America-style efforts, his frameworks are some of the cleanest available.",
    keyIdeas: [
      "Mental rehearsal of suffering is a trainable skill — the riders who finish are the ones who have been there in their head first.",
      "Energy availability for multi-week efforts is the limiting factor — you cannot make up calorie debt mid-event.",
      "Recovery from extreme efforts is months, not weeks — most ultra athletes underestimate the carryover deficit.",
      "Goal-setting for ultra-endurance has to be process-led, not outcome-led, or you break under day-3 doubt.",
      "Solo unsupported is a different sport from supported — the calorie maths and the gear maths are everything.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-recovery"],
  },

  "dr-allen-lim": {
    description:
      "American sports physiologist. Founder of Skratch Labs. Former director of sports science for Team Garmin–Slipstream (2008–2010) and personal coach to riders including Lance Armstrong, Levi Leipheimer, and Christian Vande Velde. Author of The Feed Zone Cookbook series.",
    worksFor: {
      name: "Skratch Labs",
      type: "Organization",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Allen_Lim",
    ],
    whyMatters:
      "Dr Allen Lim is the sports physiologist who turned the World Tour kitchen on its head. As director of sports science at Garmin–Slipstream and personal physiologist to riders including Lance Armstrong, Levi Leipheimer, Christian Vande Velde, and the Schleck brothers, he was inside the rooms where modern endurance fuelling shifted from sports-drink-and-bar standards to real food. He founded Skratch Labs, wrote the Feed Zone Cookbook series with Biju Thomas, and has shaped how an entire generation of amateurs thinks about hydration, on-bike fuelling, and recovery meals. His work matters because it sits at the intersection of physiology research and what actually works in a team kitchen on a Grand Tour.",
    keyIdeas: [
      "Hydration is about sodium and absorption rate, not just water — the standard sports-drink formulations were too sweet and too low in electrolytes.",
      "Real food on the bike (rice cakes, potatoes, baked goods) outperforms gels for many riders — gut tolerance is the limit.",
      "Recovery starts in the first 30 minutes after a hard session and is dominated by carbohydrate, fluid, and protein in that order.",
      "Personalised nutrition is not a marketing term — sweat sodium loss, gut tolerance, and energy needs vary by orders of magnitude between athletes.",
      "Race-day fuelling has to be rehearsed in training — the day of an event is the worst time to discover a product does not work for you.",
    ],
    relatedHubs: ["cycling-nutrition"],
  },

  "dr-andy-pruitt": {
    description:
      "American sports medicine specialist and bike fit pioneer. Founder of the Boulder Center for Sports Medicine (1990) and the Specialized Body Geometry (BG) Fit programme. Has worked with US national-level cyclists, triathletes, and Olympic athletes for over four decades.",
    worksFor: {
      name: "Boulder Center for Sports Medicine",
      type: "Organization",
    },
    whyMatters:
      "Dr Andy Pruitt is the founder of the Boulder Center for Sports Medicine and the godfather of modern bike fitting. He developed the Specialized BG (Body Geometry) Fit system that is now used in thousands of bike shops worldwide, and has worked with US Olympic cyclists, professional teams, and World Tour riders for over four decades. His work matters because he turned bike fit from a craft into a measurable, repeatable, evidence-based discipline. For amateurs dealing with knee pain, lower back issues, or numb hands, his frameworks for fit-by-injury are the most thorough in the field.",
    keyIdeas: [
      "Bike fit is biomechanics, not aesthetics — the goal is to put the rider in the position that protects their joints over thousands of hours.",
      "Knee pain on the bike is almost always a saddle height or cleat alignment issue, not a training issue.",
      "Saddle height is set off the hip-knee-ankle relationship, not from a generic formula based on inseam.",
      "Lower-back pain is usually a core/hamstring strength deficit being unmasked by the bike position — fit is part of the answer, not all of it.",
      "Aero positioning for amateurs has to be earned through flexibility and core work — the position the pros hold takes years to build.",
    ],
    relatedHubs: ["cycling-strength-conditioning"],
  },

  "mark-sisson": {
    description:
      "American author and former US national-class marathon runner and triathlete. Founder of Mark's Daily Apple and Primal Kitchen (sold to Kraft-Heinz in 2018). Author of The Primal Blueprint, Primal Endurance, and 30+ other books on health and endurance.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Mark_Sisson",
    ],
    whyMatters:
      "Mark Sisson is the former US national-class marathon runner and triathlete who launched the modern primal/ancestral health movement with Mark's Daily Apple, Primal Kitchen, and the Primal Blueprint book series. He has written 30+ books on health, training, and endurance, including Primal Endurance, which argued that aerobic-base development through low-heart-rate training was undervalued by the endurance community. For Roadman listeners thinking about long-term training durability, body composition, and the trade-offs of high-volume aerobic work, his work is one of the most-cited starting points.",
    keyIdeas: [
      "Aerobic-base development through MAF heart-rate training is the foundation that supports all higher-intensity work.",
      "Low-carb endurance training has a place for some athletes, but most performance work still requires carbohydrate around hard sessions.",
      "Long-term training durability matters more than peak performance for most amateurs — programmes that wear out the rider lose the long game.",
      "Lifestyle factors (sleep, sun, movement, stress) account for a larger share of body composition outcomes than most training plans assume.",
      "Recovery is a leading indicator — track it, respect it, and train into it, not through it.",
    ],
    relatedHubs: ["cycling-nutrition", "cycling-training-plans"],
  },

  "laurens-ten-dam": {
    description:
      "Dutch former professional road cyclist (1999–2019) and current professional gravel racer. Tour de France GC top-10 finisher, founder of the Live Slow Ride Fast podcast. Now races gravel privately and runs the Ten Dam Foundation.",
    sameAs: [
      "https://en.wikipedia.org/wiki/Laurens_ten_Dam",
    ],
    whyMatters:
      "Laurens Ten Dam is one of the more articulate Dutch riders of his generation — a Tour de France GC top-10 finisher with Belkin and CCC, and now a serious gravel privateer who has finished Unbound, raced the Migration Gravel Race, and built one of the most-watched amateur gravel YouTube channels. His Live Slow Ride Fast podcast, co-hosted with Stefan Bolt, is one of the longest-running cycling podcasts in Europe. For amateurs interested in the transition from road racing to gravel and ultra-endurance — and the realities of training as a near-50 ex-pro — his content is exceptional.",
    keyIdeas: [
      "Gravel and ultra-endurance racing is reinforcing the long-distance volume that road training had quietly abandoned.",
      "Pacing 200-mile gravel events is closer to a slow Grand Tour stage than to a road race — discipline beats talent.",
      "Post-pro masters racing requires more recovery and more strength work than the pro version, not less.",
      "Live Slow Ride Fast is built on the principle that long endurance riding is best enjoyed at conversational pace.",
      "Privateer gravel is now economically viable because of YouTube, podcasts, and direct sponsor relationships.",
    ],
    relatedHubs: ["cycling-training-plans"],
  },

  "matt-bottrill": {
    description:
      "British former professional cyclist and current cycling coach. 7-time British national time trial champion, multiple British Best All-Rounder titles, and now founder of Matt Bottrill Performance Coaching. Specialises in time trial and triathlon coaching for amateur and pro athletes.",
    worksFor: {
      name: "Matt Bottrill Performance Coaching",
      type: "Organization",
    },
    whyMatters:
      "Matt Bottrill is one of the most decorated British TT specialists of his generation — seven national time trial titles and a string of British Best All-Rounder finishes — and now one of the country's most respected time trial coaches. His coaching at Matt Bottrill Performance Coaching has produced national, age-group world, and Ironman bike-leg champions. For amateurs trying to translate FTP into actual time trial results, his methodology is one of the cleanest in the UK: pacing discipline, position work, fuelling rehearsal, and equipment selection that earns its weight.",
    keyIdeas: [
      "Time trial pacing is a power discipline — the riders who win are the ones who hold their wattage cap when they do not feel like it.",
      "Position work is years long — saddle, bar, helmet, position adapt incrementally and reward the patient rider.",
      "Aero gains are real but only after fit is sorted — most amateurs leave 30 W on the table by chasing kit before position.",
      "Triathlon bike legs are not standalone TTs — they are paced for the run that follows, which fundamentally changes the wattage strategy.",
      "Strength and core work are non-negotiable for holding TT position over 25 miles or 180 km.",
    ],
    relatedHubs: ["ftp-training", "cycling-training-plans"],
  },

  "yanto-barker": {
    description:
      "British former professional road cyclist (2002–2017) and 2008 British road race champion. Founder and CEO of Le Col, a British cycling apparel company that supplies WorldTour and continental teams.",
    worksFor: {
      name: "Le Col",
      type: "Organization",
      url: "https://www.lecol.cc",
    },
    whyMatters:
      "Yanto Barker is the former British road race champion (2008) and founder and CEO of Le Col, the British cycling apparel company that has become one of the leading premium kit brands worldwide. He raced as a professional for over 15 years on UK and European continental teams, then built Le Col from a kit-room idea into a brand that now sponsors WorldTour teams and Grand Tour podium finishers. For amateurs interested in the business side of cycling, the realities of being a UK-based pro, or the technical decisions behind premium cycling apparel, his perspective is uniquely informed.",
    keyIdeas: [
      "Premium cycling apparel is built around fit, fabric, and durability — the visible price reflects the engineering, not just the logo.",
      "UK pro cycling pathway is harder than the Continental one because the domestic calendar is smaller — most riders go abroad.",
      "Sponsor relationships are a long game built on actually delivering value, not on the size of the team budget.",
      "Off-bike business in cycling works when you stay close to riders — the brands that drift lose the credibility that built them.",
      "Masters racing and amateur cycling now drive most of the apparel market — the pro peloton is the show, not the volume.",
    ],
    relatedHubs: ["cycling-coaching"],
  },

  "tim-podlogar": {
    description:
      "Slovenian sports nutritionist and researcher in carbohydrate metabolism and endurance performance. Peer-reviewed work on glucose-fructose oxidation and high-carb fuelling. Has worked with World Tour cyclists and Ironman athletes on race nutrition.",
    sameAs: [
      "https://www.researchgate.net/profile/Tim-Podlogar",
    ],
    whyMatters:
      "Tim Podlogar is the Slovenian sports nutritionist whose peer-reviewed work on high-rate glucose-fructose fuelling has shaped how the World Tour, Ironman field, and serious age-group athletes now fuel long efforts. His research on carbohydrate transporter saturation, on-bike absorption rates, and gut training matters because it provides the experimental basis for what every modern cyclist's fuelling plan now looks like. For Roadman listeners chasing high-carb fuelling protocols without GI distress, his work is one of the most-cited research starting points in cycling.",
    keyIdeas: [
      "Glucose-fructose ratios (typically around 1:0.8) bypass single-transporter saturation and allow 90–120 g/hr absorption.",
      "Gut training is real and trainable — chronic exposure to high-carb fuelling shifts what the gut can absorb without distress.",
      "On-bike fuelling is now the single most-improvable nutrition variable for amateur endurance athletes.",
      "Race-day fuelling has to be rehearsed in long training rides for weeks — gut tolerance is not a race-day decision.",
      "Periodised fuelling around training (low-carb easy, high-carb hard) supports body-composition goals without compromising sessions.",
    ],
    relatedHubs: ["cycling-nutrition"],
  },

  "dr-michael-gervais": {
    description:
      "American high-performance psychologist. Co-founder of Compete to Create with Pete Carroll, performance psychologist for the Seattle Seahawks during their Super Bowl-winning era, and host of the Finding Mastery podcast. Has worked with Olympic gold medallists, World Series champions, and a global roster of corporate leaders.",
    whyMatters:
      "Dr Michael Gervais is one of the most-cited high-performance psychologists working today. He worked with Pete Carroll's Seattle Seahawks during their Super Bowl-winning era, with Olympic gold medallists across multiple disciplines, and now hosts the Finding Mastery podcast — one of the most respected interview shows on elite performance. His framework for mindset, deliberate practice, and the relationship between fear and performance has shaped how a generation of professional and amateur athletes prepare for high-stakes events. For Roadman listeners chasing PBs, racing decisions, or just consistency, his work is a primary reference.",
    keyIdeas: [
      "High performance is a craft — the practices that produce gold medals are the same practices that produce sustained excellence anywhere.",
      "Fear is a performance signal, not a stop sign — the goal is to move toward what scares you, not to eliminate the fear itself.",
      "Mindfulness in sport is not a wellness add-on — it is the discipline that lets you stay present when results matter.",
      "Identity-led training (you are the kind of person who trains) outperforms outcome-led training (you want a result).",
      "Recovery from failure is the core skill — the athletes who last are the ones who recover faster, not the ones who fail less.",
    ],
    relatedHubs: ["cycling-recovery", "cycling-coaching"],
  },

  "dr-mark-gordon": {
    description:
      "American endocrinologist. Founder of Millennium Health Centers in California, specialising in traumatic brain injury (TBI) and hormonal recovery. Author of clinical materials on the hypothalamic–pituitary axis and post-TBI hormonal management.",
    worksFor: {
      name: "Millennium Health Centers",
      type: "Organization",
    },
    whyMatters:
      "Dr Mark Gordon is a US endocrinologist whose work on traumatic brain injury and hormonal recovery has made him one of the more debated voices in functional endocrinology. His clinics treat post-concussion syndromes, age-related hormonal decline, and the cumulative effects of athletic and military head trauma. For Roadman listeners interested in the male hormonal landscape after 40, the connection between cycling crashes and long-term health, or the realities of testosterone and recovery, his perspective raises questions worth hearing — though several of his framings remain debated within mainstream endocrinology, and his protocols should be considered alongside conventional clinical guidance.",
    keyIdeas: [
      "Traumatic brain injury can disrupt the hypothalamic–pituitary axis and produce long-term hormonal deficits.",
      "Cycling crashes that produce concussion deserve the same workup as other TBI events — most athletes do not get it.",
      "Free testosterone in masters athletes can be a more useful marker than total testosterone for performance and recovery.",
      "Hormonal optimisation is not the same as anabolic abuse — but the line is poorly drawn and easily abused.",
      "Sleep, stress, and energy availability are upstream of most hormonal issues for masters cyclists.",
    ],
    relatedHubs: ["cycling-recovery"],
  },

  "vasilis-anastopoulos": {
    description:
      "Greek performance coach. Senior coaching roles at Astana Pro Team and Soudal Quick-Step, and consultant to multiple WorldTour and continental teams. Background in exercise physiology with a focus on Grand Tour preparation, altitude camps, and threshold work.",
    whyMatters:
      "Vasilis Anastopoulos is one of the more underrated performance coaches working in the WorldTour. He has held senior coaching roles at Astana Pro Team and Soudal Quick-Step and has consulted with multiple Grand Tour-winning teams on aerobic-base development, threshold work, and altitude camps. His public conversations on the differences between Grand Tour and one-day Classics preparation, and his frameworks for periodising a 9-month racing season, are some of the more practical pro-tour insights in the cycling podcast world. For amateurs trying to understand how a Grand Tour team really structures a year, his work is a primary reference.",
    keyIdeas: [
      "Grand Tour preparation is built on multi-week aerobic-base blocks, not on threshold intervals.",
      "Altitude camps produce repeatable physiological adaptations when sequenced correctly with the racing calendar.",
      "Classics preparation is closer to track-and-power work than to GC training — the demands shift fundamentally.",
      "Periodised season planning works backwards from one or two A-races, with everything else as build or recovery.",
      "Recovery between racing blocks is the limiting factor for season-long form — most amateurs ignore this entirely.",
    ],
    relatedHubs: ["cycling-coaching", "cycling-training-plans", "ftp-training"],
  },

  "rosa-kloser": {
    description:
      "German professional gravel and road cyclist, 2024 Unbound Gravel 200 winner and 2025 German gravel national champion. Races both as a gravel privateer and for the CANYON//SRAM zondacrypto road team. PhD researcher in green shipping at Copenhagen Business School.",
    worksFor: {
      name: "CANYON//SRAM zondacrypto",
      type: "SportsTeam",
    },
    sameAs: [
      "https://en.wikipedia.org/wiki/Rosa_Kl%C3%B6ser",
      "https://www.canyon.com/en-us/blog-content/athletes/rosa-kloser-the-new-fast/b19122025.html",
    ],
    whyMatters:
      "Rosa Klöser is a model for the modern dual-discipline rider: a UCI Women's WorldTour rider for CANYON//SRAM zondacrypto on the road, and a winner of the 2024 Unbound Gravel 200 — the most prestigious privateer gravel race in the world. She combines that schedule with PhD research at Copenhagen Business School. For amateurs juggling life, work, and a full racing calendar, she is the proof that you can race seriously across disciplines without compromising either.",
    keyIdeas: [
      "Road and gravel fitness reinforce each other — the bike-handling, pacing, and fuelling demands of gravel translate back to the bunch.",
      "Privateer gravel is now a viable parallel career for World Tour-level riders, with its own sponsorship and prize-money economy.",
      "Long off-road events are won on fuelling discipline more than on raw power — the riders who blow up are the ones who under-eat in hour two.",
      "Position-specific gravel training (rough terrain at threshold) builds resilience that a smooth-road FTP block cannot.",
      "Balancing elite sport with a research career proves that the binary of pro-or-amateur is more flexible than the cycling press portrays.",
    ],
    relatedHubs: ["cycling-training-plans", "cycling-nutrition"],
  },
};

/** Look up overrides for a guest by slug. Returns undefined if no curated data. */
export function getGuestProfileOverride(
  slug: string,
): GuestProfileOverride | undefined {
  return GUEST_PROFILE_OVERRIDES[slug];
}
