import Link from "next/link";
import { requireAuth } from "@/lib/admin/auth";
import { maskEmail } from "@/lib/admin/events-store";
import {
  listDiagnosticCategoryDistribution,
  listDiagnosticToolStats,
  listRecentToolResults,
} from "@/lib/paid-reports/admin-queries";
import { listDefinitions, getDefinition } from "@/lib/diagnostics/framework/registry";
import { isToolSlug } from "@/lib/tool-results/types";

/**
 * Umbrella diagnostics dashboard — one row per registered tool plus a
 * category breakdown and the most recent result slugs. Sits alongside
 * the Plateau-specific /admin/diagnostic page (which still drives the
 * LLM QA workflow) and the /admin/paid-reports page (which drives the
 * Stripe funnel). Together they cover the three lenses on the same
 * data: how each tool performs, how its outputs cluster, and who is
 * actually converting.
 */

export const dynamic = "force-dynamic";

export default async function AdminDiagnosticsPage() {
  await requireAuth();
  const [toolStats, categoryRows, recent] = await Promise.all([
    listDiagnosticToolStats(),
    listDiagnosticCategoryDistribution(),
    listRecentToolResults(30),
  ]);

  const defs = listDefinitions();

  // Category rows come back grouped by tool+category; roll them up per
  // tool so the breakdown card stays compact.
  const categoriesByTool = new Map<
    string,
    Array<{ category: string; count: number }>
  >();
  for (const row of categoryRows) {
    const existing = categoriesByTool.get(row.toolSlug) ?? [];
    existing.push({ category: row.primaryCategory, count: row.count });
    categoriesByTool.set(row.toolSlug, existing);
  }

  return (
    <div className="space-y-8">
      <header className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-2xl font-semibold text-white">Diagnostics</h1>
          <p className="text-sm text-foreground-subtle mt-1">
            Every result generated by the diagnostic framework — plateau,
            fuelling, FTP zones. Email conversion and Ask Roadman hand-offs
            live here so we can spot which tools actually do the work.
          </p>
        </div>
        <Link
          href="/admin/paid-reports"
          className="text-sm rounded-md bg-white/5 border border-white/10 text-white hover:bg-white/10 px-3 py-1.5"
        >
          Paid reports →
        </Link>
      </header>

      {/* ── Per-tool funnel ─────────────────────────── */}
      <section className="rounded-md bg-white/5 border border-white/10 p-5">
        <h2 className="text-lg font-semibold text-white mb-4">Tool funnel</h2>
        {toolStats.length === 0 ? (
          <p className="text-sm text-foreground-subtle">
            No saved tool results yet.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-xs uppercase tracking-widest text-foreground-subtle">
                <tr>
                  <th className="py-2 pr-4">Tool</th>
                  <th className="py-2 pr-4">Total runs</th>
                  <th className="py-2 pr-4">Emailed</th>
                  <th className="py-2 pr-4">Ask handoffs</th>
                  <th className="py-2 pr-4">Email rate</th>
                  <th className="py-2 pr-4">Ask rate</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {toolStats.map((t) => {
                  const emailPct =
                    t.totalRuns > 0
                      ? ((t.emailedRuns / t.totalRuns) * 100).toFixed(0)
                      : "0";
                  const askPct =
                    t.totalRuns > 0
                      ? ((t.askHandoffs / t.totalRuns) * 100).toFixed(0)
                      : "0";
                  const title = isToolSlug(t.toolSlug)
                    ? getDefinition(t.toolSlug).title
                    : t.toolSlug;
                  return (
                    <tr key={t.toolSlug} className="text-foreground-muted">
                      <td className="py-2 pr-4 font-medium text-white">
                        {title}
                        <span className="ml-2 text-[10px] uppercase tracking-widest text-foreground-subtle">
                          {t.toolSlug}
                        </span>
                      </td>
                      <td className="py-2 pr-4">{t.totalRuns}</td>
                      <td className="py-2 pr-4">{t.emailedRuns}</td>
                      <td className="py-2 pr-4">{t.askHandoffs}</td>
                      <td className="py-2 pr-4 text-xs">{emailPct}%</td>
                      <td className="py-2 pr-4 text-xs">{askPct}%</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </section>

      {/* ── Category distribution per tool ──────────── */}
      <section className="rounded-md bg-white/5 border border-white/10 p-5">
        <h2 className="text-lg font-semibold text-white mb-4">
          Primary category distribution
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {defs.map((def) => {
            const rows = categoriesByTool.get(def.toolSlug) ?? [];
            const total = rows.reduce((s, r) => s + r.count, 0);
            return (
              <div
                key={def.toolSlug}
                className="rounded-md bg-white/5 border border-white/10 p-4"
              >
                <p className="text-xs uppercase tracking-widest text-foreground-subtle mb-3">
                  {def.title}
                </p>
                {rows.length === 0 ? (
                  <p className="text-xs text-foreground-subtle">
                    No categorised runs yet.
                  </p>
                ) : (
                  <ul className="space-y-1.5">
                    {rows.map((r) => {
                      const cat = def.categories.find((c) => c.key === r.category);
                      const label = cat?.label ?? r.category;
                      const pct = total > 0 ? (r.count / total) * 100 : 0;
                      return (
                        <li
                          key={r.category}
                          className="flex items-baseline justify-between gap-3 text-xs"
                        >
                          <span className="text-off-white truncate">{label}</span>
                          <span className="text-foreground-subtle">
                            {r.count}{" "}
                            <span className="text-[10px]">
                              ({pct.toFixed(0)}%)
                            </span>
                          </span>
                        </li>
                      );
                    })}
                  </ul>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* ── Recent runs ─────────────────────────────── */}
      <section className="rounded-md bg-white/5 border border-white/10 p-5">
        <h2 className="text-lg font-semibold text-white mb-4">Recent runs</h2>
        {recent.length === 0 ? (
          <p className="text-sm text-foreground-subtle">
            No tool results recorded yet.
          </p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="text-left text-xs uppercase tracking-widest text-foreground-subtle">
                <tr>
                  <th className="py-2 pr-4">When</th>
                  <th className="py-2 pr-4">Tool</th>
                  <th className="py-2 pr-4">Email</th>
                  <th className="py-2 pr-4">Primary result</th>
                  <th className="py-2 pr-4">Summary</th>
                  <th className="py-2 pr-4 text-right"></th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5">
                {recent.map((r) => {
                  const toolUrl = r.toolSlug === "ftp_zones" ? "ftp-zones" : r.toolSlug;
                  return (
                    <tr key={r.slug} className="text-foreground-muted">
                      <td className="py-2 pr-4 whitespace-nowrap text-xs">
                        {r.createdAt
                          .toISOString()
                          .slice(0, 16)
                          .replace("T", " ")}
                      </td>
                      <td className="py-2 pr-4 text-xs">{r.toolSlug}</td>
                      <td className="py-2 pr-4 font-mono text-xs text-white">
                        {maskEmail(r.email)}
                      </td>
                      <td className="py-2 pr-4 text-xs">
                        {r.primaryResult ?? "—"}
                      </td>
                      <td className="py-2 pr-4 text-xs text-foreground-subtle truncate max-w-sm">
                        {r.summary.length > 80
                          ? `${r.summary.slice(0, 80)}…`
                          : r.summary}
                      </td>
                      <td className="py-2 pr-4 text-right whitespace-nowrap">
                        <Link
                          href={`/results/${toolUrl}/${r.slug}`}
                          target="_blank"
                          className="text-xs text-foreground-muted hover:text-off-white hover:underline"
                        >
                          open →
                        </Link>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
