/**
 * Build-time generator for Method protocol bodies.
 *
 * Reads each module's protocol MDX (listed in `METHOD_MODULES`), strips
 * frontmatter, and inlines the bodies into `src/lib/method/protocol-content.ts`
 * as a plain string map.
 *
 * Why: `MethodProtocol.tsx` used to `fs.readFile` the protocol at a *dynamic*
 * path at request time. Next's output file tracer can't narrow a runtime path,
 * so it bundled the entire ~46MB `content/` directory into the
 * /method/modules/[slug] serverless function. Inlining the bodies as JS turns
 * that into an in-memory lookup — no runtime fs, nothing to trace.
 *
 * Run via `npm run method:protocols`. Wired into `prebuild` so deploys are
 * always in sync with the MDX on disk.
 */
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { METHOD_MODULES } from "../src/lib/method/modules";

const OUT_PATH = path.join(
  process.cwd(),
  "src/lib/method/protocol-content.ts",
);

function main() {
  const entries: string[] = [];
  let missing = 0;

  for (const mod of METHOD_MODULES) {
    const absPath = path.join(process.cwd(), mod.protocolMdxPath);
    let body: string;
    try {
      const raw = fs.readFileSync(absPath, "utf-8");
      body = matter(raw).content.trim();
    } catch {
      // Missing protocol → omit from the map. MethodProtocol renders its
      // "being finalised" fallback for any slug not present here.
      console.warn(
        `[method:protocols] missing ${mod.protocolMdxPath} — will fall back at runtime`,
      );
      missing += 1;
      continue;
    }
    entries.push(`  ${JSON.stringify(mod.slug)}: ${JSON.stringify(body)},`);
  }

  const file = `/**
 * AUTO-GENERATED by \`npm run method:protocols\` — do not edit by hand.
 *
 * Method protocol MDX bodies, inlined at build time so the
 * /method/modules/[slug] route does not fs-read (and therefore file-trace)
 * the entire content/ directory into its serverless function at runtime.
 *
 * Regenerate after editing anything in content/method/protocols/.
 */
export const PROTOCOL_BODIES: Record<string, string> = {
${entries.join("\n")}
};
`;

  fs.writeFileSync(OUT_PATH, file, "utf-8");
  console.log(
    `[method:protocols] wrote ${entries.length} protocol bodies to ${path.relative(
      process.cwd(),
      OUT_PATH,
    )}${missing ? ` (${missing} missing → fallback)` : ""}`,
  );
}

main();
